import hashlib
import json
import math
import os
from pathlib import Path
import subprocess
import sys

import pytest

from bhsm.interface import m5_m4_boundary_reduction as m4
from bhsm.interface import round_background_gauge_scalar_sector as v61


ROOT = Path(__file__).resolve().parents[1]
ARTIFACTS = ROOT / "artifacts"
DOC = ROOT / "docs" / "bhsm_parent_m5_to_m4_boundary_reduction_v6_1_1.md"
EXPECTED_HASHES = {
    "docs/frozen_predictions.md": "9ea147c56537520c86d3c4f9b864c6ba98bac9e64931edae96449f3b335a36c4",
    "docs/frozen_predictions.json": "f38210e0689871a25a9d5b0a1a4239883b7240cd7d0e25cdcf4c8cab72a2cbe7",
    "src/bhsm_model.py": "8fc5a59ac4fcafe4d3fca3249c46eaaf4ee2d0a019656333b75e3b1a989c8b3b",
}


def load(key):
    return json.loads((ARTIFACTS / m4.ARTIFACT_FILES[key]).read_text(encoding="utf-8"))


def public_text():
    paths = [DOC, ROOT / "STATUS.md", ROOT / "CLAIMS.md", ROOT / "ARTIFACT_INDEX.md", ROOT / "CLI_REFERENCE.md"]
    paths.extend(ARTIFACTS / name for name in m4.ARTIFACT_FILES.values())
    return "\n".join(path.read_text(encoding="utf-8") for path in paths)


def test_twenty_six_deterministic_claim_safe_artifacts():
    assert len(m4.ARTIFACT_FILES) == 26
    assert len(set(m4.ARTIFACT_FILES.values())) == 26
    built = m4.build_artifact_payloads(ROOT)
    for key, filename in m4.ARTIFACT_FILES.items():
        payload = load(key)
        assert payload["primary_result"] == m4.PRIMARY_RESULT, key
        assert payload["v6_1_bosonic_results_preserved"] is True, key
        assert payload["physical_fermion_equation_assumed"] is False, key
        assert payload["magnetic_monopole_sector_used"] is False, key
        assert payload["measured_input_used"] is False, key
        assert payload["frozen_predictions_changed"] is False, key
        assert (ARTIFACTS / filename).read_text(encoding="utf-8") == m4.deterministic_json(built[key])


def test_v61_bosonic_result_and_control_floor_are_preserved():
    assert v61.PRIMARY_RESULT == "BHSM_ROUND_BACKGROUND_GAUGE_SCALAR_ACTION_DERIVED_CONDITIONALLY"
    assert v61.round_minimum(1, 1)["gap_at_minimum_radius"] == pytest.approx(1 / 14)
    assert v61.control_ratios(0, 1, 1)["epsilon_control"] == pytest.approx(1 / 3)
    assert "1/3" in load("report")["central_answer"] or "time-control" in DOC.read_text(encoding="utf-8")


def test_s4_polar_metric_has_exact_warp_radius_normal_and_measure():
    row = m4.hyperspherical_geometry(3, math.pi / 6)
    assert row["warp"] == pytest.approx(0.5)
    assert row["level_radius"] == pytest.approx(1.5)
    assert row["spatial_measure_coefficient"] == pytest.approx(3**4 / 8)
    assert row["normal_contravariant_chi"] == pytest.approx(1 / 3)
    assert load("m5_geometry")["not_product"] is True
    with pytest.raises(ValueError):
        m4.hyperspherical_geometry(1, -0.1)


def test_equator_is_exact_totally_geodesic_lorentzian_m4():
    polar = m4.hyperspherical_geometry(2, math.pi / 2)
    assert polar["K_trace"] == pytest.approx(0, abs=1e-15)
    row = m4.equatorial_geometry(2, 0.1, 0.2)
    assert row["spatial_radius"] == 2
    assert row["spatial_volume"] == pytest.approx(16 * math.pi**2)
    assert row["K_mn_K_mn"] == 0
    assert load("equator")["status"] == "BHSM_ROUND_EQUATORIAL_M4_GEOMETRY_DERIVED"


def test_equator_family_has_no_preferred_axis_or_monopole_selection():
    payload = load("selection")
    assert "SO(5)-equivalent" in payload["family"]
    assert payload["preferred_axis"] is None
    assert payload["monopole_selection"] is False


def test_control_surface_is_not_promoted_to_physical_boundary():
    payload = load("boundary_firewall")
    assert "control_surface" in payload["status"].lower()
    assert "not supplied" in payload["independent_fields"]
    assert payload["control_surface_called_physical_boundary"] is False


def test_gauss_codazzi_keeps_normal_divergence_and_no_independent_eh_claim():
    payload = load("gauss_codazzi")
    assert "nabla_A" in payload["identity"]
    assert payload["normal_acceleration"] == "a_n^A=n^B nabla_B n^A; here a_n^t=H"
    assert "does not vanish" in payload["equator"]
    assert payload["independent_EH_term"] == "not generated by mere restriction"
    for chi in (0.4, math.pi / 2, 2.2):
        row = m4.gauss_codazzi_background(2, chi, 0.1, 0.2)
        assert row["R5_from_decomposition"] == pytest.approx(row["R5_direct"])
        assert row["residual"] == pytest.approx(0, abs=1e-12)


def test_ghy_background_zero_does_not_delete_variation():
    payload = load("ghy")
    assert "zero" in payload["equator_background"]
    assert "retained" in payload["variation"]
    assert payload["intrinsic_boundary_action"] is None


def test_normal_sturm_liouville_weight_spectrum_and_domains_are_exact():
    assert m4.normal_eigenvalue(0, 4) == 0
    assert m4.normal_eigenvalue(1, 4) == pytest.approx(0.25)
    with pytest.raises(ValueError):
        m4.normal_eigenvalue(-1, 1)
    payload = load("sturm")
    assert payload["weight"] == "sin^3 chi"
    assert "l(l+3)" in payload["spectrum"]
    assert "cos chi" in payload["odd"]


def test_green_form_vanishes_for_self_adjoint_endpoint_data():
    assert m4.green_boundary_form(0, 2, 0, 5, math.pi / 2) == 0
    assert m4.green_boundary_form(3, 0, 7, 0, math.pi / 2) == 0
    assert m4.green_boundary_form(3, 4, 7, 8, 0) == 0
    assert "vanishes" in load("boundary_conditions")["green_form"]


def test_exact_zero_mode_is_scalar_only_not_a_low_mode_relabel():
    payload = load("zero_modes")
    assert "constant" in payload["scalar_singlet"]
    assert "no zero eigenvalue" in payload["associated_nonconstant_S3_modes"]
    assert "no smooth global tangential vector zero mode" in payload["connection"]
    assert "no product-factor M4 graviton zero mode" in payload["metric"]


def test_full_and_hemisphere_scalar_profile_integrals_are_physical_warped_integrals():
    full = m4.scalar_profile_factors(3, "full")
    half = m4.scalar_profile_factors(3, "hemisphere")
    assert full["L_time"] == pytest.approx(4)
    assert full["L_spatial"] == pytest.approx(6)
    assert half["L_time"] == pytest.approx(2)
    assert half["L_spatial"] == pytest.approx(3)
    assert full["spatial_to_time"] == pytest.approx(1.5)
    with pytest.raises(ValueError):
        m4.scalar_profile_factors(1, "collar")


def test_smooth_bulk_zero_mode_does_not_fake_one_lorentzian_m4_coefficient():
    payload = load("scalar")
    assert payload["full_S4"]["ratio"] == "Z4_spatial/Z4_time=3/2"
    assert "requires boundary localization" in payload["Lorentzian_M4_status"]
    assert load("sp1")["status"] == "BHSM_M4_SP1_CONNECTION_NORMALIZATION_REQUIRES_LOCALIZATION"


def test_formal_gravity_profile_coefficient_is_exact_but_conditional():
    assert m4.m5_gravity_coefficient(2, 3) == pytest.approx(16 * math.pi**2 * 27)
    assert m4.formal_m4_gravity_coefficient(2, 3) == pytest.approx(16 * math.pi**2 * 27 * 4)
    payload = load("gravity")
    assert "not M4 times an interval" in payload["obstruction"]
    assert payload["observed_Planck_identification"] is None


def test_no_connection_length_or_standard_model_group_is_invented():
    payload = load("sp1")
    assert "common L_eff,A" in payload["boundary_profile"]
    assert payload["compactification_length_invented"] is False
    assert payload["physical_group"] is None


def test_nested_u1_remains_constrained_and_not_double_counted():
    payload = load("u1")
    assert payload["independent_field"] is False
    assert "no additional independent" in payload["zero_mode"]
    assert payload["hypercharge"] is None


def test_no_monopole_firewall_separates_chern_data_from_magnetic_charge():
    firewall = load("firewall")
    ledger = load("no_monopole")
    assert "first Chern class" in firewall["bundle_data"]
    assert firewall["physical_magnetic_interpretation"] is None
    assert "monopole harmonic basis" in firewall["excluded"]
    assert ledger["magnetic_charge_operator"] is None


def test_sigma_m4_homogeneous_normalization_and_potential_are_not_v5_imports():
    row = m4.scalar_m4_coefficients(2, -1, 3, 4)
    expected_z = 2 * 16 * math.pi**2 * 4**3 * (16 / 3)
    assert row["Z4_time"] == pytest.approx(expected_z)
    assert row["Z4_spatial"] / row["Z4_time"] == pytest.approx(1.5)
    assert row["potential_mass_squared"] == pytest.approx(-0.5)
    potential = load("potential")
    assert potential["v5"]["A_ST"] == "not derived"
    assert potential["v5"]["G_ST"] == "not derived"
    assert potential["v5"]["sigma_half"] == "not derived"


def test_sigma_is_bulk_even_zero_mode_not_an_unsourced_boundary_field():
    payload = load("sigma")
    assert payload["status"] == "BHSM_SIGMA_BULK_ZERO_MODE_SELECTED"
    assert "even bulk singlet" in payload["selected_role"]
    assert "independent boundary scalar" in payload["not_derived"]
    assert payload["desired_vacuum_used"] is False


def test_localization_audit_names_exact_missing_action_family_without_adding_it():
    payload = load("localization")
    terms = " ".join(row["term"] for row in payload["missing_terms"])
    assert "R4" in terms and "F^2" in terms and "V_loc" in terms
    assert payload["delta_brane_added"] is False
    assert payload["coefficient_values"] is None


def test_boundary_conditions_are_gauge_compatible_and_have_no_magnetic_sector():
    payload = load("boundary_conditions")
    assert payload["scalar"]["even"] == "u'=0"
    assert "gauge-compatible" in payload["Sp1"]
    assert "no magnetic sector" in payload["U1"]


def test_current_operators_remain_profile_conditional_and_nonmagnetic():
    payload = load("currents")
    assert "profile overlap" in payload["Sp1"]
    assert "requires g4_geom" in payload["canonical_coefficient"]
    assert payload["magnetic_charge"] is None
    assert payload["observed_charge"] is None


def test_aperture_keeps_amplitude_square_coupling_and_alpha_distinct():
    payload = load("aperture")
    assert "|I_R|^2" in payload["definitions"]["candidate"]
    assert "localized regular vector profile" in payload["missing"]
    assert payload["e_eff"] is None
    assert payload["alpha"] is None


def test_induced_m4_einstein_tensor_is_kinematic_not_observed_cosmology():
    row = m4.equatorial_geometry(2, 0.1, 0.2)
    assert row["G00"] == pytest.approx(3 * (0.01 + 0.25))
    assert load("equator")["m4_identified_as_observed_spacetime"] is False
    assert "observed-cosmology claim" in DOC.read_text(encoding="utf-8")


def test_fermionic_readiness_is_clifford_geometry_not_physical_equation():
    payload = load("fermionic")
    assert payload["status"] == "BHSM_FERMIONIC_CLIFFORD_BOUNDARY_READINESS_DERIVED"
    assert "mathematically defined" in payload["Clifford_bundle"]
    assert payload["physical_equation"] is None
    assert payload["fermionic_action_source"] is None
    assert payload["monopole_dependency"] is None


def test_scale_ledger_derives_geometric_lengths_but_no_absolute_unit():
    payload = load("scale")
    assert payload["geometric_normal_lengths"]["scalar_L_time_full"] == "4a/3"
    assert payload["new_geometric_primitive"] is False
    assert payload["L_eff_connection"] is None
    assert payload["absolute_unit"] is None


def test_parent_map_preserves_open_physical_coefficients_and_predictions():
    payload = load("parent_v5")
    assert "localization coefficient required" in payload["map"]["gauge"]
    assert "v5 boundary role conditional" in payload["map"]["sigma"]
    assert payload["frozen_values_changed"] is False


def test_report_is_constructive_and_routes_to_localization_source():
    payload = load("report")
    assert payload["status"] == m4.PRIMARY_RESULT
    assert payload["boundary_action_status"] == "BHSM_M5_TO_M4_BOUNDARY_ACTION_PARTIAL"
    assert "exact totally geodesic Lorentzian equator" in payload["central_answer"]
    assert "not a product M4 times an interval" in payload["central_answer"]
    assert payload["completion_gate"] == m4.COMPLETION_GATE
    assert payload["recommended_next_branch"] == "bhsm-m4-boundary-localization-action-source-v6-1-2"
    assert payload["full_bhsm_status"] == "FULL_BHSM_NOT_COMPLETE"


def test_cli_json_and_markdown():
    env = {**os.environ, "PYTHONPATH": str(ROOT / "src")}
    command = [sys.executable, "-m", "bhsm.interface", "m5-m4-boundary-reduction-status"]
    result = subprocess.run(command + ["--format", "json"], cwd=ROOT, env=env, check=True, capture_output=True, text=True)
    assert json.loads(result.stdout)["primary_result"] == m4.PRIMARY_RESULT
    markdown = subprocess.run(command + ["--format", "markdown"], cwd=ROOT, env=env, check=True, capture_output=True, text=True)
    assert "v6.1.1 Parent M5" in markdown.stdout


def test_public_claim_language_has_required_labels_and_no_promotions():
    text = public_text()
    required = [m4.PRIMARY_RESULT, "BHSM_ROUND_EQUATORIAL_M4_GEOMETRY_DERIVED", "BHSM_M4_GAUSS_CODAZZI_REDUCTION_DERIVED", "BHSM_NO_MONOPOLE_FIREWALL_DERIVED", "BHSM_FERMIONIC_CLIFFORD_BOUNDARY_READINESS_DERIVED", "FULL_BHSM_NOT_COMPLETE"]
    assert all(label in text for label in required)
    forbidden = ["M4 is observed spacetime", "Sp(1) is the Standard Model", "U(1) is hypercharge", "Chern number is magnetic charge", "alpha is derived", "sigma is the Higgs field", "full BHSM completion is achieved"]
    assert not any(phrase in text for phrase in forbidden)


def test_frozen_predictions_and_official_model_are_unchanged():
    for relative, digest in EXPECTED_HASHES.items():
        assert hashlib.sha256((ROOT / relative).read_bytes()).hexdigest() == digest
