from bhsm.interface.aether_n3_fresh_sbp_third_damped_newton_cone_v16_72 import v16_71_selected_raw_vector
def test_v16_71_state_has_complete_dimension():assert v16_71_selected_raw_vector().shape==(376,)
