"""Checks of the new bulk body; no heat/pole assertion."""
from pathlib import Path
import numpy as np
from scipy.linalg import expm
import json

ROOT=Path(__file__).resolve().parents[1]
ART=ROOT/'artifacts/muon_parent_source_contact_20261003/replay_reference'


def test_cartan_connection_matches_independent_koszul_contraction():
    with np.load(ART/'parent_metric_dirac_actions.npz') as p:
        G=p['parent_gamma'];points=p['gauss_rho'];cells=p['gauss_cells'];saved=p['spin_connection_contracted']
    with np.load(ROOT/'artifacts/muon_parent_geometry_20261001/replay_reference/local_parent_velocity_density.npz') as p:
        rho=p['rho'];dt=p['proper_times'][1]-p['proper_times'][0]
        x=(points-rho[cells])/np.diff(rho)[cells]
        def val(k):return p[k][0,cells]*(1-x)+p[k][0,cells+1]*x
        def dr(k):return (p[k][0,cells+1]-p[k][0,cells])/np.diff(rho)[cells]
        def time(k):
            a=(p[k][1]-p[k][0])/dt
            return a[cells]*(1-x)+a[cells+1]*x
        nu,C,r,z=(val(k) for k in ('proper_lapse','C_rho','base_radius','proper_shift_rho'))
        nr,Cr,rr,zr=(dr(k) for k in ('proper_lapse','C_rho','base_radius','proper_shift_rho'))
        Ct,rt=time('C_rho'),time('base_radius')
    eta=np.array([1,-1,-1,-1,-1])
    for g in (0,27,63):
        c=np.zeros((5,5,5))
        c[0,0,4]=nr[g]/(C[g]*nu[g])
        c[4,0,4]=-(Ct[g]-z[g]*Cr[g])/(nu[g]*C[g])+zr[g]/nu[g]
        for a in range(1,4):
            c[a,0,a]=-(rt[g]-z[g]*rr[g])/(nu[g]*r[g])
            c[a,4,a]=-rr[g]/(C[g]*r[g])
        for a,b,d in ((1,2,3),(2,3,1),(3,1,2)):
            c[d,a,b]=-2/r[g]
        c=c-c.transpose(0,2,1)
        lower=eta[:,None,None]*c
        result=np.zeros((4,4),complex)
        for a in range(5):
            for b in range(5):
                for d in range(5):
                    omega=(lower[b,a,d]-lower[a,d,b]+lower[d,b,a])/2
                    result+=1j*omega/4*G[a]@G[b]@G[d]
        np.testing.assert_allclose(np.kron(result,np.eye(16)),saved[g],atol=3e-14,rtol=4e-14)


def test_new_body_preserves_source_time_jet_and_full_connected_output():
    with np.load(ART/'parent_metric_dirac_actions.npz') as p:
        assert p['D5_on_same_source_image_b_coefficient_n3'].shape==(64,8,64,4,4,4)
        assert np.linalg.norm(p['D5_on_same_source_image_b_coefficient_n3'])>86
        assert np.linalg.norm(p['D5_on_same_source_image_b_tau_coefficient_n3'])>0
        K=p['K0_metric_common_A_probe_cut_density']
        np.testing.assert_allclose(K,K.conj().T,atol=5e-13)
        assert p['D5_metric_common_A_on_compact_probes'].shape==(64,64,64)
        assert np.linalg.norm(p['common_A_zero_order'])>0
        # Both remain stored; neither is silently made an identity matrix.
        assert np.linalg.norm(K)>4600
        assert 0.75<p['M0_probe_cut_density'][0,0]<0.76


def test_same_source_image_against_pointwise_group_directional_derivative():
    """Actual transported source, with an independent representation jet."""
    corrected=ROOT/'artifacts/muon_parent_source_rate_20261003/replay_reference/parent_source_rate_corrected.npz'
    # Expected source-time rate is the independently retained exterior-face
    # producer record, not the geometry cache or the corrected action output.
    record=json.loads((ROOT/'artifacts/muon_exterior_face_source_20261002/replay_reference/result.json').read_text())
    H_expected=record['frontier_source']['H']
    with np.load(corrected) as p, np.load(ART/'parent_source_contact.npz') as c:
        gp=29; cell=p['gauss_cells'][gp]; rho_gp=p['gauss_rho'][gp]
        columns=p['source_image_probe_columns'];gamma=p['parent_gamma']
        body=p['spin_connection_contracted'][gp]+p['common_A_zero_order'][gp]
        contact_rho=c['rho'];hat=c['spinor_probe_hat_nodes'];Tb=c['T_b']
        actual=np.zeros((8,64,4),complex);xi_point=np.zeros_like(actual)
        deriv=np.zeros((3,8,64,4),complex)
        for n in (1,3):
            j=n/2;w=np.arange(n,-n-1,-2)/2;plus=np.zeros((n+1,n+1),complex)
            for k in range(1,n+1):plus[k-1,k]=np.sqrt((j-w[k])*(j+w[k]+1))
            J=np.array([(plus+plus.T)/2,(plus-plus.T)/(2j),np.diag(w)])
            D=expm(-1j*.31*J[2])@expm(-1j*.62*J[1])@expm(-1j*.93*J[2])
            phi=np.sqrt(n+1)*D.conj()
            # E_a is generated by exp(-2it J_a) D. Differentiate the
            # representation before conjugating, rather than the coefficient.
            dphi=np.sqrt(n+1)*(-2j*J@D).conj()
            xi=c[f'Xi_A_unit_n{n}'][:,:,columns]
            xi_point+=np.einsum('Aocmk,mk->Aoc',xi,phi)
            deriv+=np.einsum('Aocmk,amk->aAoc',xi,dphi)
            actual+=np.einsum('Aocmk,mk->Aoc',p[f'D5_on_same_source_image_b_coefficient_n{n}'][gp],phi)
    with np.load(ROOT/'artifacts/muon_parent_geometry_20261001/replay_reference/local_parent_velocity_density.npz') as g:
        width=g['rho'][cell+1]-g['rho'][cell];x=(rho_gp-g['rho'][cell])/width
        def val(k):return (1-x)*g[k][0,cell]+x*g[k][0,cell+1]
        r,nu,C,z=(val(k) for k in ('base_radius','proper_lapse','C_rho','proper_shift_rho'))
        rr=(g['base_radius'][0,cell+1]-g['base_radius'][0,cell])/width
        time_slope=(g['base_radius'][1]-g['base_radius'][0])/(g['proper_times'][1]-g['proper_times'][0])
        rt=(1-x)*time_slope[cell]+x*time_slope[cell+1]
        chi=np.interp(rho_gp,contact_rho,hat)
        chi_r=(hat[cell+1]-hat[cell])/width
        f=Tb*chi/r;fr=Tb*(chi_r/r-chi*rr/r**2)
        ft=(-H_expected/2-rt/r)*f
    G64=np.array([np.kron(a,np.eye(16)) for a in gamma])
    expected=np.einsum('oi,Aic->Aoc',body,xi_point)*f
    expected+=np.einsum('oi,Aic->Aoc',1j*G64[0],xi_point)*(ft-z*fr)/nu
    expected+=np.einsum('oi,Aic->Aoc',1j*G64[4],xi_point)*fr/C
    expected+=sum(np.einsum('oi,Aic->Aoc',1j*G64[a+1],deriv[a])*f/r for a in range(3))
    np.testing.assert_allclose(actual,expected,atol=2e-14,rtol=2e-14)
