from bhsm.interface.aether_n3_fresh_sbp_second_measured_fractional_cone_v17_03 import completion_payload,v17_02_selected_raw_vector
def test_v17_02_state_has_complete_dimension():assert v17_02_selected_raw_vector().shape==(376,)
def test_second_measured_fractional_cone_validates():assert completion_payload()["validation_passed"]
