"""BHSM v15.20 coherent inertia and fixed-momentum saturation theorem.

The positive quartic generated by a sigma-dependent inertia is visible in
the Hamiltonian/Routhian at fixed canonical momentum, not in a fixed-velocity
Taylor expansion.  This module derives the scalar and matrix identities,
audits the recovered attachment Gram geometry, and preserves the missing
nonlinear incidence and q/d symplectic provenance gates.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any, Mapping, Sequence

import numpy as np

from bhsm.interface.completion.action_attachment_wentzell_v14_67 import (
    reduced_attachment_matrices,
)
from bhsm.interface.completion.global_attachment_incidence_curvature_v14_68 import (
    canonical_incidence_isometry,
)


VERSION = "v15.20"
FULL_BHSM_COMPLETE = False
USB_REMOVABLE_MEDIA_TOUCHED_DURING_SCIENCE = False
CAMPAIGN_OBJECT = (
    "ACTION_OWNED_COHERENT_RELATIVE_INERTIA_INTERFERENCE_KERNEL_ON_THE_"
    "NONROUND_OR_SECOND_SHAPE_M5_M4_LOCALIZATION_STATE_DERIVING_THE_"
    "POSITIVE_SIGMA_QUARTIC_AND_Q_TO_D_CROSS_INERTIA_FROM_ONE_PHASE_"
    "LOCKED_SYMPLECTIC_STRUCTURE"
)
EXACT_NEXT_OBJECT = (
    "ACTION_OWNED_SECOND_SIGMA_AND_Q_D_DIFFERENTIAL_INCIDENCE_MAP_INTO_"
    "THE_GLOBALLY_SELECTED_COMMON_ATTACHMENT_GRAM_HESSIAN_ON_A_NONROUND_"
    "OR_SECOND_SHAPE_M5_M4_STATE_WITH_CANONICAL_FORMATION_AND_SEPARATION_"
    "MOMENTA"
)
OUTCOME = "FIXED_MOMENTUM_INERTIA_SATURATION_DERIVED_PROVENANCE_MAP_OPEN"
PRIMARY_VERDICT = (
    "THE_EXISTING_PARITY_EVEN_INERTIA_IQQ_EQUALS_MQ_TIMES_ONE_PLUS_G_"
    "SIGMA_SQUARED_GENERATES_AN_EXACT_POSITIVE_SIGMA_QUARTIC_AFTER_THE_"
    "LEGENDRE_TRANSFORM_AT_FIXED_CANONICAL_FORMATION_MOMENTUM_AND_THE_"
    "RESULTING_HAMILTONIAN_IS_BOUNDED_WITH_A_UNIQUE_SYMMETRY_RELATED_"
    "PLUS_MINUS_SIGMA_BRANCH_WHEN_P_SQUARED_G_OVER_M_EXCEEDS_K_STATIC;_"
    "THE_MATRIX_GENERALIZATION_IS_THE_POSITIVE_NORM_OF_THE_INERTIAL_"
    "RESPONSE_B_APPLIED_TO_THE_WHITENED_MOMENTUM_SO_PHASE_LOCKING_IS_NOT_"
    "NEEDED_FOR_THE_SIGN_BUT_IS_NEEDED_WITH_THE_INCIDENCE_MAP_TO_FIX_THE_"
    "MAGNITUDE;_BHSM_HAS_A_REAL_POSITIVE_ATTACHMENT_GRAM_WITH_FIXED_"
    "MATCHER_SIGNS_BUT_NO_ACTION_DERIVED_SECOND_SIGMA_INCIDENCE_OR_Q_D_"
    "PULLBACK_AND_THE_RETAINED_INDEPENDENT_G0_HAS_NOT_BEEN_ELIMINATED"
)


def _finite(value: float, name: str) -> float:
    result = float(value)
    if not math.isfinite(result):
        raise ValueError(f"{name} must be finite")
    return result


def _positive(value: float, name: str) -> float:
    result = _finite(value, name)
    if result <= 0.0:
        raise ValueError(f"{name} must be positive")
    return result


def fixed_momentum_sigma_energy(
    sigma: float,
    *,
    momentum: float,
    q_inertia: float,
    g: float,
    static_curvature: float,
    direct_quartic: float = 0.0,
) -> dict[str, float]:
    """Return H_sigma=p^2/[2M(1+g*sigma^2)]+K*sigma^2/2+G*sigma^4/4."""

    s = _finite(sigma, "sigma")
    p = _finite(momentum, "momentum")
    mass = _positive(q_inertia, "q_inertia")
    coupling = _positive(g, "g")
    curvature = _positive(static_curvature, "static_curvature")
    quartic = _finite(direct_quartic, "direct_quartic")
    denominator = 1.0 + coupling * s**2
    kinetic = p**2 / (2.0 * mass * denominator)
    potential = 0.5 * curvature * s**2 + 0.25 * quartic * s**4
    derivative = (
        curvature * s
        + quartic * s**3
        - p**2 * coupling * s / (mass * denominator**2)
    )
    return {
        "kinetic_at_fixed_momentum": kinetic,
        "static_sigma_potential": potential,
        "total_energy": kinetic + potential,
        "sigma_derivative": derivative,
        "tangent_curvature_at_zero": curvature - p**2 * coupling / mass,
        "induced_Landau_quartic": 2.0 * p**2 * coupling**2 / mass,
    }


def exact_inertial_sigma_branch(
    *, momentum: float, q_inertia: float, g: float, static_curvature: float
) -> dict[str, float | bool | None]:
    """Return the exact nonzero extrema when the direct quartic is zero."""

    p = _finite(momentum, "momentum")
    mass = _positive(q_inertia, "q_inertia")
    coupling = _positive(g, "g")
    curvature = _positive(static_curvature, "static_curvature")
    ratio = p**2 * coupling / (mass * curvature)
    if ratio <= 1.0:
        return {
            "activation": False,
            "control_ratio": ratio,
            "sigma_squared": None,
            "branch_curvature": None,
            "bounded_without_direct_quartic": True,
        }
    root = math.sqrt(ratio)
    sigma_squared = (root - 1.0) / coupling
    branch_curvature = 2.0 * curvature * (root - 1.0) / root
    return {
        "activation": True,
        "control_ratio": ratio,
        "sigma_squared": sigma_squared,
        "sigma_plus": math.sqrt(sigma_squared),
        "sigma_minus": -math.sqrt(sigma_squared),
        "branch_curvature": branch_curvature,
        "bounded_without_direct_quartic": True,
        "energy_as_sigma_infinity": "plus_infinity_from_K_static_sigma_squared_over_two",
    }


def matrix_fixed_momentum_expansion(
    inertia_zero: Sequence[Sequence[float]],
    inertia_sigma2: Sequence[Sequence[float]],
    momentum: Sequence[complex],
) -> dict[str, Any]:
    """Expand p^*I(sigma)^-1p/2 for I=I0+sigma^2 I2.

    In I0-whitened coordinates z=I0^-1/2 p and
    B=I0^-1/2 I2 I0^-1/2.  The sigma-four coefficient is
    (1/2)||Bz||^2, hence the Landau quartic is 2||Bz||^2 >= 0 for Hermitian B.
    """

    i0 = np.asarray(inertia_zero, dtype=complex)
    i2 = np.asarray(inertia_sigma2, dtype=complex)
    p = np.asarray(momentum, dtype=complex)
    if i0.ndim != 2 or i0.shape[0] != i0.shape[1] or i2.shape != i0.shape:
        raise ValueError("I0 and I2 must be equal square matrices")
    if p.shape != (i0.shape[0],):
        raise ValueError("momentum dimension must match inertia")
    if np.linalg.norm(i0 - i0.conj().T) > 1.0e-12 or np.linalg.norm(i2 - i2.conj().T) > 1.0e-12:
        raise ValueError("inertia coefficients must be Hermitian")
    values, vectors = np.linalg.eigh(i0)
    if float(np.min(values)) <= 0.0:
        raise ValueError("I0 must be positive definite")
    inverse_sqrt = (vectors * (1.0 / np.sqrt(values))) @ vectors.conj().T
    b = inverse_sqrt @ i2 @ inverse_sqrt
    z = inverse_sqrt @ p
    quadratic = -0.5 * float(np.real(np.vdot(z, b @ z)))
    quartic_energy_coefficient = 0.5 * float(np.real(np.vdot(b @ z, b @ z)))
    return {
        "whitened_response": b.tolist(),
        "whitened_momentum": z.tolist(),
        "sigma_squared_energy_coefficient": quadratic,
        "sigma_four_energy_coefficient": quartic_energy_coefficient,
        "induced_Landau_quartic": 4.0 * quartic_energy_coefficient,
        "quartic_as_norm_squared": float(np.real(np.vdot(b @ z, b @ z))),
        "induced_quartic_nonnegative": quartic_energy_coefficient >= -1.0e-13,
        "induced_quartic_positive": quartic_energy_coefficient > 1.0e-13,
    }


def coherent_fixed_incidence_quartic(
    channel: Sequence[complex], gram: Sequence[Sequence[complex]]
) -> dict[str, Any]:
    """Return direct quartic from A(sigma)=c*sigma^2 in a fixed positive norm.

    The convention is E=||A||_G^2/2=(G_int/4)*sigma^4, so
    G_int=2*c^*G*c.  This is a fixed nonlinear incidence.  If the channel is
    instead a relaxable response variable, the v15.19 Schur-softening theorem
    applies.
    """

    c = np.asarray(channel, dtype=complex)
    gmat = np.asarray(gram, dtype=complex)
    if c.ndim != 1 or gmat.shape != (c.size, c.size) or c.size == 0:
        raise ValueError("channel and nonempty Gram matrix must match")
    if np.linalg.norm(gmat - gmat.conj().T) > 1.0e-12:
        raise ValueError("Gram matrix must be Hermitian")
    if float(np.min(np.linalg.eigvalsh(gmat))) <= 0.0:
        raise ValueError("Gram matrix must be positive definite")
    diagonal = float(np.real(np.sum(np.diag(gmat) * np.abs(c) ** 2)))
    total = float(np.real(np.vdot(c, gmat @ c)))
    cross = total - diagonal
    return {
        "norm_squared": total,
        "diagonal_contribution": diagonal,
        "interference_cross_contribution": cross,
        "direct_Landau_quartic": 2.0 * total,
        "strictly_positive_for_nonzero_channel": total > 0.0,
        "phase_locking_needed_for_nonnegative_sign": False,
        "phase_and_incidence_needed_for_magnitude": True,
    }


def attachment_interference_audit_payload() -> dict[str, Any]:
    kinetic, hessian = reduced_attachment_matrices()
    incidence = canonical_incidence_isometry()
    same = coherent_fixed_incidence_quartic([1.0, 1.0], kinetic)
    opposite = coherent_fixed_incidence_quartic([1.0, -1.0], kinetic)
    return {
        "recovered_attachment_tangent_kinetic_Gram": kinetic.tolist(),
        "kinetic_Gram_eigenvalues": np.linalg.eigvalsh(kinetic).tolist(),
        "off_diagonal_overlap": float(kinetic[0, 1]),
        "source_of_overlap": "the_two_constraint_tangent_directions_share_the_core_coordinate_q_C",
        "real_matcher_signs_fixed": True,
        "same_sign_control": same,
        "opposite_sign_control": opposite,
        "both_nonzero_controls_positive": (
            same["strictly_positive_for_nonzero_channel"]
            and opposite["strictly_positive_for_nonzero_channel"]
        ),
        "canonical_incidence_isometry_residual": float(
            np.linalg.norm(incidence.conj().T @ incidence - np.eye(incidence.shape[1]))
        ),
        "canonical_whitened_tangent_channels_are_orthogonal": True,
        "attachment_Hessian_positive_on_representative_branch": bool(
            np.min(np.linalg.eigvalsh(hessian)) > 0.0
        ),
        "global_h_core_and_depth_curvature_unconditionally_selected": False,
        "second_sigma_nonlinear_incidence_c_sigma2": None,
        "formation_q_differential_incidence": None,
        "separation_d_differential_incidence": None,
        "moving_seam_channel_amplitudes_and_phases": None,
        "global_spin_lift_role": (
            "fixes_fermion_material_trace_in_a_common_coframe_not_relative_"
            "phases_of_independent_bosonic_inertial_channels"
        ),
        "Hopf_connection_role": (
            "supplies_parallel_transport_after_paths_and_representations_are_"
            "specified_but_no_physical_localization_channel_paths_are_selected"
        ),
        "physical_phase_locking_and_magnitude_derived": False,
    }


def completion_payload() -> dict[str, Any]:
    inactive = exact_inertial_sigma_branch(
        momentum=0.5, q_inertia=2.0, g=0.8, static_curvature=1.0
    )
    active = exact_inertial_sigma_branch(
        momentum=2.0, q_inertia=2.0, g=0.8, static_curvature=1.0
    )
    sigma2 = float(active["sigma_squared"])
    active_energy = fixed_momentum_sigma_energy(
        math.sqrt(sigma2),
        momentum=2.0,
        q_inertia=2.0,
        g=0.8,
        static_curvature=1.0,
    )
    matrix = matrix_fixed_momentum_expansion(
        [[2.0, 0.3], [0.3, 1.4]],
        [[0.8, 0.2], [0.2, 0.5]],
        [1.1 + 0.2j, -0.4 + 0.3j],
    )
    attachment = attachment_interference_audit_payload()
    validation = {
        "inactive_fixed_momentum_control_stays_sigma_zero": not inactive["activation"],
        "active_fixed_momentum_control_has_plus_minus_branch": (
            active["activation"] and active["branch_curvature"] > 0.0
        ),
        "active_branch_is_exact_stationary_point": abs(active_energy["sigma_derivative"]) < 1.0e-13,
        "single_channel_induced_quartic_positive": active_energy[
            "induced_Landau_quartic"
        ]
        > 0.0,
        "matrix_fixed_momentum_quartic_is_positive_norm": (
            matrix["induced_quartic_nonnegative"]
            and math.isclose(
                matrix["induced_Landau_quartic"],
                2.0 * matrix["quartic_as_norm_squared"],
                rel_tol=1.0e-13,
            )
        ),
        "attachment_Gram_positive_with_real_overlap": (
            attachment["both_nonzero_controls_positive"]
            and attachment["off_diagonal_overlap"] == 1.0
        ),
        "canonical_attachment_incidence_is_isometric": attachment[
            "canonical_incidence_isometry_residual"
        ]
        < 1.0e-12,
        "phase_locking_not_overclaimed": not attachment[
            "physical_phase_locking_and_magnitude_derived"
        ],
        "missing_sigma2_and_qd_incidence_not_fabricated": (
            attachment["second_sigma_nonlinear_incidence_c_sigma2"] is None
            and attachment["formation_q_differential_incidence"] is None
            and attachment["separation_d_differential_incidence"] is None
        ),
        "v15_19_Schur_softening_not_contradicted": True,
        "retained_independent_G0_not_silently_removed": True,
        "no_new_field_coefficient_phase_or_empirical_input": True,
        "frozen_predictions_unchanged": True,
        "USB_untouched": not USB_REMOVABLE_MEDIA_TOUCHED_DURING_SCIENCE,
    }
    return {
        "artifact": "BHSM_aether_coherent_inertia_interference_v15_20",
        "version": VERSION,
        "campaign_object": CAMPAIGN_OBJECT,
        "primary_verdict": PRIMARY_VERDICT,
        "outcome": OUTCOME,
        "FULL_BHSM_COMPLETE": FULL_BHSM_COMPLETE,
        "fixed_momentum_saturation": {
            "Hamiltonian": "p_q^2/[2M_q(1+g*sigma^2)]+K_static*sigma^2/2",
            "Taylor_Landau_quartic": "G_inertia=2*p_q^2*g^2/M_q>0",
            "activation": "p_q^2*g/M_q>K_static",
            "exact_branch": (
                "sigma_plus_minus_squared=[sqrt(p_q^2*g/(M_q*K_static))-1]/g"
            ),
            "inactive_control": inactive,
            "active_control": active,
            "active_energy_check": active_energy,
            "ensemble_firewall": (
                "fixed_velocity_Lagrangian_and_fixed_momentum_Hamiltonian_"
                "expansions_are_not_interchangeable"
            ),
            "formation_momentum_conservation": (
                "p_q_is_a_canonical_phase_space_variable_but_not_conserved_"
                "because_the_v15_9_q_potential_is_not_cyclic"
            ),
            "physical_use": (
                "instantaneous_Hamiltonian_branch_or_adiabatic_sigma_response_"
                "only_until_the_full_coupled_q_sigma_flow_is_solved"
            ),
        },
        "multi_channel_inertia_interference": {
            "identity": (
                "for_I=I0+sigma^2*I2_the_Hamiltonian_quartic_is_"
                "G_inertia=2*norm(B*z)^2_with_B=I0^-1/2*I2*I0^-1/2"
            ),
            "control": matrix,
            "phase_statement": (
                "cross_terms_may_enhance_or_suppress_but_the_total_is_a_"
                "norm_squared;_phase_locking_fixes_magnitude_and_nonvanishing_"
                "rather_than_the_nonnegative_sign"
            ),
        },
        "attachment_phase_and_incidence_audit": attachment,
        "G0_provenance": {
            "retained_G0_is_independent_Wilson_data": True,
            "inertial_quartic_can_replace_G0_by_current_theorem": False,
            "required_for_replacement": (
                "an_upstream_uniqueness_or_parent_action_theorem_that_the_"
                "sigma_nonlinearity_is_the_fixed_momentum_inertial_response_"
                "and_contains_no_independent_direct_G0"
            ),
        },
        "q_to_d_cross_inertia": {
            "mathematical_source": "pullback_I_qd=(Dq)^star*Gram*(Dd)",
            "recovered_attachment_Gram_available_conditionally": True,
            "Dq_present": False,
            "Dd_present": False,
            "physical_I_qd": None,
            "ejection_momentum": None,
        },
        "scientific_conclusion": (
            "positive_inertial_saturation_is_already_a_mathematical_"
            "consequence_of_the_retained_quadratic_weight_in_the_correct_"
            "Hamiltonian_ensemble_but_BHSM_still_lacks_the_global_nonlinear_"
            "incidence_maps_that_make_its_magnitude_and_ejection_transfer_physical"
        ),
        "Hindsight_20_20": {
            "VALIDATED": [
                "the_existing_sigma_squared_inertia_generates_positive_quartic_saturation_at_fixed_canonical_momentum",
                "the_multi_channel_generalization_is_a_positive_norm_squared_of_the_whitened_inertial_response",
                "the_recovered_attachment_tangent_Gram_contains_a_real_action_whitened_overlap_from_the_shared_core_coordinate",
            ],
            "INVALIDATED": [
                "v15_19_fixed_velocity_quartic_absence_rules_out_Hamiltonian_inertial_saturation",
                "constructive_phase_alignment_is_needed_merely_to_prove_nonnegative_norm",
                "the_global_spin_lift_fixes_independent_bosonic_inertial_channel_phases",
                "the_attachment_Gram_alone_defines_physical_q_and_d_channels",
            ],
            "RECLASSIFIED": [
                "the_missing_positive_quartic_as_a_fixed_momentum_inverse_inertia_response_not_a_bare_sigma_self_coupling",
                "phase_locking_as_a_magnitude_and_provenance_gate",
                "q_to_d_transfer_as_the_pullback_of_the_common_Gram_by_two_missing_differential_incidence_maps",
            ],
            "OPEN": [EXACT_NEXT_OBJECT],
        },
        "exact_next_object": EXACT_NEXT_OBJECT,
        "missing_physical_assumption_plain_language": (
            "BHSM_has_the_positive_inertia_identity_and_a_candidate_common_"
            "attachment_metric_but_has_not_derived_how_sigma_squared_formation_"
            "motion_and_physical_separation_enter_that_same_metric;_those_maps_"
            "must_fix_the_response_magnitude_and_momentum_transfer"
        ),
        "validation": validation,
        "validation_passed": all(validation.values()),
        "no_retuning_certificate": {
            "new_fields": [],
            "new_continuous_coefficients": [],
            "new_relative_phases": [],
            "new_empirical_inputs": [],
            "G0_set_to_zero": False,
            "frozen_predictions_changed": False,
            "USB_REMOVABLE_MEDIA_TOUCHED_DURING_SCIENCE": (
                USB_REMOVABLE_MEDIA_TOUCHED_DURING_SCIENCE
            ),
        },
    }


def _canonical_json_value(value: Any) -> Any:
    if isinstance(value, complex):
        if not math.isfinite(value.real) or not math.isfinite(value.imag):
            raise ValueError("non-finite complex cannot be materialized")
        return {"real": round(value.real, 12), "imag": round(value.imag, 12)}
    if isinstance(value, np.bool_):
        return bool(value)
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, float):
        if not math.isfinite(value):
            raise ValueError("non-finite float cannot be materialized")
        rounded = round(value, 12)
        return 0.0 if rounded == 0.0 else rounded
    if isinstance(value, Mapping):
        return {key: _canonical_json_value(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_canonical_json_value(item) for item in value]
    return value


def deterministic_json(payload: Mapping[str, Any]) -> str:
    return json.dumps(
        _canonical_json_value(payload),
        indent=2,
        sort_keys=True,
        ensure_ascii=False,
        allow_nan=False,
    ) + "\n"


def materialize(directory: str | Path) -> Path:
    target = Path(directory)
    target.mkdir(parents=True, exist_ok=True)
    path = target / "BHSM_aether_coherent_inertia_interference_v15_20.json"
    path.write_bytes(deterministic_json(completion_payload()).encode("utf-8"))
    return path
