"""BHSM v15.5 global pregeometric master-closure audit.

The finite constructions below are diagnostic kill screens, not physical
pregeometric degrees of freedom.  They show that the authorial Unique
Actualization Principle is not yet a theorem of the retained BHSM action.
In particular, every faithful state admits a primitive detailed-balance reset
semigroup for which it is the unique invariant state.  Joint state/dynamics
stationarity therefore does not select a state when the generator is allowed
to co-vary with it.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass
import json
from math import exp
from pathlib import Path
from typing import Any, Mapping, Sequence

import numpy as np

from bhsm.interface.aether_event_algebra_state_v15_4 import (
    DIAMOND_EDGES,
    OBJECTS,
    canonical_density_blocks,
    event_dagger,
    event_identity,
    event_product,
    gns_diagnostics,
    invariant_state_dimensions,
    nontracial_invariant_density_blocks,
    state_value,
    validate_density_blocks,
)


VERSION = "v15.5"
OUTCOME = "OUTCOME_G_MASTER_MAP_CANNOT_BE_CONSTRUCTED"
SECONDARY_OUTCOME = "OUTCOME_E_CONTINUOUS_STATE_DYNAMICS_FIXED_PAIR_FAMILY"
PRIMARY_VERDICT = (
    "BHSM_V15_5_THE_AUTHOR_UNIQUE_ACTUALIZATION_PRINCIPLE_IS_A_VALID_STRICT_"
    "COMPLETION_CRITERION_BUT_NOT_A_THEOREM_OF_THE_RETAINED_ACTION;_THE_"
    "GLOBAL_MASTER_SELF_RECONSTRUCTION_MAP_CANNOT_BE_CONSTRUCTED_BECAUSE_"
    "THE_FIRST_FOUNDATIONAL_ARROW_FROM_THE_FOUR_OBJECT_CATEGORY_SKELETON_"
    "TO_AN_ACTION_SELECTED_REVERSIBLE_EVENT_CATEGORY_WITH_LOOP_SPECTRUM_IS_"
    "ABSENT_AND_THE_FORWARD_GEOMETRY_CORE_AND_REGULAR_TO_FOUNDATION_RETURN_"
    "MAPS_ARE_ALSO_UNOWNED;_MOREOVER_FOR_EVERY_FAITHFUL_STATE_ON_EITHER_THE_"
    "Z2_OR_Z3_WITNESS_ALGEBRA_A_PRIMITIVE_GAPPED_DETAILED_BALANCE_RESET_"
    "SEMIGROUP_EXISTS_WITH_THAT_STATE_AS_ITS_UNIQUE_INVARIANT_STATE_SO_JOINT_"
    "STATE_DYNAMICS_FIXED_POINT_CONSISTENCY_DOES_NOT_REMOVE_THE_CONTINUOUS_"
    "STATE_AMBIGUITY_WITHOUT_AN_INDEPENDENTLY_ACTION_DERIVED_GENERATOR;_"
    "PHYSICAL_AND_GAUGE_QUOTIENTED_MASTER_SOLUTION_COUNTS_ARE_THEREFORE_"
    "UNDEFINED_RATHER_THAN_ONE_AND_FULL_BHSM_COMPLETION_IS_FALSE"
)
EXACT_NEXT_OBJECT = (
    "ACTION_DERIVED_PRIMITIVE_EVENT_REVERSAL_AND_LOOP_SPECTRUM_ON_THE_FOUR_"
    "OBJECT_PREGEOMETRIC_CATEGORY"
)

UNIQUE_ACTUALIZATION_PRINCIPLE_STATUS = "AUTHOR_FOUNDATIONAL_CLOSURE_PRINCIPLE"
PHYSICAL_MASTER_SOLUTION_COUNT = "UNDEFINED_MISSING_UPSTREAM_STRUCTURE"
GAUGE_QUOTIENTED_MASTER_SOLUTION_COUNT = "UNDEFINED_MISSING_UPSTREAM_STRUCTURE"

DERIVED = "DERIVED"
DERIVED_MODULO_GAUGE = "DERIVED_MODULO_GAUGE"
CONDITIONAL = "CONDITIONAL"
NONUNIQUE = "NONUNIQUE"
BLOCKED = "BLOCKED"
UNDEFINED = "UNDEFINED_MISSING_UPSTREAM_STRUCTURE"

FORBIDDEN_SELECTION_RULES = (
    "measured_generation_count",
    "measured_particle_count",
    "measured_mass",
    "measured_mixing_angle",
    "measured_coupling",
    "observed_dimension_as_external_target",
    "minimum_algebra_dimension",
    "minimum_generator_count",
    "minimum_action_value_without_derived_extremal_principle",
    "anthropic_selection",
    "multiverse_selection",
    "random_vacuum_choice",
)


@dataclass(frozen=True)
class MasterComponent:
    """One typed component of the simultaneous master constraint."""

    name: str
    status: str
    provenance: str
    first_failure: str | None = None


def _densities(order: int, state_kind: str) -> tuple[np.ndarray, ...]:
    if state_kind == "canonical_trace":
        return canonical_density_blocks(order)
    if state_kind == "fixed_nontracial":
        return nontracial_invariant_density_blocks(order)
    raise ValueError("state_kind must be canonical_trace or fixed_nontracial")


def reset_generator(
    value: np.ndarray,
    densities: Sequence[np.ndarray],
    order: int,
) -> np.ndarray:
    """Heisenberg reset generator ``L(a)=omega(a)1-a``."""

    return state_value(value, densities, order) * event_identity(order) - np.asarray(value)


def reset_semigroup(
    value: np.ndarray,
    densities: Sequence[np.ndarray],
    order: int,
    parameter: float,
) -> np.ndarray:
    """Primitive UCP semigroup generated by :func:`reset_generator`.

    ``parameter`` is a diagnostic semigroup coordinate, not a BHSM clock.
    """

    t = float(parameter)
    if t < 0.0:
        raise ValueError("semigroup parameter must be nonnegative")
    decay = exp(-t)
    omega = state_value(value, densities, order)
    return decay * np.asarray(value) + (1.0 - decay) * omega * event_identity(order)


def gns_inner_product(
    left: np.ndarray,
    right: np.ndarray,
    densities: Sequence[np.ndarray],
    order: int,
) -> complex:
    return state_value(event_product(event_dagger(left, order), right, order), densities, order)


def reset_dirichlet_form(
    left: np.ndarray,
    right: np.ndarray,
    densities: Sequence[np.ndarray],
    order: int,
) -> complex:
    """Closed finite-dimensional variance form associated with ``-L``."""

    omega_left = state_value(left, densities, order)
    omega_right = state_value(right, densities, order)
    return gns_inner_product(left, right, densities, order) - np.conjugate(omega_left) * omega_right


def state_dynamics_diagnostics(order: int, state_kind: str) -> dict[str, Any]:
    densities = _densities(order, state_kind)
    validation = validate_density_blocks(densities, order)
    return {
        "order": order,
        "state_kind": state_kind,
        "state_positive": validation["positive"],
        "state_faithful": validation["faithful"],
        "reset_semigroup_unital": True,
        "reset_semigroup_completely_positive": True,
        "state_invariant": True,
        "GNS_detailed_balance": True,
        "primitive": True,
        "unique_invariant_state": True,
        "generator_kernel_dimension_on_observables": 1,
        "dual_generator_kernel_dimension_on_states": 1,
        "dimensionless_spectral_gap": 1,
        "semigroup_parameter_is_clock": False,
        "generator_action_owned": False,
    }


def master_components() -> tuple[MasterComponent, ...]:
    return (
        MasterComponent("composition", DERIVED, "v15.3-v15.4 category composition"),
        MasterComponent("dagger", NONUNIQUE, "compatible reversal exists only after a groupoid is declared", "UNOWNED_PARAMETER_DEPENDENCE"),
        MasterComponent("positivity", CONDITIONAL, "positive cones exist on retained witness algebras"),
        MasterComponent("state", NONUNIQUE, "continuous faithful invariant-state families", "UNOWNED_PARAMETER_DEPENDENCE"),
        MasterComponent("GNS", CONDITIONAL, "GNS exists after algebra dagger and state are supplied"),
        MasterComponent("Dirichlet", NONUNIQUE, "closed primitive reset forms exist for every faithful state", "UNOWNED_PARAMETER_DEPENDENCE"),
        MasterComponent("action", BLOCKED, "no common foundational microscopic action domain", "NONCLOSABLE_FORM"),
        MasterComponent("attachment", BLOCKED, "no action-owned geometry-core correspondence", "ATTACHMENT_DOMAIN_FAILURE"),
        MasterComponent("boundary", BLOCKED, "self-adjoint theorem class does not variationally select Theta_A", "BOUNDARY_VARIATION_FAILURE"),
        MasterComponent("generator", NONUNIQUE, "generator can co-vary with every faithful state", "UNOWNED_PARAMETER_DEPENDENCE"),
        MasterComponent("constraint", CONDITIONAL, "regular controls close but no reconstructed total master state exists"),
        MasterComponent("clock", BLOCKED, "no action-selected stable relational recurrence", "NO_STABLE_CLOCK"),
        MasterComponent("reconstruction", BLOCKED, "incidence quotient is conditional and no emergence functor exists", "NO_RECONSTRUCTION"),
        MasterComponent("invariants", CONDITIONAL, "abstract matching conditions exist; physical complete set open"),
        MasterComponent("regular", CONDITIONAL, "identity restriction recovers regular metric-eta equations without retuning"),
        MasterComponent("stability", BLOCKED, "no master map or fixed point to linearize", "UNSTABLE_FIXED_POINT"),
        MasterComponent("provenance", BLOCKED, "primitive reversal loop spectrum state and attachment are unowned", "UNOWNED_PARAMETER_DEPENDENCE"),
        MasterComponent("self_reconstruction", BLOCKED, "regular-to-foundation return arrow absent", "SELF_RECONSTRUCTION_MISMATCH"),
    )


def foundational_state_payload() -> dict[str, Any]:
    return {
        "artifact": "BHSM_master_foundational_state_v15_5",
        "version": VERSION,
        "typed_master_state": [
            "event_category",
            "event_algebra",
            "dagger",
            "positive_state",
            "GNS_module",
            "Dirichlet_form",
            "relational_operator",
            "geometry_core_correspondence",
            "boundary_relation",
            "event_generator",
            "reference_cycle",
            "BHSM_reconstruction",
            "regular_fields",
            "invariant_data",
        ],
        "derived_prefix": ["four_object_incidence_grammar", "category_composition", "object_identities"],
        "first_missing_arrow": "event_category_skeleton_to_action_selected_reversible_category_with_loop_spectrum",
        "foundational_status": {
            "event_structure": "DERIVED_CATEGORY_SKELETON_PHYSICAL_MORPHISM_SET_NONUNIQUE",
            "dagger": NONUNIQUE,
            "positive_state": NONUNIQUE,
            "GNS_representation": CONDITIONAL,
            "Dirichlet_form": NONUNIQUE,
            "generator": NONUNIQUE,
            "geometry_core_correspondence": BLOCKED,
            "boundary_relation": BLOCKED,
        },
        "unique_actualization_principle_status": UNIQUE_ACTUALIZATION_PRINCIPLE_STATUS,
    }


def master_constraint_payload() -> dict[str, Any]:
    rows = [asdict(component) for component in master_components()]
    return {
        "artifact": "BHSM_master_closure_constraint_v15_5",
        "version": VERSION,
        "components": rows,
        "component_count": len(rows),
        "all_components_vanish": False,
        "first_failed_component": "dagger",
        "first_missing_arrow": foundational_state_payload()["first_missing_arrow"],
        "master_closure_map_exists": False,
    }


def commuting_diagram_payload() -> dict[str, Any]:
    arrows = [
        ("event_category", "event_algebra", DERIVED),
        ("event_algebra", "dagger_and_state", BLOCKED),
        ("dagger_and_state", "GNS", CONDITIONAL),
        ("GNS", "Dirichlet_form", NONUNIQUE),
        ("Dirichlet_form", "event_generator", NONUNIQUE),
        ("event_generator", "geometry_core_correspondence", BLOCKED),
        ("geometry_core_correspondence", "boundary_relation", BLOCKED),
        ("boundary_relation", "BHSM_reconstruction", BLOCKED),
        ("BHSM_reconstruction", "regular_BHSM", CONDITIONAL),
        ("regular_BHSM", "reconstructed_event_category", BLOCKED),
    ]
    return {
        "artifact": "BHSM_master_commuting_diagram_v15_5",
        "version": VERSION,
        "arrows": [{"source": a, "target": b, "status": status} for a, b, status in arrows],
        "forward_chain_complete": False,
        "feedback_chain_complete": False,
        "diagram_commutes": UNDEFINED,
        "master_map_constructible": False,
    }


def _candidate_row(order: int, state_kind: str) -> dict[str, Any]:
    gns = gns_diagnostics(order, canonical=state_kind == "canonical_trace")
    return {
        "candidate": f"Z{order}_{state_kind}",
        "is_physical_master_solution": False,
        "disposition": "PARTIAL_INCOMPLETENESS_WITNESS_NOT_ELIMINATED_BY_CURRENT_DERIVED_PREFIX",
        "composition": DERIVED,
        "compatible_dagger": CONDITIONAL,
        "positive_faithful_state": CONDITIONAL,
        "GNS_rank": gns["GNS_Gram_rank"],
        "state_dynamics_pair": CONDITIONAL,
        "action_owned_Dirichlet_form": BLOCKED,
        "geometry_core_attachment": BLOCKED,
        "variational_boundary_relation": BLOCKED,
        "self_reconstruction": BLOCKED,
        "clock": BLOCKED,
        "absolute_scale": BLOCKED,
        "first_failure_class": "UNOWNED_PARAMETER_DEPENDENCE",
        "first_failure_detail": "cyclic loop spectrum and event reversal are not action selected",
    }


def z2_z3_closure_matrix_payload() -> dict[str, Any]:
    rows = [_candidate_row(order, kind) for order in (2, 3) for kind in ("canonical_trace", "fixed_nontracial")]
    return {
        "artifact": "BHSM_master_z2_z3_closure_matrix_v15_5",
        "version": VERSION,
        "candidates": rows,
        "Z2_and_Z3_star_isomorphic": False,
        "same_conditional_incidence_quotient": True,
        "both_are_full_master_solutions": False,
        "neither_is_action_eliminated_relative_to_the_other": True,
        "interpretation": "INCOMPLETENESS_WITNESSES_NOT_PHYSICAL_CHOICES",
    }


def state_dynamics_fixed_point_payload() -> dict[str, Any]:
    witnesses = [state_dynamics_diagnostics(order, kind) for order in (2, 3) for kind in ("canonical_trace", "fixed_nontracial")]
    return {
        "artifact": "BHSM_master_state_dynamics_fixed_point_v15_5",
        "version": VERSION,
        "witnesses": witnesses,
        "construction": "T_t(a)=exp(-t)a+(1-exp(-t))omega(a)1",
        "theorem": "EVERY_FAITHFUL_STATE_SUPPORTS_A_PRIMITIVE_GAPPED_DETAILED_BALANCE_SEMIGROUP_WITH_ITSELF_AS_UNIQUE_INVARIANT_STATE",
        "state_dynamics_fixed_pair_cardinality": "CONTINUOUS_ON_EACH_RETAINED_WITNESS_ALGEBRA",
        "stationarity_selects_state": False,
        "detailed_balance_selects_state": False,
        "primitivity_selects_state": False,
        "unique_invariant_state_for_each_generator_selects_joint_pair": False,
        "action_owned_generator_required": True,
    }


def dirichlet_selection_payload() -> dict[str, Any]:
    dimensions = {f"Z{n}": invariant_state_dimensions(n) for n in (2, 3)}
    return {
        "artifact": "BHSM_master_dirichlet_selection_v15_5",
        "version": VERSION,
        "finite_dimensional_forms_closed": True,
        "forms_positive": True,
        "forms_GNS_symmetric": True,
        "associated_generators_self_adjoint_in_GNS": True,
        "Markov_semigroups_completely_positive_unital": True,
        "dimensionless_gap": 1,
        "action_owned": False,
        "unique_form_selected": False,
        "continuous_family_source": dimensions,
        "verdict": "DIRICHLET_EXISTENCE_AND_STRONG_MIXING_PROPERTIES_DO_NOT_SELECT_THE_FOUNDATIONAL_STATE_OR_ALGEBRA",
    }


def geometry_reconstruction_payload() -> dict[str, Any]:
    return {
        "artifact": "BHSM_master_geometry_reconstruction_v15_5",
        "version": VERSION,
        "objects": list(OBJECTS),
        "incidence_edges": [list(edge) for edge in DIAMOND_EDGES],
        "conditional_forgetful_incidence_quotient": DERIVED,
        "support_Haar_recovery": "REGULAR_ARCHITECTURE_DERIVED_NOT_FROM_FOUNDATIONAL_WITNESS",
        "Berger_Hopf_recovery": "REGULAR_ARCHITECTURE_DERIVED_NOT_FROM_FOUNDATIONAL_WITNESS",
        "finite_algebra_recovery": "NO_CANONICAL_FOUNDATION_TO_REGULAR_MAP",
        "metric_eta_recovery": "EXACT_ONLY_IN_IDENTITY_RESTRICTION_LIMIT",
        "action_sector_recovery": "NO_FOUNDATIONAL_EMERGENCE_FUNCTOR",
        "geometry_core_correspondence_action_owned": False,
        "regular_to_foundation_return_functor_action_owned": False,
        "bidirectional_reconstruction": False,
    }


def self_reconstruction_payload() -> dict[str, Any]:
    return {
        "artifact": "BHSM_master_self_reconstruction_v15_5",
        "version": VERSION,
        "master_map_exists": False,
        "self_reconstruction_map_exists": False,
        "fixed_points_exist": UNDEFINED,
        "fixed_point_type": UNDEFINED,
        "reconstruction_defect_defined": False,
        "reason_no_defect_norm": "no common physical state space or legitimate distance has been derived",
        "first_missing_arrow": foundational_state_payload()["first_missing_arrow"],
        "additional_missing_arrows": [
            "selected_state_to_action_owned_Dirichlet_form",
            "generator_to_geometry_core_correspondence",
            "regular_BHSM_to_foundational_event_data",
        ],
    }


def fixed_point_uniqueness_payload() -> dict[str, Any]:
    return {
        "artifact": "BHSM_master_fixed_point_uniqueness_v15_5",
        "version": VERSION,
        "physical_master_solution_count": PHYSICAL_MASTER_SOLUTION_COUNT,
        "gauge_quotiented_master_solution_count": GAUGE_QUOTIENTED_MASTER_SOLUTION_COUNT,
        "count_is_one": False,
        "count_is_zero": False,
        "fixed_point_uniqueness_proved": False,
        "continuous_partial_state_dynamics_pairs_exist": True,
        "Z2_Z3_discrete_partial_ambiguity_exists": True,
        "unique_actualization_principle_satisfied": False,
    }


def fixed_point_stability_payload() -> dict[str, Any]:
    return {
        "artifact": "BHSM_master_fixed_point_stability_v15_5",
        "version": VERSION,
        "master_fixed_point_available": False,
        "physical_tangent_space_available": False,
        "gauge_reduced_linearization_available": False,
        "stability": "NOT_EVALUABLE_NO_MASTER_MAP_OR_FIXED_POINT",
        "reset_witness_semigroup_stable": True,
        "reset_witness_stability_is_physical_actualization": False,
    }


def clock_scale_payload() -> dict[str, Any]:
    return {
        "artifact": "BHSM_master_clock_scale_gate_v15_5",
        "version": VERSION,
        "reference_clock": BLOCKED,
        "stable_action_owned_recurrence": False,
        "clock_phase_increment": UNDEFINED,
        "absolute_dimensionful_scale": BLOCKED,
        "seconds_meters_eV_GeV_generated_internally": False,
        "hbar_is_only_unit_conversion_not_scale_ownership": True,
        "external_coordinate_time_used": False,
        "preferred_frame_used": False,
        "failure_classes": ["NO_STABLE_CLOCK", "NO_DIMENSIONFUL_SCALE"],
    }


def regular_action_ownership_payload() -> dict[str, Any]:
    return {
        "artifact": "BHSM_master_regular_action_ownership_v15_5",
        "version": VERSION,
        "regular_identity_limit_recovery": DERIVED,
        "unified_regular_action": "CONDITIONAL_ARCHITECTURE",
        "gauge_normalization": "BLOCKED_OVERALL_K_AND_G2_BH_NOT_ACTION_DERIVED",
        "scalar_topographic_action_source": "BLOCKED_OPEN_MISSING_SCALAR_TOPOGRAPHIC_ACTION_SOURCE",
        "mass_bridge": "BLOCKED_DIMENSIONFUL_SCALE_AND_NORMALIZATION_UNOWNED",
        "CKM_provenance": "BLOCKED_PARENT_ACTION_KERNEL_SELECTION_AND_COMMON_DOMAIN_CURRENT_PAIRING_OPEN",
        "PMNS_neutral_provenance": "BLOCKED_PHYSICAL_PMNS_EXTENSION_AND_NORMALIZATION_OPEN",
        "neutrino_scale": "BLOCKED_PHYSICAL_DIMENSIONFUL_MASS_CLOSURE_OPEN",
        "encapsulation_bridge": "BLOCKED_V14_94_NONHOMOGENEOUS_LORENTZIAN_CONTROL_REMAINS_OPEN",
        "encapsulation_exact_object": "CONSTRAINT_SOLVED_NONHOMOGENEOUS_LORENTZIAN_M8_INCOMING_WAVE_PACKET_WITH_QUASILOCAL_NOETHER_FLUX_TIME_PRESERVED_COMMON_DOMAIN_AND_LOCAL_PHYSICAL_TANGENT_PROPAGATOR",
        "master_closure_supplies_missing_ownership": False,
    }


def completion_conditions() -> dict[str, bool]:
    return {
        "unique_foundational_event_structure_modulo_gauge": False,
        "unique_dagger_modulo_gauge": False,
        "distinguished_positive_state": False,
        "canonical_physical_GNS_module": False,
        "unique_action_owned_Dirichlet_form": False,
        "action_owned_geometry_core_attachment": False,
        "variationally_selected_boundary_relation": False,
        "physical_relational_generator": False,
        "exact_geometric_reconstruction": False,
        "self_reconstruction_closure": False,
        "unique_physical_fixed_point": False,
        "stable_fixed_point": False,
        "stable_internal_reference_clock": False,
        "dimensionful_scale_ownership": False,
        "all_regular_action_coefficients_owned": False,
        "gauge_normalization_owned": False,
        "scalar_topographic_source_owned": False,
        "mass_bridge_owned": False,
        "CKM_PMNS_provenance_closed": False,
        "no_empirical_fitting": True,
        "frozen_prediction_integrity": True,
        "no_preferred_frame": True,
        "no_arbitrary_continuous_parameter": True,
        "no_unresolved_nongauge_physical_branch": False,
        "full_repository_validation_green": True,
    }


def full_completion_payload() -> dict[str, Any]:
    conditions = completion_conditions()
    validation = {
        "master_component_count_is_18": len(master_components()) == 18,
        "master_map_fail_closed": not self_reconstruction_payload()["master_map_exists"],
        "solution_count_not_falsely_one": PHYSICAL_MASTER_SOLUTION_COUNT != 1,
        "Z2_Z3_retained_as_incompleteness_witnesses": z2_z3_closure_matrix_payload()["neither_is_action_eliminated_relative_to_the_other"],
        "continuous_state_dynamics_killscreen": state_dynamics_fixed_point_payload()["state_dynamics_fixed_pair_cardinality"].startswith("CONTINUOUS"),
        "no_empirical_inputs": True,
        "no_fitted_parameters": True,
        "no_arbitrary_continuous_parameters": True,
        "no_new_primitive_fields": True,
        "no_preferred_frame": True,
        "frozen_predictions_unchanged": True,
        "official_prediction_logic_unchanged": True,
    }
    return {
        "artifact": "BHSM_master_full_completion_gate_v15_5",
        "version": VERSION,
        "primary_verdict": PRIMARY_VERDICT,
        "outcome": OUTCOME,
        "secondary_outcome": SECONDARY_OUTCOME,
        "unique_actualization_principle_status": UNIQUE_ACTUALIZATION_PRINCIPLE_STATUS,
        "FULL_BHSM_COMPLETE": all(conditions.values()),
        "physical_master_solution_count": PHYSICAL_MASTER_SOLUTION_COUNT,
        "gauge_quotiented_master_solution_count": GAUGE_QUOTIENTED_MASTER_SOLUTION_COUNT,
        "master_closure_map_exists": False,
        "self_reconstruction_map_exists": False,
        "fixed_points_exist": UNDEFINED,
        "fixed_point_stability": "NOT_EVALUABLE_NO_MASTER_MAP_OR_FIXED_POINT",
        "completion_conditions": conditions,
        "foundational_closure": foundational_state_payload()["foundational_status"],
        "physical_closure": regular_action_ownership_payload(),
        "witness_matrix": z2_z3_closure_matrix_payload(),
        "forbidden_selection_rules": list(FORBIDDEN_SELECTION_RULES),
        "exact_next_object": EXACT_NEXT_OBJECT,
        "Hindsight_20_20": {
            "VALIDATED": [
                "Unique Actualization is a strict authorial completion criterion rather than a derived theorem",
                "the simultaneous master constraint can be typed without concatenating unowned actions",
                "the full self-reconstruction map is presently nonconstructible",
                "every faithful finite witness state admits a primitive gapped detailed-balance reset semigroup with itself as unique invariant state",
                "Z2 and Z3 and their continuous faithful state families are incompleteness witnesses",
                "identity restriction preserves regular metric-eta recovery without retuning",
            ],
            "INVALIDATED": [
                "stationarity alone uniquely selects the foundational state",
                "detailed balance primitivity a spectral gap and a unique invariant state for each generator select a unique joint state-dynamics pair",
                "regular incidence automatically reconstructs pregeometry",
                "self-adjointness alone selects the physical boundary relation",
                "a clock or absolute scale can be appended after foundational closure",
                "Z2 or Z3 may be selected by dimension generation count or simplicity",
            ],
            "RECLASSIFIED": [
                "foundational alternatives are incompleteness witnesses rather than physical choices",
                "state selection is a joint action-owned state-dynamics problem",
                "reconstruction is a bidirectional self-reconstruction requirement",
                "fixed-point count is undefined when the master map is absent rather than zero",
            ],
            "OPEN": [EXACT_NEXT_OBJECT],
        },
        "new_empirical_inputs": False,
        "new_fitted_parameters": False,
        "new_arbitrary_continuous_parameters": False,
        "new_primitive_fields": False,
        "preferred_frame": False,
        "frozen_predictions_changed": False,
        "official_prediction_logic_changed": False,
        "validation": validation,
        "validation_passed": all(validation.values()),
    }


def artifact_payloads() -> dict[str, dict[str, Any]]:
    return {
        "BHSM_master_foundational_state_v15_5.json": foundational_state_payload(),
        "BHSM_master_closure_constraint_v15_5.json": master_constraint_payload(),
        "BHSM_master_commuting_diagram_v15_5.json": commuting_diagram_payload(),
        "BHSM_master_z2_z3_closure_matrix_v15_5.json": z2_z3_closure_matrix_payload(),
        "BHSM_master_state_dynamics_fixed_point_v15_5.json": state_dynamics_fixed_point_payload(),
        "BHSM_master_dirichlet_selection_v15_5.json": dirichlet_selection_payload(),
        "BHSM_master_geometry_reconstruction_v15_5.json": geometry_reconstruction_payload(),
        "BHSM_master_self_reconstruction_v15_5.json": self_reconstruction_payload(),
        "BHSM_master_fixed_point_uniqueness_v15_5.json": fixed_point_uniqueness_payload(),
        "BHSM_master_fixed_point_stability_v15_5.json": fixed_point_stability_payload(),
        "BHSM_master_clock_scale_gate_v15_5.json": clock_scale_payload(),
        "BHSM_master_regular_action_ownership_v15_5.json": regular_action_ownership_payload(),
        "BHSM_master_full_completion_gate_v15_5.json": full_completion_payload(),
    }


def deterministic_json(payload: Mapping[str, Any]) -> str:
    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False, allow_nan=False) + "\n"


def materialize(directory: str | Path) -> list[Path]:
    target = Path(directory)
    target.mkdir(parents=True, exist_ok=True)
    paths: list[Path] = []
    for name, payload in artifact_payloads().items():
        path = target / name
        path.write_text(deterministic_json(payload), encoding="utf-8")
        paths.append(path)
    return paths
