"""BHSM v6.20.0 critical lapse--Weyl Hessian/domain theorem.

The frozen P1+GHY+B1+matcher+scalar action fixes the bulk principal
two-four-dimensional-derivative Hessian of the lapse/Weyl pair.  The complete
mixed fold source and its B1 domain additionally require a covariant local
representative of the stored curvature tangent delta X.  The repository
stores only the on-shell scalar X(q) and not the corresponding metric-valued
pullback derivative, so the constrained Schur reduction stops before
numerics.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import sympy as sp


VERSION = "v6.20.0"
SPRINT = "bhsm-critical-lapse-weyl-hessian-v6-20-0"
SOURCE_MAIN_SHA = "d9b639a00715ad725f0a29e25bb015e5c26d6bb7"
V619_HEAD_SHA = "6607752008f20dc417b8be45e469b8ccf5d26b09"
PR179_MERGE_SHA = SOURCE_MAIN_SHA

PRIMARY_RESULT = "BHSM_CRITICAL_LAPSE_WEYL_DOMAIN_IS_UNDERDETERMINED"

ARTIFACT_FILES = {
    "operator": "BHSM_critical_lapse_weyl_operator_v6_20_0.json",
    "verdict": "BHSM_v6_20_0_fold_kinetic_sign_verdict.json",
}

PRESERVED_RESULTS = [
    "BHSM_INDUCED_THREADING_ACTION_REPRODUCES_CONSTRAINT_RESPONSE",
    "BHSM_FOLD_SOURCE_VANISHING_REPLACES_EXPLICIT_ENERGY_THRESHOLD",
    "BHSM_THREADING_RESPONSE_ACTION_RESTORES_NONEMPTY_FOLD_DOMAIN",
    "BHSM_FOLD_KINETIC_REQUIRES_ONE_MISSING_ACTION_BLOCK",
]

GUARDS = {
    "measured_input": False,
    "fitted_coefficient": False,
    "new_primitive": False,
    "new_scale": False,
    "new_action": False,
    "threshold": False,
    "boundary_tension": False,
    "tau_J": False,
    "neutral_work": False,
    "physical_mass_claim": False,
    "generic_pseudoinverse": False,
    "frozen_predictions_changed": False,
    "official_prediction_logic_changed": False,
}

T = sp.symbols("t", real=True, nonnegative=True)
EPSILON = sp.symbols("epsilon", real=True)
PSI = sp.symbols("psi", real=True)
KAPPA_1 = sp.symbols("kappa_1", positive=True, real=True)
C_PARTIAL = sp.symbols("C_partial", positive=True, real=True)
CHI_1 = sp.symbols("chi_1", positive=True, real=True)
TAU = sp.symbols("tau", real=True)


def a0(t: sp.Expr = T) -> sp.Expr:
    """Critical fixed-domain warp factor."""
    return sp.sqrt(2) * sp.sin(sp.pi * t / 4)


def lapse0() -> sp.Expr:
    return sp.pi / 4


def radial_weight(t: sp.Expr = T) -> sp.Expr:
    """Action measure after factoring the reference M4 measure."""
    return sp.simplify(lapse0() * a0(t) ** 4)


def determinant_factor_expansion() -> sp.Expr:
    """sqrt(det h)/[a0^4 sqrt(det hbar)] for h=(1+2 eps psi)a0^2 hbar."""
    return sp.expand((1 + 2 * EPSILON * PSI) ** 2)


def inverse_metric_factor_expansion() -> sp.Expr:
    """a0^2 h^{mu nu}/hbar^{mu nu} through O(epsilon^2)."""
    return sp.series(1 / (1 + 2 * EPSILON * PSI), EPSILON, 0, 3).removeO()


def background_identity_residuals(t: sp.Expr = T) -> dict[str, sp.Expr]:
    """Exact normalized critical P1/scalar background checks."""
    a = a0(t)
    n = lapse0()
    hubble = sp.diff(a, t) / (n * a)
    return {
        "hamiltonian": sp.trigsimp(hubble**2 - sp.Integer(2) / a**2 + 1),
        "radial_evolution": sp.simplify(sp.diff(a, t, 2) / (n**2 * a) + 1),
        "scalar_background": sp.Integer(0),
        "B1_matching": sp.simplify(
            (sp.diff(a, t) / (n * a)).subs(t, 1) - sp.Integer(1)
        ),
        "critical_scalar_boundary": sp.Integer(0),
    }


def bulk_principal_density() -> str:
    """Manual conformal/ADM identity after M4 integration by parts."""
    return (
        "6*kappa_1*N0*a0^2["
        "(D A).(D psi)+(D psi).(D psi)]"
    )


def H_AA_crit(t: sp.Expr = T) -> sp.Expr:
    """No (D A)^2 term is generated by the two-derivative P1 block."""
    _ = t
    return sp.Integer(0)


def C_H_crit(t: sp.Expr = T) -> sp.Expr:
    """Off-diagonal lapse--Weyl coefficient in the radial weighted pairing."""
    return sp.simplify(6 * KAPPA_1 / a0(t) ** 2)


def C_H_crit_dagger(t: sp.Expr = T) -> sp.Expr:
    """The real multiplication block is its own formal adjoint."""
    return C_H_crit(t)


def H_psipsi_crit(t: sp.Expr = T) -> sp.Expr:
    """Bulk Weyl coefficient in the radial weighted pairing."""
    return sp.simplify(12 * KAPPA_1 / a0(t) ** 2)


def L_Apsi_crit(t: sp.Expr = T) -> sp.ImmutableMatrix:
    """Derived bulk principal Hessian on Y_rad=(A,psi)^T."""
    return sp.ImmutableMatrix(
        [
            [H_AA_crit(t), C_H_crit_dagger(t)],
            [C_H_crit(t), H_psipsi_crit(t)],
        ]
    )


def B1_endpoint_hessian() -> sp.Expr:
    """Coefficient H_B1 in (1/2) H_B1 (D psi_J)^2."""
    return 12 * C_PARTIAL


def threading_profile(
    t: sp.Expr = T,
    tau: sp.Expr = TAU,
    chi_1: sp.Expr = CHI_1,
) -> sp.Expr:
    return sp.simplify(-tau * sp.pi * chi_1 * t / 16)


def J_A_threading(
    t: sp.Expr = T,
    tau: sp.Expr = TAU,
    chi_1: sp.Expr = CHI_1,
) -> sp.Expr:
    """Action-derived threading part of the mixed lapse source."""
    b = threading_profile(t, tau, chi_1)
    h_t = sp.diff(a0(t), t) / a0(t)
    return sp.simplify(6 * KAPPA_1 * b * h_t / (lapse0() ** 2 * a0(t) ** 2))


def J_psi_threading_operator(
    t: sp.Expr = T,
    tau: sp.Expr = TAU,
    chi_1: sp.Expr = CHI_1,
) -> str:
    """Unintegrated first-radial-derivative threading source."""
    coefficient = sp.sstr(
        sp.simplify(
            -6
            * KAPPA_1
            * threading_profile(t, tau, chi_1)
            / (lapse0() ** 2 * a0(t) ** 2)
        )
    )
    return f"({coefficient})*partial_t"


def action_provenance_ledger() -> dict[str, Any]:
    return {
        "normalization": {
            "representative": "q5=kappa_1=Z5=1, C_partial/kappa_1=1/2",
            "P1": "(1/2) integral_M5 sqrt(-g)(kappa_1 R5-kappa_0)",
            "GHY": "kappa_1 integral_boundary sqrt(-h) K on each cap",
            "B1": "integral_M4 sqrt(-h) C_partial R4",
            "matcher": (
                "integral_M4 sqrt(-h) Lambda^(mu nu)"
                "(h_mu nu-iota^*g_mu nu)"
            ),
            "scalar": (
                "-(Z5/2) integral_M5 sqrt(-g)(grad sigma)^2-U5"
            ),
            "cap_count": "two reflected bulk caps; one common B1",
        },
        "source_locations": [
            "src/bhsm/interface/intrinsic_m4_junction_background.py:231",
            "src/bhsm/interface/intrinsic_m4_junction_background.py:232",
            "src/bhsm/interface/intrinsic_m4_junction_background.py:233",
            "src/bhsm/interface/intrinsic_m4_junction_background.py:242",
            "src/bhsm/interface/intrinsic_m4_junction_background.py:244",
            "src/bhsm/interface/intrinsic_m4_junction_background.py:252",
            "src/bhsm/interface/scalar_wall_junction_audit.py:273",
            "src/bhsm/interface/scalar_wall_junction_audit.py:326",
            "src/bhsm/interface/scalar_wall_junction_audit.py:327",
        ],
        "new_coefficient_used": False,
    }


def expansion_ledger() -> dict[str, Any]:
    return {
        "ansatz": (
            "N=N0(1+A), h_mu_nu=a0^2[(1+2psi)hbar_mu_nu"
            "+2D_muD_nu E], delta sigma=q u1"
        ),
        "order": "O(epsilon^2), exactly two M4 derivatives",
        "gauge_order": (
            "form S=B-a0^2 partial_t E; reproduce momentum equation; "
            "then choose E=0"
        ),
        "threading": (
            "Pi_perp B=-tau(pi chi_1/16)t Pi_perp q; C_Sigma=0"
        ),
        "fixed_support": "zeta=0",
        "determinant": sp.sstr(determinant_factor_expansion()),
        "inverse_metric": sp.sstr(inverse_metric_factor_expansion()),
        "radial_measure": sp.sstr(radial_weight()),
        "bulk_principal_density": bulk_principal_density(),
        "GHY": "normal derivatives of delta g cancel cap by cap",
        "B1_endpoint": "6 C_partial (D psi_J)^2",
        "matcher": "algebraic after h=iota^*g and Lambda elimination",
        "scalar_direct": "K_scalar=2 integral a0^2 u1^2 d rho >=2",
    }


def operator_ledger() -> dict[str, Any]:
    return {
        "Y_rad": ["A", "psi"],
        "weight": "N0 a0^4 dt",
        "order_in_t_bulk_principal": 0,
        "H_AA": sp.sstr(H_AA_crit()),
        "C_H": sp.sstr(C_H_crit()),
        "C_H_dagger": sp.sstr(C_H_crit_dagger()),
        "H_psipsi": sp.sstr(H_psipsi_crit()),
        "L_matrix": [[sp.sstr(v) for v in row] for row in L_Apsi_crit().tolist()],
        "B1_endpoint_hessian": sp.sstr(B1_endpoint_hessian()),
        "formal_adjoint": "L_bulk^dagger=L_bulk under weight N0 a0^4",
        "bulk_Green_form": "0 (real multiplication operator)",
        "B1_antisymmetric_Green_form": (
            "12 C_partial[psi1(1)psi2(1)-psi2(1)psi1(1)]=0"
        ),
        "saddle_determinant": sp.sstr(sp.factor(L_Apsi_crit().det())),
        "L_AA_zero_verified": True,
        "complete_operator": False,
    }


def missing_metric_tangent_ledger() -> dict[str, Any]:
    return {
        "name": "covariant X-metric pullback tangent T_X",
        "formula": (
            "T_X,mu_nu(x,x')="
            "delta hbar_mu_nu[X](x)/delta X(x')|X=2, "
            "with delta R4[T_X]=tau chi_1 q"
        ),
        "tensor_operator_type": (
            "symmetric-2-tensor-valued scalar Green operator modulo M4 "
            "diffeomorphisms"
        ),
        "coefficient_dimensions": (
            "L^2 before q5=1 normalization because hbar is dimensionless "
            "and X has dimension L^-2"
        ),
        "action_sectors": "P1 R4 + intrinsic B1 R4 + exact metric matcher",
        "boundary_domain_role": (
            "fixes the independent scalar B1 junction projection, the "
            "q--A/q--psi source, its endpoint term, and the split from the "
            "Einstein-frame Weyl contribution"
        ),
        "exact_repository_entry_points": [
            "src/bhsm/interface/scalar_wall_fold_morse_sheet_selection.py:218",
            "src/bhsm/interface/scalar_wall_fold_morse_sheet_selection.py:233",
            "src/bhsm/interface/fold_einstein_frame_kinetic_reduction.py:359",
            "src/bhsm/interface/intrinsic_m4_junction_background.py:244",
            "src/bhsm/interface/intrinsic_m4_junction_background.py:252",
        ],
        "stored_information": (
            "only scalar delta X=tau chi_1 and the homogeneous matched "
            "junction; no local metric representative or adjoint domain"
        ),
        "minimum_future_derivation": (
            "choose a covariant regulated M4 metric family hbar[X], compute "
            "its gauge-quotiented Frechet derivative, insert it into the "
            "already frozen P1+GHY+B1+matcher action, and derive the two "
            "independent scalar B1 conditions"
        ),
        "new_action_required": False,
    }


def domain_and_reduction_ledger() -> dict[str, Any]:
    return {
        "threading_unresolved_trace_count": 0,
        "bulk_principal_operator_order": 0,
        "full_operator_order": None,
        "domain_condition_count": None,
        "pole_regular_series": (
            "A and psi regular is necessary; leading powers cannot be "
            "completed without the lower radial/domain block"
        ),
        "B1_conditions": None,
        "kernel_dimension": None,
        "adjoint_kernel_dimension": None,
        "source_compatibility": None,
        "actual_symmetry_on_domain": None,
        "Fredholm_status": None,
        "J_A_threading": sp.sstr(J_A_threading()),
        "J_psi_threading": J_psi_threading_operator(),
        "J_rad_complete": False,
        "Hamiltonian_constraint_reproduced": (
            "principal C_H psi plus the threading source only"
        ),
        "momentum_constraint_reproduced": True,
        "Weyl_equation_reproduced": (
            "bulk principal part only; B1 scalar projection missing"
        ),
        "Schur_complement": (
            "K_red=K_direct-<J_rad,L_Apsi^-1 J_rad> is not defined "
            "until T_X fixes J_rad and Dom(L)"
        ),
        "analytic_elimination_launched": False,
        "numerical_solve_launched": False,
        "generic_pseudoinverse_used": False,
        "earliest_obstruction": "domain/source completion requires T_X",
    }


def kinetic_verdict_ledger() -> dict[str, Any]:
    return {
        "K_scalar": "2 integral a0^2 u1^2 d rho >=2>0",
        "K_Weyl_exact": "3 chi_1^2(4-pi)^2/(16 pi)",
        "K_Weyl_numeric": 1.220620174933802,
        "K_shift_endpoint_red": None,
        "k_q_E": None,
        "uncertainty": None,
        "sign": None,
        "sheet_dependence": None,
        "scalar_sign_dependence": (
            "known threading/principal blocks are scalar-sign independent"
        ),
        "fold_field_status": "kinetic sign unresolved",
        "physical_mass": None,
        "primary_theorem": PRIMARY_RESULT,
    }


def _common(name: str) -> dict[str, Any]:
    return {
        "artifact": name,
        "version": VERSION,
        "sprint": SPRINT,
        "source_main_sha": SOURCE_MAIN_SHA,
        "v6_19_head_sha": V619_HEAD_SHA,
        "pr_179_merge_sha": PR179_MERGE_SHA,
        "primary_result": PRIMARY_RESULT,
        "preserved_results": list(PRESERVED_RESULTS),
        **GUARDS,
    }


def artifact_payloads() -> dict[str, dict[str, Any]]:
    return {
        "operator": {
            **_common("BHSM_critical_lapse_weyl_operator_v6_20_0"),
            "provenance": action_provenance_ledger(),
            "expansion": expansion_ledger(),
            "background_residuals": {
                key: sp.sstr(value)
                for key, value in background_identity_residuals().items()
            },
            "operator": operator_ledger(),
            "missing_object": missing_metric_tangent_ledger(),
            "domain_and_reduction": domain_and_reduction_ledger(),
        },
        "verdict": {
            **_common("BHSM_v6_20_0_fold_kinetic_sign_verdict"),
            "kinetic": kinetic_verdict_ledger(),
            "integrity": {"guards": dict(GUARDS)},
        },
    }


def deterministic_json(payload: dict[str, Any]) -> str:
    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=True) + "\n"


def artifact_bytes() -> dict[str, bytes]:
    return {
        ARTIFACT_FILES[key]: deterministic_json(payload).encode("utf-8")
        for key, payload in artifact_payloads().items()
    }


def materialize_artifacts(root: Path) -> list[Path]:
    target = root / "artifacts"
    target.mkdir(parents=True, exist_ok=True)
    paths: list[Path] = []
    for filename, content in artifact_bytes().items():
        path = target / filename
        path.write_bytes(content)
        paths.append(path)
    return paths
