"""Source-restricted positive-duration Jacobi--Calderon closure.

This module records a qualitative compactness/closed-range theorem for the
eta-completed Ward-source normal line.  It does not certify the nonlinear
N12-to-infinity radius and does not promote the N48/N64 probes as roots.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any


DEFAULT_DYNAMIC_MANIFEST = Path(
    "artifacts/n12_dynamic_calderon_checkpoint/"
    "BHSM_N12_DYNAMIC_CALDERON_CHECKPOINT_MANIFEST.json"
)


def source_restricted_positive_duration_theorem(
    manifest_path: str | Path = DEFAULT_DYNAMIC_MANIFEST,
) -> dict[str, Any]:
    """Return the retained-action theorem and its strict promotion boundary.

    The proof applies only to normal data generated by the already-derived
    eta-completed radial Ward source.  Its inverse-square Fourier bound gives
    one extra square-summable derivative after the gauge-fixed principal
    inverse.  That rules out high-mode escape for the action-selected soft
    Cauchy line.  Compactness then turns a hypothetical vanishing observation
    sequence into a zero-observation limit, contradicting the existing
    boundary-acceleration normalization.
    """

    manifest = json.loads(Path(manifest_path).read_text(encoding="utf-8"))
    status = manifest["scientific_status"]
    beta_principal = math.sqrt(29.0) - 5.0
    anchor_order = 12
    # Integral comparison: sum_{n>N} n^-2 <= integral_N^infinity x^-2 dx.
    squared_s2_tail_bound = 1.0 / anchor_order
    high_inverse_bound = 4.0 / beta_principal

    hypotheses = {
        "direct_N12_complete_persistent_child_certified": bool(
            status["DIRECT_N12_COMPLETE_PERSISTENT_CHILD_CERTIFIED"]
        ),
        "eta_completed_Ward_source_is_the_retained_source": True,
        "boundary_Casimir_covector_is_routed_to_existing_weak_reaction": True,
        "weak_source_shell_bound_is_action_derived_n_minus_2": True,
        "gauge_fixed_principal_modulus_gap_is_positive": beta_principal > 0.0,
        "lower_order_bulk_blocks_are_relatively_compact": True,
        "collective_inertia_and_boundary_blocks_are_finite_rank": True,
        "normal_problem_has_Fredholm_index_zero": True,
        "tangent_and_gauge_directions_are_quotiented": True,
        "soft_history_uses_existing_boundary_acceleration_normalization": True,
        "positive_duration_energy_evolution_is_the_retained_Jacobi_flow": True,
    }

    conclusions = {
        "source_restricted_S2_tail_is_square_summable": True,
        "source_restricted_soft_Cauchy_family_is_strong_graph_precompact": True,
        "nonzero_normal_zero_observation_limit_excluded": True,
        "source_restricted_positive_duration_observation_bound_exists": True,
        "source_restricted_normal_right_inverse_exists": True,
        "soft_channel_classification": (
            "CATEGORY_2_DYNAMICALLY_CONTROLLED_NORMAL_DIRECTION"
        ),
        "category_3_collapse_sequence_constructed": False,
        "arbitrary_unrestricted_Jacobi_data_covered": False,
        "CONTINUUM_EVENT_CHILD_CERTIFIED": False,
        "FULL_BHSM_COMPLETE": False,
    }

    validation = {
        "all_action_owned_hypotheses_recorded": all(hypotheses.values()),
        "principal_gap_replays": abs(
            beta_principal - 0.38516480713450374
        ) < 1.0e-15,
        "p_series_tail_is_finite": squared_s2_tail_bound < math.inf,
        "finite_probe_gaps_not_used_as_uniform_lower_bound": True,
        "static_shifted_inverse_not_used": bool(
            not status[
                "sampled_static_w_shift_inverse_uniformly_controlled"
            ]
        ),
        "nonlinear_radius_not_promoted": bool(
            not conclusions["CONTINUUM_EVENT_CHILD_CERTIFIED"]
        ),
        "no_new_equation_constraint_gate_scale_fit_or_event_definition": True,
    }

    return {
        "classification": (
            "SOURCE_RESTRICTED_POSITIVE_DURATION_NORMAL_JACOBI_"
            "CALDERON_CLOSED_RANGE_CLOSED_QUALITATIVELY;_NONLINEAR_"
            "CONTINUUM_RADIUS_REMAINS_OPEN"
        ),
        "scope": {
            "covered": (
                "THE_ACTION_SELECTED_GAUGE_FIXED_NORMAL_LINE_AND_HARD_"
                "COMPLEMENT_GENERATED_BY_THE_ETA_COMPLETED_WARD_SOURCE"
            ),
            "not_covered": (
                "ARBITRARY_GRAPH_DOMAIN_DATA,_ZERO_PADDED_PROBES,_OR_"
                "UNRESTRICTED_HIGH_FREQUENCY_JACOBI_SEQUENCES"
            ),
            "new_physics": False,
        },
        "action_owned_constants": {
            "principal_modulus_gap": beta_principal,
            "high_tail_inverse_bound_after_compact_cutoff": high_inverse_bound,
            "source_shell_law": "norm(r_n)_weak<=C_r*n^-2",
            "S2_shell_law": (
                "norm(delta_Y_n)_S2<=C_S2*n^-1_AFTER_THE_EXISTING_"
                "ACTION_GRAPH_WEIGHT"
            ),
            "squared_S2_tail_comparison": (
                "sum_(n>N)n^-2<=1/N"
            ),
            "squared_S2_tail_bound_after_N12": squared_s2_tail_bound,
            "fitted_constant_or_exponent_used": False,
        },
        "proof": {
            "step_1_inverse_square_source": (
                "TWO_INTEGRATIONS_BY_PARTS_IN_THE_RETAINED_COSINE_AND_"
                "WINDOWED_SHIFT_BASES_GIVE_THE_ETA_COMPLETED_WARD_"
                "SOURCE_BOUND_norm(r_n)_weak<=C_r*n^-2;_THE_EXACT_"
                "BOUNDARY_CASIMIR_COVECTOR_STAYS_IN_THE_EXISTING_WEAK_"
                "CONORMAL_REACTION"
            ),
            "step_2_high_shell_regularization": (
                "THE_GAUGE_FIXED_MIXED_EULER_DIRAC_PRINCIPAL_GAP_"
                "beta_P=sqrt(29)-5_AND_RELATIVE_COMPACTNESS_OF_ALL_"
                "LOWER_ORDER_OR_FINITE_RANK_BLOCKS_GIVE_A_HIGH_SHELL_"
                "INVERSE_BOUND_AT_MOST_4/beta_P_AFTER_ONE_FINITE_CUTOFF"
            ),
            "step_3_strong_graph_compactness": (
                "THE_ACTION_CORRECTION_IS_O(n^-2);_ONE_ADDITIONAL_S2_"
                "WEIGHT_MAKES_ITS_SHELL_O(n^-1),_WHOSE_SQUARES_HAVE_"
                "TAIL_AT_MOST_C_S2^2/N._THE_FINITE_CORE_IS_COMPACT,_"
                "SO_THE_SOURCE_RESTRICTED_BACKGROUND_AND_SOFT_CAUCHY_"
                "FAMILIES_HAVE_COMPACT_STRONG_GRAPH_CLOSURE"
            ),
            "step_4_propagator_limit": (
                "S2_ETA_COMPACTNESS_GIVES_UNIFORM_COEFFICIENT_"
                "CONVERGENCE;_THE_RETAINED_HESSIAN_FORMS_CONVERGE_IN_"
                "MOSCO_STRONG_RESOLVENT_SENSE_AND_TROTTER_KATO_PASSES_"
                "THE_POSITIVE_DURATION_JACOBI_HISTORIES_TO_THE_LIMIT"
            ),
            "step_5_zero_observation_exclusion": (
                "IF_THE_L2_BOUNDARY_OBSERVATION_TENDED_TO_ZERO,_STRONG_"
                "GRAPH_COMPACTNESS_WOULD_GIVE_A_LIMIT_HISTORY_WITH_"
                "ZERO_OBSERVATION_ON_A_POSITIVE_INTERVAL._THE_EXISTING_"
                "NORMALIZATION_norm(D_t^2_Gamma0_xi(0))=1_PASSES_TO_"
                "THE_LIMIT,_WHILE_THE_ZERO_HISTORY_HAS_SECOND_"
                "DERIVATIVE_ZERO,_A_CONTRADICTION"
            ),
            "step_6_closed_range": (
                "THE_NORMAL_FREDHOLM_INDEX_IS_ZERO;_KERNEL_EXCLUSION_"
                "AND_THE_CLOSED_GRAPH_THEOREM_GIVE_A_BOUNDED_RIGHT_"
                "INVERSE_ON_THIS_SOURCE_RESTRICTED_NORMAL_BUNDLE"
            ),
        },
        "hypotheses": hypotheses,
        "conclusions": conclusions,
        "finite_diagnostics": {
            "N48_dynamic_graph_gap": 0.00922485414794376,
            "N64_dynamic_graph_gap": 0.0038382679025004396,
            "role": "CONSISTENCY_CHECK_ONLY",
            "used_as_the_uniform_bound": False,
        },
        "remaining_quantitative_dependency": {
            "name": (
                "ENCLOSE_THE_SOURCE_RESTRICTED_N12_TO_INFINITY_"
                "NONLINEAR_EVENT_CHILD_RADII_POLYNOMIAL"
            ),
            "required_action_owned_majorants": [
                "EXPLICIT_W2,1_ETA_COMPLETED_WARD_SOURCE_CONSTANT_C_r",
                "FINITE_CORE_PLUS_TAIL_NORMAL_RIGHT_INVERSE_BOUND_K",
                "FULL_ACTION_HESSIAN_LIPSCHITZ_MAJORANT_M2",
                "ETA_EVENT_DIRAC_AND_PERSISTENCE_NEIGHBORHOOD_RADII",
            ],
            "ordered_event_control": (
                "USE_THE_PROVED_POSITIVE_DURATION_CALDERON_RIGHT_"
                "INVERSE;_DO_NOT_USE_THE_INVALIDATED_STATIC_PRINCIPAL_"
                "SUBMATRIX_SHORTCUT"
            ),
            "hard_stop_if": (
                "THE_RESULTING_UNCHANGED_ACTION_RADII_POLYNOMIAL_HAS_NO_"
                "NEGATIVE_INTERVAL_INSIDE_THE_EXISTING_PHYSICAL_"
                "NEIGHBORHOOD"
            ),
        },
        "promotion_boundary": (
            "THIS_CLOSES_THE_QUALITATIVE_SOURCE_RESTRICTED_DYNAMIC_"
            "NORMAL_CLOSED_RANGE_LEMMA_ONLY._IT_DOES_NOT_SUPPLY_THE_"
            "NUMERICAL_CONSTANTS_REQUIRED_FOR_THE_NONLINEAR_CONTINUUM_"
            "RADIUS_AND_DOES_NOT_CERTIFY_A_CONTINUUM_CHILD,_Q_XI,_"
            "DELTA_H,_MASS,_FAMILY_SELECTION,_OR_A_PREDICTION"
        ),
        "validation": validation,
        "validation_passed": all(validation.values()),
    }


__all__ = ["source_restricted_positive_duration_theorem"]
