"""Deterministic provenance matrix for recovered BHSM objects."""

from __future__ import annotations

from typing import Any


def support_representation_candidates() -> list[dict[str, Any]]:
    return [
        {
            "historical_name": "multiplicative support characters",
            "source_type": "merged action audit",
            "source_path": "src/bhsm/interface/envelopment/support_weight_derivation_v11_0.py",
            "branch": "agent/bhsm-canonical-unification-completion-v11-0",
            "commit": "76ca770729d73805e79e2e6528fc735dcdd559ec",
            "PR": 214,
            "campaign_version": "v11.0",
            "equation": "F_a(upsilon)=upsilon^w_a",
            "status_at_that_time": "weights and lambda_D not action fixed",
            "tests": ["tests/test_bhsm_supported_parent_action_v11_0.py"],
            "artifact": "artifacts/BHSM_supported_parent_action_v11_0.json",
            "classification": "PARTIAL_INGREDIENT",
            "reason": "derives the character family but not a primitive representation or equivalence quotient",
        },
        {
            "historical_name": "stratified support action",
            "source_type": "merged action-family audit",
            "source_path": "src/bhsm/interface/envelopment/support_action_v10_4.py",
            "branch": "agent/bhsm-spacetime-removal-completion-v10-4",
            "commit": "04a38d962e32613ff4486f6ef068a01d24a9e4ac",
            "PR": 213,
            "campaign_version": "v10.4",
            "equation": "S_upsilon=int sqrt(-G)[-Z(upsilon)|grad upsilon|^2/2-U+(F_C-1)X_C+(F_W-1)X_W]",
            "status_at_that_time": "Z, U, support couplings, and core action open",
            "tests": ["tests/test_bhsm_support_action_v10_4.py"],
            "artifact": "artifacts/BHSM_support_action_gate_v10_4.json",
            "classification": "PARTIAL_INGREDIENT",
            "reason": "supplies the exact derivative terms needed by the quotient but not their selected coefficients/domain",
        },
        {
            "historical_name": "covariant bulk-boundary reduction functor",
            "source_type": "merged reduction theorem",
            "source_path": "src/bhsm/interface/master_action/reduction.py",
            "branch": "bhsm-covariant-bulk-boundary-reduction-functor-v7-1",
            "commit": "97cb8d4e65da0dbdb7cf198324d763cba552cd32",
            "PR": 200,
            "campaign_version": "v7.1",
            "equation": "pi_85=id_I x p_H with normalized retained-mode pairing and explicit fiber volume",
            "status_at_that_time": "covariant pushforward adopted",
            "tests": ["tests/test_bhsm_complete_unified_parent_action_v7_0.py"],
            "artifact": "artifacts/BHSM_covariant_bulk_boundary_reduction_functor_v7_1.json",
            "classification": "PARTIAL_INGREDIENT",
            "reason": "owns geometric reduction and normalized measures but no GD action on support-charged objects",
        },
        {
            "historical_name": "1:2:7 active-generator sector weights",
            "source_type": "merged representation/action reconciliation",
            "source_path": "src/bhsm/interface/master_action/coefficients.py",
            "branch": "bhsm-complete-unified-parent-action-v7-0",
            "commit": "aea655dcb12690629337fe34a2c9d74b8e53bb72",
            "PR": 199,
            "campaign_version": "v7.0",
            "equation": "w_1:w_2:w_3=1:2:7",
            "status_at_that_time": "rejected as action/representation trace weights",
            "tests": ["tests/test_bhsm_complete_unified_parent_action_v7_0.py"],
            "artifact": "artifacts/BHSM_master_coefficient_input_ledger_v7_0.json",
            "classification": "INVALIDATED",
            "reason": "active-generator screen counts are not support characters or representation trace coefficients",
        },
        {
            "historical_name": "primitive lattice common-rescaling quotient",
            "source_type": "merged exact lemma and action gate",
            "source_path": "src/bhsm/interface/action_lemmas/primitive_lattice_rule.py",
            "branch": "bhsm-action-lemma-closure-v2-1",
            "commit": "339ba7c13117e9c4b9a4ace78574db68646e3d5d",
            "PR": 103,
            "campaign_version": "v2.1 action lemmas",
            "equation": "(3,6,12)/gcd=(1,2,4)",
            "status_at_that_time": "open without action quotient of common incidence rescalings",
            "tests": ["tests/test_primitive_lattice_normalization_rule.py"],
            "artifact": "artifacts/BHSM_primitive_lattice_normalization_rule_v2_1.json",
            "classification": "CONDITIONAL_CANDIDATE",
            "reason": "directly anticipates the quotient issue but records that the action-invariance proof is absent",
        },
        {
            "historical_name": "coframe multiplier and sector winding",
            "source_type": "unmerged tested branch",
            "source_path": "src/coframe_sector_winding_closure.py",
            "branch": "origin/bhsm-coframe-sector-winding-closure",
            "commit": "820198fd6a561c28ecbeba45c980ee8575c52a55",
            "PR": None,
            "campaign_version": "historical closure sprint",
            "equation": "base=-4 T3 C_f; winding=(1,2,4)",
            "status_at_that_time": "COFRAME_MULTIPLIER_NOT_DERIVED and SECTOR_WINDING_RULE_NOT_DERIVED",
            "tests": ["tests/test_coframe_sector_winding_closure.py"],
            "artifact": "audits/coframe_sector_winding_closure_audit.json",
            "classification": "CONDITIONAL_CANDIDATE",
            "reason": "tested and structurally motivated, but explicitly not forced by action variation",
        },
        {
            "historical_name": "boundary action to representation connection",
            "source_type": "unmerged tested branch",
            "source_path": "src/bhsm_boundary_action_to_rep_connection.py",
            "branch": "origin/bhsm-boundary-action-to-rep-connection-closure",
            "commit": "75894b95d32ddbb34689c6a6cd957569735ae2d6",
            "PR": None,
            "campaign_version": "historical boundary connection sprint",
            "equation": "A_f=O_q A_q+O_j A_j",
            "status_at_that_time": "A_q partial; A_j normalization convention-dependent; full action incomplete",
            "tests": [],
            "artifact": None,
            "classification": "PARTIAL_INGREDIENT",
            "reason": "gives sector connection incidence, not the multiplicative support representation",
        },
        {
            "historical_name": "normalized boundary/collar measure",
            "source_type": "merged geometry audits",
            "source_path": "theory/theorem_discharge_collar_measure_extrinsic_geometry.md",
            "branch": "main",
            "commit": "6dee862c3ac02205e2a7973579dadbb88cb8f1e7",
            "PR": 13,
            "campaign_version": "PO-BH-57",
            "equation": "J(Y,rho)=det(I+rho S)=1+rho K+O(rho^2)",
            "status_at_that_time": "conditional local collar formula; physical normalization/embedding data open",
            "tests": ["tests/test_collar_measure_extrinsic_geometry.py"],
            "artifact": None,
            "classification": "PARTIAL_INGREDIENT",
            "reason": "fixes a local Jacobian expansion, not a GD measure character",
        },
    ]
