"""BHSM v1.3H mirror-mode exclusion scaffold."""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from boundary_derivation import default_boundaries
from twisted_dirac import build_dirac_basis
from zero_mode_index import ZeroModeCandidate, protected_family_zero_modes


EXCLUDED_BY_BOUNDARY_CONDITION = "EXCLUDED_BY_BOUNDARY_CONDITION"
LIFTED_BY_CHIRAL_PROJECTOR = "LIFTED_BY_CHIRAL_PROJECTOR"
LIFTED_BY_HIGGS_U1_PHASE = "LIFTED_BY_HIGGS_U1_PHASE"
OPEN_MIRROR_RISK = "OPEN_MIRROR_RISK"
NOT_PRESENT_IN_BASIS = "NOT_PRESENT_IN_BASIS"


@dataclass(frozen=True)
class MirrorModeCandidate:
    """Opposite-chirality candidate paired with a protected zero mode."""

    id: str
    protected_partner_id: str
    sector: str
    k: int
    j: int
    q: int
    chirality: int
    present_in_finite_basis: bool
    boundary_residual: int
    classification: str
    assumptions: tuple[str, ...]
    limitations: tuple[str, ...]


@dataclass(frozen=True)
class MirrorExclusionCriterion:
    """A criterion that could exclude or lift mirror zero modes."""

    id: str
    statement: str
    status: str
    applies_to: tuple[str, ...]
    limitations: tuple[str, ...]


@dataclass(frozen=True)
class MirrorModeAuditReport:
    """Mirror-mode exclusion audit report."""

    title: str
    candidates: tuple[MirrorModeCandidate, ...]
    criteria: tuple[MirrorExclusionCriterion, ...]
    open_mirror_risk_count: int
    all_mirrors_excluded: bool
    mirror_exclusion_status: str
    theorem_complete: bool
    limitations: tuple[str, ...]


def _basis_keys(k_max: int = 4) -> set[tuple[str, int, int, int, int]]:
    return {
        (mode.sector, mode.k, mode.j, mode.q, mode.chirality)
        for mode in build_dirac_basis(k_max, include_chirality=True)
    }


def _boundary_residual(sector: str, k: int, j: int, q: int) -> int:
    boundary = default_boundaries()[sector]
    return int(boundary.fiber_weight * q + boundary.base_weight * j - boundary.target)


def generate_mirror_mode_candidates(k_max: int = 4) -> tuple[MirrorModeCandidate, ...]:
    """Generate opposite-chirality candidates for the protected zero modes."""

    basis_keys = _basis_keys(k_max)
    rows = []
    for protected in protected_family_zero_modes():
        mirror_chirality = -protected.chirality
        key = (protected.sector, protected.k, protected.j, protected.q, mirror_chirality)
        present = key in basis_keys
        residual = _boundary_residual(protected.sector, protected.k, protected.j, protected.q)
        if not present:
            classification = NOT_PRESENT_IN_BASIS
        else:
            classification = OPEN_MIRROR_RISK
        rows.append(
            MirrorModeCandidate(
                id=f"mirror_{protected.sector}",
                protected_partner_id=protected.id,
                sector=protected.sector,
                k=protected.k,
                j=protected.j,
                q=protected.q,
                chirality=mirror_chirality,
                present_in_finite_basis=present,
                boundary_residual=residual,
                classification=classification,
                assumptions=(
                    "Mirror mode is generated by flipping the protected zero-mode chirality.",
                    "No empirical flavor or residual data enter this classification.",
                ),
                limitations=(
                    "The current scaffold does not derive a full operator rule that removes this mirror candidate.",
                    "Boundary residual diagnostics alone are not treated as a proof of exclusion.",
                ),
            )
        )
    return tuple(rows)


def mirror_exclusion_criteria() -> tuple[MirrorExclusionCriterion, ...]:
    """Return explicit mirror-exclusion criteria and current statuses."""

    mirror_ids = tuple(candidate.id for candidate in generate_mirror_mode_candidates())
    return (
        MirrorExclusionCriterion(
            id="M1",
            statement="Boundary conditions exclude opposite-chirality zero modes.",
            status="OPEN",
            applies_to=mirror_ids,
            limitations=("The boundary functional is action-reduced, but mirror exclusion from the full spectrum is not proven.",),
        ),
        MirrorExclusionCriterion(
            id="M2",
            statement="Weak/chiral projector lifts opposite-chirality mirror candidates.",
            status="OPEN",
            applies_to=mirror_ids,
            limitations=("The finite scaffold inserts protected chirality; a complete projector proof remains open.",),
        ),
        MirrorExclusionCriterion(
            id="M3",
            statement="Higgs-selected U(1) phase lifts or forbids mirror candidates.",
            status="OPEN",
            applies_to=mirror_ids,
            limitations=("The U(1) boundary phase is action-linked, not a completed mirror-mode theorem.",),
        ),
        MirrorExclusionCriterion(
            id="M4",
            statement="Mirror candidates are not present in the finite Level 2 basis.",
            status="FALSE_FOR_BASELINE",
            applies_to=mirror_ids,
            limitations=("The baseline finite basis includes opposite-chirality coordinate labels.",),
        ),
    )


def build_mirror_mode_audit_report() -> MirrorModeAuditReport:
    """Return the v1.3H mirror-mode audit report."""

    candidates = generate_mirror_mode_candidates()
    open_count = sum(item.classification == OPEN_MIRROR_RISK for item in candidates)
    return MirrorModeAuditReport(
        title="BHSM v1.3H Mirror-Mode Exclusion Audit",
        candidates=candidates,
        criteria=mirror_exclusion_criteria(),
        open_mirror_risk_count=open_count,
        all_mirrors_excluded=bool(open_count == 0),
        mirror_exclusion_status="OPEN_MIRROR_RISK" if open_count else "MIRRORS_EXCLUDED_IN_SCAFFOLD",
        theorem_complete=False,
        limitations=(
            "Mirror-mode exclusion remains a proof obligation for the complete twisted Dirac operator.",
            "The current finite scaffold reports mirror risks rather than hiding them.",
            "No frozen BHSM predictions are changed.",
        ),
    )


def _jsonable(value: Any) -> Any:
    if isinstance(value, tuple):
        return [_jsonable(item) for item in value]
    if isinstance(value, list):
        return [_jsonable(item) for item in value]
    if isinstance(value, dict):
        return {str(key): _jsonable(item) for key, item in value.items()}
    if hasattr(value, "__dataclass_fields__"):
        return _jsonable(asdict(value))
    return value


def export_mirror_mode_audit_json(path: str | Path) -> None:
    """Export the mirror-mode audit report as JSON."""

    Path(path).write_text(json.dumps(_jsonable(build_mirror_mode_audit_report()), indent=2, sort_keys=True) + "\n")


def export_mirror_mode_audit_markdown(path: str | Path) -> None:
    """Export the mirror-mode audit report as Markdown."""

    report = build_mirror_mode_audit_report()
    lines = [
        "# BHSM v1.3H Mirror-Mode Exclusion Audit",
        "",
        f"Mirror exclusion status: `{report.mirror_exclusion_status}`",
        f"Theorem complete: `{report.theorem_complete}`",
        f"Open mirror risk count: `{report.open_mirror_risk_count}`",
        "",
        "## Mirror Candidates",
        "",
        "| ID | Partner | Sector | k | j | q | chirality | present | boundary residual | classification |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for item in report.candidates:
        lines.append(
            f"| `{item.id}` | `{item.protected_partner_id}` | `{item.sector}` | `{item.k}` | `{item.j}` | `{item.q}` | `{item.chirality}` | `{item.present_in_finite_basis}` | `{item.boundary_residual}` | `{item.classification}` |"
        )
    lines.extend(
        [
            "",
            "## Exclusion Criteria",
            "",
            "| ID | Status | Statement |",
            "| --- | --- | --- |",
        ]
    )
    for criterion in report.criteria:
        lines.append(f"| `{criterion.id}` | `{criterion.status}` | {criterion.statement} |")
    lines.extend(["", "## Limitations", "", *[f"- {item}" for item in report.limitations], ""])
    Path(path).write_text("\n".join(lines))
