"""BHSM v1.3B sector-coupling norm and relative-bound audit.

This module audits the Level 2 off-diagonal sector-coupling block. It compares
the full Level 2 Dirac-squared operator to the same scaffold with sector
couplings disabled, then applies finite-matrix norm, Weyl, and relative-bound
estimates on the protected complement. It does not change the BHSM frozen
prediction sets.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping

import numpy as np

from ht_operator import alpha_scaled_a, default_level2_config
from operator_norm_bounds import (
    GapStabilityResult,
    OperatorNormBound,
    RelativeBoundEstimate,
    gap_stability_from_norm,
    operator_norm_bounds,
    relative_bound_estimate,
)
from positivity import min_eigenvalue, restrict_to_complement
from spectral_bounds import required_dirac_lower_bound
from spectral_gap import MU_H, natural_lambda2
from twisted_dirac import (
    DIRAC_PROXY_LEVEL_2,
    DiracOperatorConfig,
    build_dirac_basis,
    build_level2_dirac_matrix,
    zero_mode_subspace,
)


SECTOR_BOUND_STATUSES = (
    "NORM_BOUND_SUFFICIENT",
    "NORM_BOUND_INSUFFICIENT_BUT_FINITE_BASIS_PASSES",
    "FAILS_GAP",
    "OPEN",
)


@dataclass(frozen=True)
class SectorCouplingBoundReport:
    """Auditable sector-coupling stability report for one Level 2 config."""

    model_level: str
    k_max: int
    a: float
    basis_size: int
    zero_mode_count: int
    sector_coupling: float
    offdiag_boundary_coupling: float
    required_dirac_lower_bound: float
    base_complement_lower_bound: float
    full_complement_lower_bound: float
    sector_perturbation_spectral_norm: float
    sector_perturbation_frobenius_norm: float
    sector_perturbation_row_sum_norm: float
    norm_bounds: tuple[OperatorNormBound, ...]
    relative_bound: RelativeBoundEstimate
    stability: GapStabilityResult
    theorem_complete: bool
    assumptions: tuple[str, ...]
    limitations: tuple[str, ...]


def config_without_sector_coupling(config: DiracOperatorConfig) -> DiracOperatorConfig:
    """Return a copy of ``config`` with sector-coupling terms disabled."""

    boundary_params = dict(config.boundary_params)
    boundary_params["sector_coupling"] = 0.0
    boundary_params["offdiag_boundary_coupling"] = 0.0
    return DiracOperatorConfig(
        a=config.a,
        k_max=config.k_max,
        sectors=config.sectors,
        twist_params=dict(config.twist_params),
        boundary_params=boundary_params,
        include_chirality=config.include_chirality,
        operator_level=config.operator_level,
    )


def level2_sector_coupling_dirac_block(config: DiracOperatorConfig) -> np.ndarray:
    """Return the off-diagonal Dirac-matrix block generated by sector coupling."""

    full = build_level2_dirac_matrix(config)
    base = build_level2_dirac_matrix(config_without_sector_coupling(config))
    return full - base


def level2_sector_coupling_squared_perturbation(config: DiracOperatorConfig) -> np.ndarray:
    """Return the D^dagger D perturbation induced by Level 2 sector coupling."""

    full = build_level2_dirac_matrix(config)
    base = build_level2_dirac_matrix(config_without_sector_coupling(config))
    return full.T @ full - base.T @ base


def _zero_modes_for_config(config: DiracOperatorConfig) -> np.ndarray:
    basis = build_dirac_basis(
        config.k_max,
        sectors=config.sectors,
        include_chirality=config.include_chirality,
    )
    zero_count = int(config.boundary_params.get("zero_mode_count", 3))
    return zero_mode_subspace(basis, index_count=zero_count)


def _restricted_operators(config: DiracOperatorConfig) -> dict[str, np.ndarray]:
    zero_modes = _zero_modes_for_config(config)
    full_dirac = build_level2_dirac_matrix(config)
    base_dirac = build_level2_dirac_matrix(config_without_sector_coupling(config))
    full_sq = full_dirac.T @ full_dirac
    base_sq = base_dirac.T @ base_dirac
    perturbation = full_sq - base_sq
    return {
        "zero_modes": zero_modes,
        "full_squared": full_sq,
        "base_squared": base_sq,
        "sector_squared_perturbation": perturbation,
        "restricted_full_squared": restrict_to_complement(full_sq, zero_modes),
        "restricted_base_squared": restrict_to_complement(base_sq, zero_modes),
        "restricted_sector_perturbation": restrict_to_complement(perturbation, zero_modes),
    }


def sector_coupling_bound_report(
    config: DiracOperatorConfig | None = None,
    lambda2: float | None = None,
    mu_h: float = MU_H,
) -> SectorCouplingBoundReport:
    """Return the Level 2 sector-coupling norm and gap-stability report."""

    resolved_config = default_level2_config() if config is None else config
    resolved_lambda2 = natural_lambda2() if lambda2 is None else float(lambda2)
    required = required_dirac_lower_bound(resolved_lambda2, mu_h)
    operators = _restricted_operators(resolved_config)
    restricted_base = operators["restricted_base_squared"]
    restricted_full = operators["restricted_full_squared"]
    restricted_k = operators["restricted_sector_perturbation"]
    base_lower = min_eigenvalue(restricted_base)
    full_lower = min_eigenvalue(restricted_full)
    bounds = operator_norm_bounds(restricted_k)
    by_name = {bound.name: bound for bound in bounds}
    spectral = by_name["spectral_norm"].value
    relative = relative_bound_estimate(spectral, base_lower, required)
    stability = gap_stability_from_norm(base_lower, spectral, full_lower, required)
    basis_size = len(
        build_dirac_basis(
            resolved_config.k_max,
            sectors=resolved_config.sectors,
            include_chirality=resolved_config.include_chirality,
        )
    )
    return SectorCouplingBoundReport(
        model_level=DIRAC_PROXY_LEVEL_2,
        k_max=int(resolved_config.k_max),
        a=float(resolved_config.a),
        basis_size=basis_size,
        zero_mode_count=int(np.asarray(operators["zero_modes"]).shape[1]),
        sector_coupling=float(resolved_config.boundary_params.get("sector_coupling", 0.0)),
        offdiag_boundary_coupling=float(resolved_config.boundary_params.get("offdiag_boundary_coupling", 0.0)),
        required_dirac_lower_bound=float(required),
        base_complement_lower_bound=float(base_lower),
        full_complement_lower_bound=float(full_lower),
        sector_perturbation_spectral_norm=float(spectral),
        sector_perturbation_frobenius_norm=float(by_name["frobenius_norm"].value),
        sector_perturbation_row_sum_norm=float(by_name["row_sum_norm"].value),
        norm_bounds=bounds,
        relative_bound=relative,
        stability=stability,
        theorem_complete=False,
        assumptions=(
            "Sector coupling is isolated by comparing the full Level 2 matrix to the same config with sector couplings set to zero.",
            "Bounds are evaluated on the finite protected complement.",
            f"Natural cutoff Lambda^2 = {natural_lambda2()} is used when lambda2 is omitted.",
        ),
        limitations=(
            "This is a finite-matrix operator-norm and relative-bound audit.",
            "A finite-basis pass is not a proof of the full H_T theorem.",
            "The zero-mode/complement decomposition remains finite-basis in this audit.",
        ),
    )


def _perturbed_config(config: DiracOperatorConfig, perturbation: Mapping[str, float]) -> DiracOperatorConfig:
    boundary = dict(config.boundary_params)
    boundary.update({key: float(value) for key, value in perturbation.items()})
    return DiracOperatorConfig(
        a=config.a,
        k_max=config.k_max,
        sectors=config.sectors,
        twist_params=dict(config.twist_params),
        boundary_params=boundary,
        include_chirality=config.include_chirality,
        operator_level=config.operator_level,
    )


def default_sector_coupling_perturbations() -> tuple[dict[str, float], ...]:
    """Return baseline and nearby sector-coupling perturbations."""

    return (
        {},
        {"sector_coupling": 0.005},
        {"sector_coupling": 0.02},
        {"offdiag_boundary_coupling": 0.01},
    )


def scan_sector_coupling_bounds(
    k_max_values: Iterable[int],
    a_values: Iterable[float],
    perturbations: Iterable[Mapping[str, float]] | None = None,
    lambda2: float | None = None,
) -> list[dict[str, object]]:
    """Scan sector-coupling norm sufficiency across basis and coupling choices."""

    rows: list[dict[str, object]] = []
    for k_max in k_max_values:
        for a in a_values:
            base = default_level2_config(k_max=int(k_max), a=float(a))
            for perturbation in tuple(perturbations or default_sector_coupling_perturbations()):
                config = _perturbed_config(base, perturbation)
                report = sector_coupling_bound_report(config, lambda2=lambda2)
                rows.append(
                    {
                        "k_max": report.k_max,
                        "a": report.a,
                        "basis_size": report.basis_size,
                        "zero_mode_count": report.zero_mode_count,
                        "sector_coupling": report.sector_coupling,
                        "offdiag_boundary_coupling": report.offdiag_boundary_coupling,
                        "required_dirac_lower_bound": report.required_dirac_lower_bound,
                        "base_complement_lower_bound": report.base_complement_lower_bound,
                        "full_complement_lower_bound": report.full_complement_lower_bound,
                        "spectral_norm": report.sector_perturbation_spectral_norm,
                        "frobenius_norm": report.sector_perturbation_frobenius_norm,
                        "row_sum_norm": report.sector_perturbation_row_sum_norm,
                        "weyl_lower_bound": report.stability.weyl_lower_bound,
                        "norm_bound_sufficient": report.stability.norm_bound_sufficient,
                        "finite_basis_passes": report.stability.finite_basis_passes,
                        "classification": report.stability.classification,
                        "theorem_complete": False,
                    }
                )
    return rows


def default_sector_coupling_scan() -> list[dict[str, object]]:
    """Return the required v1.3B robustness scan."""

    return scan_sector_coupling_bounds(
        k_max_values=(4, 6, 8, 10, 12, 16),
        a_values=(0.573, 1.0, alpha_scaled_a()),
        perturbations=default_sector_coupling_perturbations(),
        lambda2=natural_lambda2(),
    )


def _jsonable(value: Any) -> Any:
    if isinstance(value, tuple):
        return [_jsonable(item) for item in value]
    if isinstance(value, list):
        return [_jsonable(item) for item in value]
    if isinstance(value, dict):
        return {str(key): _jsonable(item) for key, item in value.items()}
    if hasattr(value, "__dataclass_fields__"):
        return _jsonable(asdict(value))
    return value


def sector_coupling_audit_payload() -> dict[str, object]:
    """Return the default report plus robustness scan for exports."""

    baseline = sector_coupling_bound_report(default_level2_config(), lambda2=natural_lambda2())
    scan = default_sector_coupling_scan()
    classifications = {row["classification"] for row in scan}
    return {
        "title": "BHSM v1.3B Sector-Coupling Operator-Norm Audit",
        "baseline": baseline,
        "scan": scan,
        "scan_case_count": len(scan),
        "classifications_seen": sorted(classifications),
        "all_finite_basis_cases_pass": all(bool(row["finite_basis_passes"]) for row in scan),
        "all_norm_bounds_sufficient": all(bool(row["norm_bound_sufficient"]) for row in scan),
        "worst_weyl_lower_bound": min(float(row["weyl_lower_bound"]) for row in scan),
        "worst_full_complement_lower_bound": min(float(row["full_complement_lower_bound"]) for row in scan),
        "theorem_complete": False,
        "correct_claim": (
            "BHSM v1.3B bounds the Level 2 sector-coupling block by operator-norm "
            "and relative-bound estimates. It does not prove the full H_T no-extra-light-state theorem."
        ),
        "limitations": (
            "Operator norms are finite-matrix estimates on the Level 2 complement.",
            "The full analytic H_T spectrum and the full zero-mode complement proof remain open.",
        ),
    }


def export_sector_coupling_bound_report_json(path: str | Path) -> None:
    """Export the sector-coupling audit payload as JSON."""

    Path(path).write_text(json.dumps(_jsonable(sector_coupling_audit_payload()), indent=2, sort_keys=True) + "\n")


def export_sector_coupling_bound_report_markdown(path: str | Path) -> None:
    """Export the sector-coupling audit payload as Markdown."""

    payload = sector_coupling_audit_payload()
    baseline: SectorCouplingBoundReport = payload["baseline"]  # type: ignore[assignment]
    lines = [
        "# BHSM v1.3B Sector-Coupling Operator-Norm Audit",
        "",
        f"Theorem complete: `{payload['theorem_complete']}`",
        f"Baseline classification: `{baseline.stability.classification}`",
        "",
        payload["correct_claim"],  # type: ignore[index]
        "",
        "## Baseline Norm Table",
        "",
        "| Norm | Value | Method |",
        "| --- | --- | --- |",
    ]
    for bound in baseline.norm_bounds:
        lines.append(f"| `{bound.name}` | `{bound.value}` | {bound.method} |")
    lines.extend(
        [
            "",
            "## Baseline Weyl / Relative-Bound Table",
            "",
            "| Quantity | Value |",
            "| --- | --- |",
            f"| Required Dirac lower bound | `{baseline.required_dirac_lower_bound}` |",
            f"| Base complement lower bound before sector coupling | `{baseline.base_complement_lower_bound}` |",
            f"| Full complement lower bound with sector coupling | `{baseline.full_complement_lower_bound}` |",
            f"| Weyl lower bound after sector coupling | `{baseline.stability.weyl_lower_bound}` |",
            f"| Relative bound a_K | `{baseline.relative_bound.a_k}` |",
            f"| Norm bound sufficient | `{baseline.stability.norm_bound_sufficient}` |",
            f"| Finite-basis gap passes | `{baseline.stability.finite_basis_passes}` |",
            "",
            "## Robustness Scan Summary",
            "",
            f"- Cases: `{payload['scan_case_count']}`",
            f"- All finite-basis cases pass: `{payload['all_finite_basis_cases_pass']}`",
            f"- All norm bounds sufficient: `{payload['all_norm_bounds_sufficient']}`",
            f"- Worst Weyl lower bound: `{payload['worst_weyl_lower_bound']}`",
            f"- Worst full complement lower bound: `{payload['worst_full_complement_lower_bound']}`",
            "",
            "| k_max | a | sector coupling | offdiag boundary | spectral norm | Weyl lower | full lower | classification |",
            "| --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for row in payload["scan"]:  # type: ignore[index]
        lines.append(
            "| `{k_max}` | `{a}` | `{sector_coupling}` | `{offdiag_boundary_coupling}` | `{spectral_norm}` | `{weyl_lower_bound}` | `{full_complement_lower_bound}` | `{classification}` |".format(
                **row
            )
        )
    lines.extend(
        [
            "",
            "## Limitations",
            "",
            *[f"- {item}" for item in payload["limitations"]],  # type: ignore[index]
            "",
        ]
    )
    Path(path).write_text("\n".join(lines))
