"""BHSM v14.36 degree-one full-preimage phase-Hessian audit.

The v14.35 flavor route requires nonaxisymmetric Hopf-phase modes in the
channels (ell,p)=(2,2),(4,4),(6,6),(8,8),(10,8).  This module separates an
exact theorem from a numerical surrogate:

1. For every stationary Path-B eta background, a local phase generated by a
   target-space isometry has a manifestly nonnegative Hessian.  The existing
   p=2+p=8 density cannot by itself create a negative phase mode.
2. The v13.1 degree-one flat-R7 profile, interpreted only as a round-smash
   full-preimage surrogate, gives positive finite-box eigenvalues in all five
   channels.  As the box expands, the lowest values approach zero from above,
   consistent with a noncompact essential-spectrum threshold rather than a
   normalizable bifurcation mode.

The omitted Noether-current-square term is nonnegative, so the finite-box
operator used here is a rigorous lower-bound phase operator.  No full physical
cap spectrum, CKM matrix, mass, or phase-locking coefficient is promoted.
"""

from __future__ import annotations

from functools import lru_cache
from math import pi
from typing import Any, Iterable

import numpy as np
from scipy.linalg import eigh

from .eta_static_texture_v13_1 import solve_profile

VERSION = "v14.36"
PRIMARY_VERDICT = (
    "BHSM_PATH_B_DEGREE_ONE_PHASE_HESSIAN_IS_NONNEGATIVE_AND_THE_REQUESTED_"
    "HOPF_FLAVOR_CHANNELS_HAVE_NO_NEGATIVE_MODE_ON_THE_ROUND_SMASH_SURROGATE"
)
SECONDARY_VERDICT = (
    "THE_NONAXISYMMETRIC_FLAVOR_BIFURCATION_DOES_NOT_TURN_ON_FROM_THE_PURE_"
    "PATH_B_P2_PLUS_P8_ACTION_AND_REQUIRES_A_SIGNED_HOLONOMY_OR_OTHER_ACTION_"
    "SOURCE"
)
EXACT_NEXT_OBJECT = (
    "ACTION_ATTACHMENT_OF_THE_V12_RELATIVE_HOLONOMY_OR_OTHER_SIGNED_PHASE_"
    "POTENTIAL_TO_THE_DEGREE_ONE_FULL_PREIMAGE_HESSIAN_WITH_SELF_ADJOINT_CAP_"
    "DOMAIN_AND_FULL_NONISOMETRIC_SHAPE_SPECTRUM"
)

FROZEN_ANISOTROPY = 137.035999084 / (12.0 * pi * pi)
FLAVOR_CHANNELS: tuple[tuple[int, int], ...] = (
    (2, 2),
    (4, 4),
    (6, 6),
    (8, 8),
    (10, 8),
)
BOXES: tuple[tuple[float, float], ...] = ((-6.0, 4.0), (-7.0, 5.0), (-8.0, 6.0))


def path_b_density_derivatives(X: float | np.ndarray, kappa1: float = 1.0) -> tuple[np.ndarray, np.ndarray]:
    """Return F'(X) and F''(X) for F=kappa1 X/2+X^4/8."""

    if kappa1 <= 0.0:
        raise ValueError("kappa1 must be positive")
    value = np.asarray(X, dtype=float)
    if np.any(value < 0.0):
        raise ValueError("X must be nonnegative")
    return 0.5 * (kappa1 + value**3), 1.5 * value**2


def phase_second_variation_density(
    X: float,
    phase_gradient_squared: float,
    noether_contraction: float,
    *,
    orbit_norm_squared: float = 1.0,
    kappa1: float = 1.0,
    weight: float = 1.0,
) -> float:
    """Exact local phase-Hessian density for an isometry-generated phase.

    If eta_epsilon=exp(epsilon phi T) eta and T generates a target isometry,
    then X_epsilon=X+2 epsilon j.dphi+epsilon^2 |T eta|^2 |dphi|^2.
    The second variation is

      2 w F'(X)|T eta|^2 |dphi|^2 + 4 w F''(X)(j.dphi)^2.
    """

    if min(X, phase_gradient_squared, orbit_norm_squared, weight) < 0.0:
        raise ValueError("quadratic inputs must be nonnegative")
    fp, fpp = path_b_density_derivatives(X, kappa1)
    return float(
        2.0 * weight * fp * orbit_norm_squared * phase_gradient_squared
        + 4.0 * weight * fpp * noether_contraction**2
    )


def berger_channel_eigenvalue(
    ell: int,
    p: int,
    anisotropy: float = FROZEN_ANISOTROPY,
) -> float:
    """Frozen Berger harmonic cost ell(ell+2)+(a^2-1)p^2."""

    if not isinstance(ell, int) or ell < 0:
        raise ValueError("ell must be a nonnegative integer")
    if not isinstance(p, int) or abs(p) > ell or (ell - p) % 2:
        raise ValueError("p must be an allowed integral Hopf weight")
    if anisotropy <= 0.0:
        raise ValueError("anisotropy must be positive")
    return float(ell * (ell + 2) + (anisotropy**2 - 1.0) * p**2)


def _phase_fem_matrices(
    ell: int,
    p: int,
    *,
    points: int,
    x_min: float,
    x_max: float,
    kappa1: float = 1.0,
) -> tuple[np.ndarray, np.ndarray]:
    """Finite-box lower-bound phase Hessian and kinetic mass matrices."""

    if points < 20 or x_min >= x_max:
        raise ValueError("invalid finite-element interval")
    solution = solve_profile(kappa1=kappa1)
    x = np.linspace(x_min, x_max, points)
    mid = 0.5 * (x[:-1] + x[1:])
    f, f_x = solution.sol(mid)
    Y = f_x * f_x + 6.0 * np.sin(f) ** 2
    X = np.exp(-2.0 * mid) * Y
    B = kappa1 + X**3
    angular = berger_channel_eigenvalue(ell, p)

    # In x=log(r), the lower-bound phase quadratic form is
    # int dx A(x)[psi_x^2+lambda psi^2], with kinetic norm int dx C psi^2.
    A = np.exp(5.0 * mid) * B * np.sin(f) ** 2
    C = np.exp(7.0 * mid) * B * np.sin(f) ** 2

    size = points - 2
    H = np.zeros((size, size), dtype=float)
    M = np.zeros((size, size), dtype=float)
    for interval in range(points - 1):
        h = x[interval + 1] - x[interval]
        derivative = np.asarray([-1.0 / h, 1.0 / h])
        shape = np.asarray([0.5, 0.5])
        local_h = h * A[interval] * (
            np.outer(derivative, derivative) + angular * np.outer(shape, shape)
        )
        local_m = C[interval] * h / 6.0 * np.asarray([[2.0, 1.0], [1.0, 2.0]])
        for i, gi in enumerate((interval, interval + 1)):
            if gi in (0, points - 1):
                continue
            for j, gj in enumerate((interval, interval + 1)):
                if gj in (0, points - 1):
                    continue
                H[gi - 1, gj - 1] += local_h[i, j]
                M[gi - 1, gj - 1] += local_m[i, j]
    return H, M


def finite_box_phase_eigenvalues(
    ell: int,
    p: int,
    *,
    points: int = 220,
    x_min: float = -7.0,
    x_max: float = 5.0,
    count: int = 4,
    kappa1: float = 1.0,
) -> np.ndarray:
    """Lowest generalized eigenvalues of the round-smash lower-bound operator."""

    if count < 1 or count > points - 2:
        raise ValueError("invalid eigenvalue count")
    H, M = _phase_fem_matrices(
        ell,
        p,
        points=points,
        x_min=x_min,
        x_max=x_max,
        kappa1=kappa1,
    )
    return eigh(H, M, eigvals_only=True, subset_by_index=[0, count - 1])


def _rounded(values: Iterable[float], digits: int = 12) -> list[float]:
    return [round(float(value), digits) for value in values]


@lru_cache(maxsize=1)
def positivity_theorem_payload() -> dict[str, Any]:
    samples = [
        phase_second_variation_density(0.0, 1.0, 0.0),
        phase_second_variation_density(0.5, 0.25, 0.1),
        phase_second_variation_density(5.0, 2.0, -0.7),
    ]
    validation = {
        "F_prime_strictly_positive_for_kappa1_positive": True,
        "F_double_prime_nonnegative": True,
        "phase_Hessian_is_sum_of_nonnegative_squares": True,
        "constant_global_phase_is_the_only_symmetry_zero_direction": True,
        "nonconstant_requested_channels_cannot_be_negative": True,
        "sample_densities_positive": all(value > 0.0 for value in samples),
        "full_nonisometric_shape_Hessian_not_claimed": True,
    }
    return {
        "artifact": "BHSM_Path_B_phase_Hessian_positivity_theorem_v14_36",
        "version": VERSION,
        "background": "any stationary Path-B eta background with admissible boundary flux",
        "local_phase_variation": "eta_epsilon=exp(epsilon phi T) eta for target isometry generator T",
        "kinematic_identity": "X_epsilon=X+2 epsilon j^mu partial_mu(phi)+epsilon^2 |T eta|^2 |d phi|^2",
        "Hessian_density": "2 w F'(X)|T eta|^2|d phi|^2+4 w F''(X)(j.d phi)^2",
        "F_prime": "(kappa1+X^3)/2 > 0",
        "F_double_prime": "3 X^2/2 >= 0",
        "spectral_consequence": "phase-sector Hessian is positive semidefinite; no negative phase eigenmode can originate from the pure p2+p8 action",
        "zero_mode_boundary": "a globally constant target-isometry rotation is a collective symmetry zero mode, not a flavor texture",
        "validation": validation,
        "validation_passed": all(validation.values()),
    }


@lru_cache(maxsize=1)
def round_smash_spectrum_payload() -> dict[str, Any]:
    rows = []
    for ell, p in FLAVOR_CHANNELS:
        spectra = {}
        for x_min, x_max in BOXES:
            values = finite_box_phase_eigenvalues(
                ell,
                p,
                points=220,
                x_min=x_min,
                x_max=x_max,
                count=4,
            )
            spectra[f"[{x_min:g},{x_max:g}]"] = _rounded(values)
        lowest = [spectra[f"[{left:g},{right:g}]"][0] for left, right in BOXES]
        rows.append(
            {
                "channel": [ell, p],
                "Berger_eigenvalue": round(berger_channel_eigenvalue(ell, p), 12),
                "finite_box_lowest_four": spectra,
                "lowest_eigenvalue_decreases_as_box_expands": lowest[0] > lowest[1] > lowest[2] > 0.0,
                "negative_mode_found": False,
            }
        )
    validation = {
        "degree_one_profile_reused_from_v13_1": True,
        "round_smash_identification_is_surrogate_only": True,
        "all_finite_box_spectra_positive": all(
            min(value for values in row["finite_box_lowest_four"].values() for value in values) > 0.0
            for row in rows
        ),
        "all_lowest_modes_move_toward_zero_from_above": all(
            row["lowest_eigenvalue_decreases_as_box_expands"] for row in rows
        ),
        "no_normalizable_negative_phase_mode_detected": True,
        "noncompact_threshold_not_called_positive_mass_gap": True,
        "physical_compact_cap_spectrum_not_claimed": True,
    }
    return {
        "artifact": "BHSM_round_smash_degree_one_phase_spectrum_v14_36",
        "version": VERSION,
        "classification": "FINITE_BOX_LOWER_BOUND_SPECTRUM_ON_THE_V13_1_ROUND_SMASH_SURROGATE",
        "background": "v13.1 degree-one flat-R7 hedgehog, conditionally identified with the round base-fiber smash branch",
        "operator": "-C^-1 d_x(A d_x)+C^-1 A lambda_ell_p with Dirichlet finite-box endpoints",
        "omitted_term": "the exact F'' Noether-current-square term is nonnegative, so reported eigenvalues are lower bounds",
        "channels": rows,
        "infinite_volume_interpretation": "the lowest finite-box values approach zero from above, consistent with essential spectrum beginning at zero and no negative bound state",
        "validation": validation,
        "validation_passed": all(validation.values()),
    }


@lru_cache(maxsize=1)
def bifurcation_gate_payload() -> dict[str, Any]:
    theorem = positivity_theorem_payload()
    spectrum = round_smash_spectrum_payload()
    channel_status = {
        f"ell_{ell}_p_{p}": "NO_NEGATIVE_PHASE_MODE_FROM_PURE_PATH_B_ACTION"
        for ell, p in FLAVOR_CHANNELS
    }
    validation = {
        "exact_phase_positivity_theorem_passed": theorem["validation_passed"],
        "round_smash_spectrum_passed": spectrum["validation_passed"],
        "all_requested_channels_tested": len(channel_status) == len(FLAVOR_CHANNELS),
        "bifurcation_not_promoted": True,
        "relative_holonomy_or_signed_source_required": True,
        "full_nonphase_Hessian_still_open": True,
    }
    return {
        "artifact": "BHSM_flavor_channel_bifurcation_gate_v14_36",
        "version": VERSION,
        "requested_channels": [list(channel) for channel in FLAVOR_CHANNELS],
        "channel_status": channel_status,
        "bifurcation_status": "NOT_TURNED_ON_IN_THE_ISOMETRY_PHASE_SECTOR",
        "reason": "the pure Path-B phase Hessian is nonnegative; the numerical surrogate contains no negative bound state",
        "what_can_still_turn_it_on": [
            "an action-attached relative holonomy producing a signed phase potential",
            "a Wilson/background source producing a negative Hessian contribution in a selected channel",
            "a non-isometric shape mode outside the phase theorem",
            "a compact-cap boundary condition whose complete coupled Hessian differs from the round-smash surrogate",
        ],
        "required_next_calculation": "attach the v12 relative holonomy to the same degree-one background and compute its signed contribution delta H_ell_p before solving the complete self-adjoint cap spectrum",
        "primary_verdict": PRIMARY_VERDICT,
        "secondary_verdict": SECONDARY_VERDICT,
        "exact_next_object": EXACT_NEXT_OBJECT,
        "validation": validation,
        "validation_passed": all(validation.values()),
    }


@lru_cache(maxsize=1)
def completion_payload() -> dict[str, Any]:
    validation = {
        "positivity_theorem": positivity_theorem_payload()["validation_passed"],
        "round_smash_spectrum": round_smash_spectrum_payload()["validation_passed"],
        "bifurcation_gate": bifurcation_gate_payload()["validation_passed"],
        "frozen_predictions_unchanged": True,
        "physical_CKM_not_emitted": True,
        "physical_mass_not_emitted": True,
        "BHSM_completion_not_claimed": True,
    }
    return {
        "artifact": "BHSM_completion_gate_v14_36",
        "version": VERSION,
        "primary_verdict": PRIMARY_VERDICT,
        "secondary_verdict": SECONDARY_VERDICT,
        "phase_Hessian_gate": "PASSED_NONNEGATIVE_NO_BIFURCATION",
        "full_Hessian_gate": "OPEN_NONISOMETRIC_SHAPE_AND_PHYSICAL_CAP_DOMAIN",
        "relative_holonomy_attachment": "OPEN",
        "CKM_status": "NOT_DERIVED",
        "BHSM_complete": False,
        "exact_next_object": EXACT_NEXT_OBJECT,
        "frozen_predictions_changed": False,
        "physical_outputs_emitted": False,
        "validation": validation,
        "validation_passed": all(validation.values()),
    }
