"""BHSM v14.66 operator-valued Calderon/Wentzell theorem gate.

This sprint upgrades the scalar v14.65 envelopment diamond to a finite retained
common-boundary-mode theorem class.  Each incidence edge carries

    P_e = -D_x^2 + K_e^2,

where K_e is a positive Hermitian tangential operator on a retained common
S^3 mode block and U_e is its unitary endpoint parallel transport.  The exact
operator-valued edge Weyl function is obtained by Hermitian functional
calculus.  A Hermitian Wentzell term is generated by a KKT Schur complement
and inserted into vector-valued continuity/flux boundary conditions.

The package proves, in this retained theorem class:
* exact self-adjoint vector-valued Wentzell boundary conditions;
* exact Hermitian positive operator-valued edge and global Weyl functions;
* non-Abelian Wilson-loop eigenphases are vertex-gauge invariant;
* the scalar-circle isospectral collapse is lifted at the operator-valued
  boundary-response level when distinct tangential blocks are present;
* a gauge/constraint quotient and finite response heat/logdet pipeline can be
  executed without post-comparison tuning.

It deliberately does NOT claim that the diagnostic tangential blocks are the
complete physical M8/M5/M4 operators.  The exact Berger homogeneous block is
used only as an action-compatible geometric retained-mode witness.  The
physical KKT Gram-Hessian, complete Calderon projectors, ghosts, global
stationary background, and full relative continuum heat supertrace remain
open.  No physical particle prediction is emitted.
"""
from __future__ import annotations

from pathlib import Path
import hashlib
import json
import math
from typing import Any, Mapping, Sequence

import numpy as np

VERSION = "v14.66"

PRIMARY_VERDICT = (
    "BHSM_V14_66_THE_SCALAR_DIAMOND_COLLAPSE_IS_LIFTED_IN_AN_EXACT_OPERATOR_"
    "VALUED_RETAINED_MODE_THEOREM_CLASS_WHERE_POSITIVE_HERMITIAN_TANGENTIAL_"
    "BERGER_DIRAC_LAPLACE_BLOCKS_ENTER_THE_EDGE_CALDERON_WEYL_FUNCTION_AND_"
    "A_HERMITIAN_KKT_SCHUR_COMPLEMENT_ENTERS_AS_A_SELF_ADJOINT_WENTZELL_"
    "BOUNDARY_TERM_BUT_THE_ARCHIVE_STILL_LACKS_THE_PHYSICAL_ACTION_NORMALIZED_"
    "M8_M5_M4_RESPONSE_GRAM_HESSIAN_AND_COMPLETE_CONTINUUM_PROJECTORS"
)

HOLONOMY_VERDICT = (
    "BHSM_V14_66_OPERATOR_VALUED_PARALLEL_TRANSPORT_PROMOTES_THE_SINGLE_"
    "ABELIAN_DIAMOND_PHASE_TO_A_NONABELIAN_WILSON_LOOP_WHOSE_EIGENPHASES_"
    "ARE_VERTEX_GAUGE_INVARIANT_AND_CAN_SUPPLY_MULTIPLE_RELATIVE_PHASES_"
    "WITHOUT_INSERTING_A_FLAVOR_MATRIX_BUT_THE_PHYSICAL_CONNECTION_REMAINS_"
    "TO_BE_DERIVED_FROM_THE_GLOBAL_STATIONARY_ACTION"
)

WENTZELL_VERDICT = (
    "BHSM_V14_66_A_HERMITIAN_WENTZELL_OPERATOR_OBTAINED_AS_THE_KKT_SCHUR_"
    "COMPLEMENT_HBB_MINUS_HBI_HII_INVERSE_HIB_GIVES_AN_EXACT_SELF_ADJOINT_"
    "VECTOR_VALUED_CONTINUITY_PLUS_DYNAMIC_FLUX_DOMAIN_IN_THE_RETAINED_MODE_"
    "CLASS_WHILE_THE_PHYSICAL_CORE_WALL_GRAM_HESSIAN_IS_STILL_UNEVALUATED"
)

EXACT_NEXT_OBJECT = (
    "ACTION_NORMALIZED_PHYSICAL_COMMON_ATTACHMENT_RESPONSE_GRAM_HESSIAN_AND_"
    "ACTUAL_M8_M5_PLUS_MINUS_M4_TANGENTIAL_CALDERON_BLOCKS_ON_THE_GLOBAL_"
    "STATIONARY_ENVELOPMENT_BACKGROUND_WITH_COMPLETE_GAUGE_GHOST_ZERO_MODE_"
    "PROJECTORS_THEN_CONTINUUM_RELATIVE_HEAT_SUPERTRACE_AND_FROZEN_NO_"
    "RETUNING_NEUTRINO_KILL_SCREEN"
)

VERTICES = ("M8", "M5_plus", "M5_minus", "M4")
VERTEX_INDEX = {v: i for i, v in enumerate(VERTICES)}
EDGES = (
    ("M8", "M5_plus", "e_8p"),
    ("M5_plus", "M4", "e_p4"),
    ("M5_minus", "M4", "e_m4"),
    ("M8", "M5_minus", "e_8m"),
)
EDGE_NAMES = tuple(e[2] for e in EDGES)
FROZEN_BERGER_DIAGNOSTIC = 1.157054135733433


def canonical_json_bytes(payload: Any) -> bytes:
    return json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
        allow_nan=False,
    ).encode("utf-8")


def sha256_payload(payload: Any) -> str:
    return hashlib.sha256(canonical_json_bytes(payload)).hexdigest()


def _finite_positive(x: float, name: str) -> float:
    y = float(x)
    if not math.isfinite(y) or y <= 0.0:
        raise ValueError(f"{name} must be positive and finite")
    return y


def _as_hermitian(a: np.ndarray, name: str = "matrix", tol: float = 1e-11) -> np.ndarray:
    x = np.asarray(a, dtype=complex)
    if x.ndim != 2 or x.shape[0] != x.shape[1]:
        raise ValueError(f"{name} must be square")
    if np.linalg.norm(x - np.conjugate(x.T)) > tol:
        raise ValueError(f"{name} must be Hermitian")
    return 0.5 * (x + np.conjugate(x.T))


def _as_unitary(u: np.ndarray, name: str = "unitary", tol: float = 1e-11) -> np.ndarray:
    x = np.asarray(u, dtype=complex)
    if x.ndim != 2 or x.shape[0] != x.shape[1]:
        raise ValueError(f"{name} must be square")
    ident = np.eye(x.shape[0], dtype=complex)
    if np.linalg.norm(np.conjugate(x.T) @ x - ident) > tol:
        raise ValueError(f"{name} must be unitary")
    return x


def hermitian_function(a: np.ndarray, fn) -> np.ndarray:
    h = _as_hermitian(a)
    w, v = np.linalg.eigh(h)
    fw = np.asarray([fn(float(x)) for x in w], dtype=float)
    if not np.all(np.isfinite(fw)):
        raise ValueError("matrix function returned nonfinite values")
    return (v * fw) @ np.conjugate(v.T)


def positive_sqrt(a: np.ndarray, tol: float = 1e-12) -> np.ndarray:
    h = _as_hermitian(a)
    w = np.linalg.eigvalsh(h)
    if float(np.min(w)) < -tol:
        raise ValueError("matrix is not positive semidefinite")
    return hermitian_function(h, lambda x: math.sqrt(max(0.0, x)))


def spin_j_matrices(n: int) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Spin j=n/2 generators in the descending-m basis."""
    nn = int(n)
    if nn < 0:
        raise ValueError("n must be nonnegative")
    j = 0.5 * nn
    d = nn + 1
    ms = np.asarray([j - k for k in range(d)], dtype=float)
    jz = np.diag(ms).astype(complex)
    jp = np.zeros((d, d), dtype=complex)
    for col, m in enumerate(ms):
        mp = m + 1.0
        if mp <= j + 1e-14:
            rows = np.where(np.isclose(ms, mp))[0]
            if len(rows):
                jp[int(rows[0]), col] = math.sqrt(max(0.0, j * (j + 1.0) - m * (m + 1.0)))
    jm = np.conjugate(jp.T)
    jx = 0.5 * (jp + jm)
    jy = (jp - jm) / (2.0j)
    return jx, jy, jz


def berger_dirac_block(n: int, beta: float, radius: float = 1.0) -> np.ndarray:
    """Exact homogeneous Berger Dirac block used by the v14.59 geometry gate.

    Metric convention: h_beta = R^2(sigma_1^2+sigma_2^2+beta^2 sigma_3^2).
    The block is
      D_n = C I + 2 a sigma_z⊗J_z + 2 b sigma_y⊗J_y + 2 c sigma_x⊗J_x,
    with a=b=1/R, c=1/(beta R),
      C=1/2(ab/c+bc/a+ca/b).
    """
    bta = _finite_positive(beta, "beta")
    r = _finite_positive(radius, "radius")
    sx = np.array([[0.0, 1.0], [1.0, 0.0]], dtype=complex)
    sy = np.array([[0.0, -1.0j], [1.0j, 0.0]], dtype=complex)
    sz = np.array([[1.0, 0.0], [0.0, -1.0]], dtype=complex)
    jx, jy, jz = spin_j_matrices(int(n))
    a = 1.0 / r
    b = 1.0 / r
    c = 1.0 / (bta * r)
    C = 0.5 * (a * b / c + b * c / a + c * a / b)
    dim = 2 * (int(n) + 1)
    out = (
        C * np.eye(dim, dtype=complex)
        + 2.0 * a * np.kron(sz, jz)
        + 2.0 * b * np.kron(sy, jy)
        + 2.0 * c * np.kron(sx, jx)
    )
    return _as_hermitian(out, "Berger Dirac block")


def berger_n1_expected_eigenvalues(beta: float, radius: float = 1.0) -> np.ndarray:
    b = _finite_positive(beta, "beta")
    r = _finite_positive(radius, "radius")
    vals = [
        (b - 4.0) / (2.0 * r),
        (b * b + 4.0) / (2.0 * b * r),
        (b * b + 4.0) / (2.0 * b * r),
        (b + 4.0) / (2.0 * r),
    ]
    return np.asarray(sorted(vals), dtype=float)


def berger_positive_tangential(n: int, beta: float, radius: float, regulator_mass: float) -> np.ndarray:
    mu = _finite_positive(regulator_mass, "regulator_mass")
    d = berger_dirac_block(n, beta, radius)
    return positive_sqrt(d @ d + mu * mu * np.eye(d.shape[0], dtype=complex))


def plane_unitary(dim: int, i: int, j: int, theta: float, phase: float = 0.0) -> np.ndarray:
    d = int(dim)
    if d < 2 or not (0 <= i < d and 0 <= j < d) or i == j:
        raise ValueError("invalid plane rotation indices")
    th = float(theta)
    ph = float(phase)
    if not (math.isfinite(th) and math.isfinite(ph)):
        raise ValueError("rotation data must be finite")
    c, s = math.cos(th), math.sin(th)
    u = np.eye(d, dtype=complex)
    u[i, i] = c
    u[j, j] = c
    u[i, j] = -s * np.exp(-1j * ph)
    u[j, i] = s * np.exp(1j * ph)
    return _as_unitary(u)


def diagnostic_operator_data() -> tuple[dict[str, np.ndarray], dict[str, np.ndarray], dict[str, float]]:
    """Frozen theorem-witness common-mode data; explicitly nonphysical."""
    n = 2
    radius = 1.0
    mu = 0.35
    betas = {
        "e_8p": 1.04,
        "e_p4": FROZEN_BERGER_DIAGNOSTIC,
        "e_m4": 1.31,
        "e_8m": 1.47,
    }
    ks = {name: berger_positive_tangential(n, b, radius, mu) for name, b in betas.items()}
    d = next(iter(ks.values())).shape[0]
    us = {
        "e_8p": plane_unitary(d, 0, 1, 0.23, 0.17) @ plane_unitary(d, 2, 3, -0.11, 0.31),
        "e_p4": plane_unitary(d, 1, 2, -0.29, -0.27) @ plane_unitary(d, 4, 5, 0.19, 0.41),
        "e_m4": plane_unitary(d, 0, 2, 0.17, -0.35) @ plane_unitary(d, 3, 4, 0.26, 0.22),
        "e_8m": plane_unitary(d, 1, 4, -0.21, 0.37) @ plane_unitary(d, 2, 5, 0.14, -0.18),
    }
    return ks, us, betas


def endpoint_layout() -> dict[str, tuple[int, int]]:
    return {name: (2 * i, 2 * i + 1) for i, (_, _, name) in enumerate(EDGES)}


def vertex_endpoint_indices() -> dict[str, tuple[int, int]]:
    layout = endpoint_layout()
    by_vertex: dict[str, list[int]] = {v: [] for v in VERTICES}
    for a, b, name in EDGES:
        left, right = layout[name]
        by_vertex[a].append(left)
        by_vertex[b].append(right)
    out = {v: tuple(xs) for v, xs in by_vertex.items()}
    if any(len(xs) != 2 for xs in out.values()):
        raise RuntimeError("diamond must remain degree two")
    return out  # type: ignore[return-value]


def kkt_schur_wentzell(dim: int, vertex_index: int = 0) -> tuple[np.ndarray, dict[str, float]]:
    """Deterministic positive KKT witness W=Hbb-Hbi Hii^-1 Hib.

    This validates the algebraic ownership route only.  The coefficients are
    frozen theorem-witness values and are not the physical BHSM Gram-Hessian.
    """
    d = int(dim)
    if d < 1:
        raise ValueError("dim must be positive")
    q = int(vertex_index)
    hbb = np.diag([0.52 + 0.035 * q + 0.021 * i for i in range(d)]).astype(complex)
    hii = np.diag([1.65 + 0.041 * q + 0.037 * i for i in range(d)]).astype(complex)
    hbi = np.zeros((d, d), dtype=complex)
    for i in range(d):
        hbi[i, i] = 0.075 + 0.004 * q + 0.003 * i
        if i + 1 < d:
            hbi[i, i + 1] = (0.018 + 0.001 * q) * np.exp(1j * (0.11 + 0.03 * i))
    w = hbb - hbi @ np.linalg.solve(hii, np.conjugate(hbi.T))
    w = _as_hermitian(w, "Wentzell Schur complement")
    ev = np.linalg.eigvalsh(w)
    return w, {
        "min_Hii_eigenvalue": float(np.min(np.linalg.eigvalsh(hii))),
        "min_W_eigenvalue": float(np.min(ev)),
        "W_hermiticity_residual": float(np.linalg.norm(w - np.conjugate(w.T))),
    }


def diagnostic_wentzell_blocks(dim: int) -> dict[str, np.ndarray]:
    return {v: kkt_schur_wentzell(dim, i)[0] for i, v in enumerate(VERTICES)}


def wentzell_extension_matrices(dim: int, wentzell: Mapping[str, np.ndarray]) -> tuple[np.ndarray, np.ndarray]:
    """A,B for vector continuity and p_i+p_j+W_v u_v=0.

    W_v is distributed as W_v/2 on the two endpoint values.  On the
    continuity subspace this is exactly W_v u_v.  Hermitian W_v implies the
    exact self-adjoint extension criterion AB*=BA*.
    """
    d = int(dim)
    n_end = 2 * len(EDGES)
    n = n_end * d
    a = np.zeros((n, n), dtype=complex)
    b = np.zeros((n, n), dtype=complex)
    row = 0
    I = np.eye(d, dtype=complex)
    for vertex in VERTICES:
        i_ep, j_ep = vertex_endpoint_indices()[vertex]
        si = slice(i_ep * d, (i_ep + 1) * d)
        sj = slice(j_ep * d, (j_ep + 1) * d)
        rr = slice(row, row + d)
        a[rr, si] = I
        a[rr, sj] = -I
        row += d
        rr = slice(row, row + d)
        w = _as_hermitian(np.asarray(wentzell[vertex]), f"W[{vertex}]")
        if w.shape != (d, d):
            raise ValueError("Wentzell block dimension mismatch")
        a[rr, si] = 0.5 * w
        a[rr, sj] = 0.5 * w
        b[rr, si] = I
        b[rr, sj] = I
        row += d
    return a, b


def wentzell_extension_diagnostics(dim: int = 6) -> dict[str, Any]:
    ws = diagnostic_wentzell_blocks(dim)
    a, b = wentzell_extension_matrices(dim, ws)
    rank = int(np.linalg.matrix_rank(np.concatenate((a, b), axis=1)))
    comm = float(np.linalg.norm(a @ np.conjugate(b.T) - b @ np.conjugate(a.T)))
    mins = {v: float(np.min(np.linalg.eigvalsh(w))) for v, w in ws.items()}
    return {
        "boundary_dimension": int(a.shape[0]),
        "rank_A_B": rank,
        "ABstar_minus_BAstar_norm": comm,
        "minimum_Wentzell_eigenvalues": mins,
        "all_Wentzell_blocks_positive": all(x > 0.0 for x in mins.values()),
        "self_adjoint_Wentzell_extension_pass": rank == a.shape[0] and comm < 1e-12,
    }


def sample_wentzell_domain_data(dim: int = 6, seed: int = 1466) -> tuple[np.ndarray, np.ndarray]:
    rng = np.random.default_rng(seed)
    d = int(dim)
    n_end = 2 * len(EDGES)
    g0 = np.zeros(n_end * d, dtype=complex)
    g1 = np.zeros(n_end * d, dtype=complex)
    ws = diagnostic_wentzell_blocks(d)
    for vertex in VERTICES:
        i_ep, j_ep = vertex_endpoint_indices()[vertex]
        si = slice(i_ep * d, (i_ep + 1) * d)
        sj = slice(j_ep * d, (j_ep + 1) * d)
        u = rng.normal(size=d) + 1j * rng.normal(size=d)
        p = rng.normal(size=d) + 1j * rng.normal(size=d)
        g0[si] = u
        g0[sj] = u
        g1[si] = p
        g1[sj] = -ws[vertex] @ u - p
    return g0, g1


def boundary_green_form(g0_f: np.ndarray, g1_f: np.ndarray, g0_g: np.ndarray, g1_g: np.ndarray) -> complex:
    return np.vdot(g1_f, g0_g) - np.vdot(g0_f, g1_g)


def operator_edge_weyl(length: float, k_tan: np.ndarray, transport: np.ndarray) -> np.ndarray:
    """Exact operator-valued interval Weyl matrix.

    In the source endpoint frame let K>0 and U map source to target.  Then
      A=K coth(l K), B=K csch(l K),
    and
      M=[[A,-B U*],[-U B,U A U*]].
    """
    ell = _finite_positive(length, "length")
    k = _as_hermitian(k_tan, "K")
    ev = np.linalg.eigvalsh(k)
    if float(np.min(ev)) <= 0.0:
        raise ValueError("K must be strictly positive")
    u = _as_unitary(transport, "transport")
    if u.shape != k.shape:
        raise ValueError("K/transport dimension mismatch")
    A = hermitian_function(k, lambda x: x * math.cosh(ell * x) / math.sinh(ell * x))
    B = hermitian_function(k, lambda x: x / math.sinh(ell * x))
    top = np.concatenate((A, -B @ np.conjugate(u.T)), axis=1)
    bottom = np.concatenate((-u @ B, u @ A @ np.conjugate(u.T)), axis=1)
    out = np.concatenate((top, bottom), axis=0)
    return _as_hermitian(out, "edge Weyl")


def assemble_operator_weyl(
    lengths: Mapping[str, float],
    tangential: Mapping[str, np.ndarray],
    transports: Mapping[str, np.ndarray],
) -> np.ndarray:
    d = next(iter(tangential.values())).shape[0]
    m = np.zeros((len(VERTICES) * d, len(VERTICES) * d), dtype=complex)
    for a, b, name in EDGES:
        loc = operator_edge_weyl(lengths[name], tangential[name], transports[name])
        ia, ib = VERTEX_INDEX[a], VERTEX_INDEX[b]
        sa, sb = slice(ia * d, (ia + 1) * d), slice(ib * d, (ib + 1) * d)
        m[sa, sa] += loc[:d, :d]
        m[sa, sb] += loc[:d, d:]
        m[sb, sa] += loc[d:, :d]
        m[sb, sb] += loc[d:, d:]
    return _as_hermitian(m, "global operator Weyl")


def block_diag(mats: Sequence[np.ndarray]) -> np.ndarray:
    dims = [np.asarray(x).shape[0] for x in mats]
    n = sum(dims)
    out = np.zeros((n, n), dtype=complex)
    start = 0
    for x, d in zip(mats, dims):
        out[start:start+d, start:start+d] = x
        start += d
    return out


def global_wentzell_matrix(dim: int) -> np.ndarray:
    ws = diagnostic_wentzell_blocks(dim)
    return block_diag([ws[v] for v in VERTICES])


def response_operator(
    lengths: Mapping[str, float],
    tangential: Mapping[str, np.ndarray],
    transports: Mapping[str, np.ndarray],
) -> np.ndarray:
    m = assemble_operator_weyl(lengths, tangential, transports)
    return _as_hermitian(m + global_wentzell_matrix(next(iter(tangential.values())).shape[0]), "response operator")


def gauge_transform_operator_data(
    tangential: Mapping[str, np.ndarray],
    transports: Mapping[str, np.ndarray],
    vertex_gauges: Mapping[str, np.ndarray],
) -> tuple[dict[str, np.ndarray], dict[str, np.ndarray]]:
    kt: dict[str, np.ndarray] = {}
    ut: dict[str, np.ndarray] = {}
    for a, b, name in EDGES:
        ga = _as_unitary(vertex_gauges[a], f"G[{a}]")
        gb = _as_unitary(vertex_gauges[b], f"G[{b}]")
        kt[name] = ga @ tangential[name] @ np.conjugate(ga.T)
        ut[name] = gb @ transports[name] @ np.conjugate(ga.T)
    return kt, ut


def gauge_transform_global_matrix(m: np.ndarray, vertex_gauges: Mapping[str, np.ndarray]) -> np.ndarray:
    g = block_diag([_as_unitary(vertex_gauges[v]) for v in VERTICES])
    return g @ np.asarray(m, dtype=complex) @ np.conjugate(g.T)


def wilson_loop(transports: Mapping[str, np.ndarray]) -> np.ndarray:
    """Loop M8 -> M5+ -> M4 -> M5- -> M8."""
    return (
        np.conjugate(transports["e_8m"].T)
        @ np.conjugate(transports["e_m4"].T)
        @ transports["e_p4"]
        @ transports["e_8p"]
    )


def unitary_eigenphases(u: np.ndarray) -> np.ndarray:
    x = _as_unitary(u)
    vals = np.linalg.eigvals(x)
    phases = np.asarray([math.atan2(z.imag, z.real) for z in vals], dtype=float)
    return np.sort(phases)


def diagnostic_vertex_gauges(dim: int) -> dict[str, np.ndarray]:
    return {
        "M8": plane_unitary(dim, 0, 2, 0.16, 0.12),
        "M5_plus": plane_unitary(dim, 1, 3, -0.21, -0.28),
        "M5_minus": plane_unitary(dim, 2, 4, 0.18, 0.33),
        "M4": plane_unitary(dim, 0, 5, -0.13, 0.19),
    }


def orthogonal_complement_basis(zero_modes: np.ndarray, ambient_dim: int | None = None, tol: float = 1e-12) -> np.ndarray:
    z = np.asarray(zero_modes, dtype=complex)
    if z.ndim == 1:
        z = z[:, None]
    if z.ndim != 2:
        raise ValueError("zero_modes must be a matrix")
    n = z.shape[0] if ambient_dim is None else int(ambient_dim)
    if z.shape[0] != n:
        raise ValueError("ambient dimension mismatch")
    if z.shape[1] == 0:
        return np.eye(n, dtype=complex)
    u, s, _ = np.linalg.svd(z, full_matrices=True)
    rank = int(np.sum(s > tol))
    return u[:, rank:]


def diagnostic_zero_modes(dim: int) -> np.ndarray:
    n = len(VERTICES) * dim
    z1 = np.zeros(n, dtype=complex)
    z2 = np.zeros(n, dtype=complex)
    for vi in range(len(VERTICES)):
        z1[vi * dim + 0] = 1.0
        z2[vi * dim + 1] = (1.0, -1.0, -1.0, 1.0)[vi]
    z1 /= np.linalg.norm(z1)
    z2 /= np.linalg.norm(z2)
    return np.column_stack((z1, z2))


def projected_response_operator(h: np.ndarray, dim: int) -> tuple[np.ndarray, np.ndarray]:
    z = diagnostic_zero_modes(dim)
    q = orthogonal_complement_basis(z, h.shape[0])
    hp = np.conjugate(q.T) @ h @ q
    return _as_hermitian(hp, "projected response"), q


def matrix_heat_trace(h: np.ndarray, t: float) -> float:
    tt = _finite_positive(t, "t")
    ev = np.linalg.eigvalsh(_as_hermitian(h))
    return math.fsum(math.exp(-tt * float(x)) for x in ev)


def matrix_logdet_positive(h: np.ndarray) -> float:
    ev = np.linalg.eigvalsh(_as_hermitian(h))
    if float(np.min(ev)) <= 0.0:
        raise ValueError("positive logdet requires positive spectrum")
    return math.fsum(math.log(float(x)) for x in ev)


def operator_valued_weyl_payload() -> dict[str, Any]:
    ks, us, betas = diagnostic_operator_data()
    d = next(iter(ks.values())).shape[0]
    lengths = {"e_8p": 1.15, "e_p4": 0.73, "e_m4": 0.91, "e_8m": 1.31}
    m = assemble_operator_weyl(lengths, ks, us)
    g = diagnostic_vertex_gauges(d)
    ksg, usg = gauge_transform_operator_data(ks, us, g)
    mg = assemble_operator_weyl(lengths, ksg, usg)
    expected = gauge_transform_global_matrix(m, g)
    comms = []
    names = list(EDGE_NAMES)
    for i in range(len(names)):
        for j in range(i + 1, len(names)):
            comms.append(float(np.linalg.norm(ks[names[i]] @ ks[names[j]] - ks[names[j]] @ ks[names[i]])))
    ev = np.linalg.eigvalsh(m)
    return {
        "version": VERSION,
        "primary_verdict": PRIMARY_VERDICT,
        "retained_mode_n": 2,
        "common_boundary_mode_dimension": d,
        "berger_beta_diagnostic": betas,
        "lengths_diagnostic": lengths,
        "global_Weyl_hermiticity_residual": float(np.linalg.norm(m - np.conjugate(m.T))),
        "global_Weyl_minimum_eigenvalue": float(np.min(ev)),
        "global_Weyl_positive": bool(np.min(ev) > 0.0),
        "vertex_gauge_covariance_residual": float(np.linalg.norm(mg - expected)),
        "maximum_pairwise_tangential_commutator_norm": max(comms),
        "tangential_blocks_are_not_all_mutually_commuting": max(comms) > 1e-8,
        "physical_M8_M5_M4_operator_claim": False,
        "physical_BHSM_prediction": False,
    }


def nonabelian_holonomy_payload() -> dict[str, Any]:
    ks, us, _ = diagnostic_operator_data()
    d = next(iter(ks.values())).shape[0]
    w = wilson_loop(us)
    phases = unitary_eigenphases(w)
    g = diagnostic_vertex_gauges(d)
    _, ug = gauge_transform_operator_data(ks, us, g)
    wg = wilson_loop(ug)
    phases_g = unitary_eigenphases(wg)
    return {
        "version": VERSION,
        "verdict": HOLONOMY_VERDICT,
        "wilson_unitarity_residual": float(np.linalg.norm(np.conjugate(w.T) @ w - np.eye(d))),
        "wilson_eigenphases_diagnostic": phases.tolist(),
        "wilson_eigenphases_after_vertex_gauge": phases_g.tolist(),
        "gauge_invariant_eigenphase_residual": float(np.max(np.abs(phases - phases_g))),
        "number_of_eigenphases": int(len(phases)),
        "more_than_one_relative_phase_available_kinematically": len(np.unique(np.round(phases - phases[0], 12))) > 2,
        "physical_connection_holonomy_derived": False,
        "physical_BHSM_prediction": False,
    }


def wentzell_payload() -> dict[str, Any]:
    diag = wentzell_extension_diagnostics(6)
    f0, f1 = sample_wentzell_domain_data(6, 1466)
    g0, g1 = sample_wentzell_domain_data(6, 1467)
    green = boundary_green_form(f0, f1, g0, g1)
    return {
        "version": VERSION,
        "verdict": WENTZELL_VERDICT,
        **diag,
        "sample_boundary_green_form_abs": float(abs(green)),
        "retained_mode_Wentzell_domain_closed": bool(diag["self_adjoint_Wentzell_extension_pass"] and abs(green) < 1e-11),
        "Wentzell_source": "diagnostic KKT Schur complement Hbb-Hbi Hii^-1 Hib",
        "physical_action_normalized_core_wall_Gram_Hessian_inserted": False,
        "physical_BHSM_prediction": False,
    }


def operator_no_collapse_payload() -> dict[str, Any]:
    ks, us, _ = diagnostic_operator_data()
    a = {"e_8p": 1.0, "e_p4": 1.0, "e_m4": 1.0, "e_8m": 1.0}
    b = {"e_8p": 0.4, "e_p4": 1.6, "e_m4": 0.7, "e_8m": 1.3}
    ma = assemble_operator_weyl(a, ks, us)
    mb = assemble_operator_weyl(b, ks, us)
    eva = np.linalg.eigvalsh(ma)
    evb = np.linalg.eigvalsh(mb)
    return {
        "version": VERSION,
        "same_total_length": math.isclose(sum(a.values()), sum(b.values())),
        "partition_A": a,
        "partition_B": b,
        "operator_response_spectrum_max_difference": float(np.max(np.abs(eva - evb))),
        "operator_response_trace_difference": float(abs(np.trace(ma).real - np.trace(mb).real)),
        "scalar_circle_partition_collapse_persists_at_operator_response_level": False,
        "claim_scope": "retained operator-valued Calderon/Weyl boundary response; not yet a proof of the full continuum spectrum",
        "physical_BHSM_prediction": False,
    }


def projector_heat_payload() -> dict[str, Any]:
    ks, us, _ = diagnostic_operator_data()
    d = next(iter(ks.values())).shape[0]
    lengths = {"e_8p": 1.15, "e_p4": 0.73, "e_m4": 0.91, "e_8m": 1.31}
    h = response_operator(lengths, ks, us)
    hp, q = projected_response_operator(h, d)
    z = diagnostic_zero_modes(d)
    round_ks = {name: berger_positive_tangential(2, 1.0, 1.0, 0.35) for name in EDGE_NAMES}
    ident_us = {name: np.eye(d, dtype=complex) for name in EDGE_NAMES}
    h0 = response_operator(lengths, round_ks, ident_us)
    h0p = np.conjugate(q.T) @ h0 @ q
    t = 0.55
    rel_heat = matrix_heat_trace(hp, t) - matrix_heat_trace(h0p, t)
    rel_logdet = matrix_logdet_positive(hp) - matrix_logdet_positive(h0p)
    return {
        "version": VERSION,
        "ambient_dimension": int(h.shape[0]),
        "diagnostic_removed_mode_count": int(z.shape[1]),
        "physical_quotient_dimension": int(q.shape[1]),
        "QstarQ_identity_residual": float(np.linalg.norm(np.conjugate(q.T) @ q - np.eye(q.shape[1]))),
        "Qstar_zero_modes_residual": float(np.linalg.norm(np.conjugate(q.T) @ z)),
        "projected_response_hermiticity_residual": float(np.linalg.norm(hp - np.conjugate(hp.T))),
        "projected_response_minimum_eigenvalue": float(np.min(np.linalg.eigvalsh(hp))),
        "diagnostic_relative_response_heat_trace": rel_heat,
        "diagnostic_relative_response_logdet": rel_logdet,
        "full_continuum_relative_heat_supertrace_computed": False,
        "complete_physical_gauge_ghost_zero_mode_projector_derived": False,
        "physical_BHSM_prediction": False,
    }


def berger_geometry_payload() -> dict[str, Any]:
    b = FROZEN_BERGER_DIAGNOSTIC
    d1 = berger_dirac_block(1, b, 1.0)
    got = np.linalg.eigvalsh(d1)
    exp = berger_n1_expected_eigenvalues(b, 1.0)
    d2a = berger_dirac_block(2, 1.04, 1.0)
    d2b = berger_dirac_block(2, 1.47, 1.0)
    return {
        "version": VERSION,
        "beta_diagnostic": b,
        "n1_eigenvalues": got.tolist(),
        "n1_closed_form_eigenvalues": exp.tolist(),
        "n1_closed_form_residual": float(np.max(np.abs(got-exp))),
        "n1_gap_at_frozen_beta": float(np.min(np.abs(got))),
        "n2_cross_beta_commutator_norm": float(np.linalg.norm(d2a @ d2b - d2b @ d2a)),
        "n2_Berger_blocks_noncommuting_across_beta": float(np.linalg.norm(d2a @ d2b - d2b @ d2a)) > 1e-8,
        "use_scope": "exact homogeneous retained S3 boundary-mode geometry; not complete M8/M5/M4 operator provenance",
        "physical_BHSM_prediction": False,
    }


def neutrino_kill_screen_payload() -> dict[str, Any]:
    required = {
        "global_stationary_cosmological_parent_background": False,
        "global_stationary_regular_child_cap": False,
        "actual_action_normalized_M8_tangential_block": False,
        "actual_action_normalized_M5_plus_tangential_block": False,
        "actual_action_normalized_M5_minus_tangential_block": False,
        "actual_intrinsic_M4_fermion_gauge_scalar_block": False,
        "physical_KKT_core_wall_response_Gram_Hessian": False,
        "complete_Calderon_gauge_ghost_zero_mode_projectors": False,
        "continuum_relative_heat_supertrace": False,
        "action_selected_nonabelian_connection_holonomy": False,
        "action_selected_three_transverse_moving_seam_channels": False,
        "physical_detector_projection_map": False,
        "blinded_neutrino_targets_hash_frozen_before_prediction": False,
    }
    return {
        "version": VERSION,
        "purpose": "fail closed before any physical neutrino mass/mixing comparison",
        "required_inputs": required,
        "all_required_inputs_present": all(required.values()),
        "physical_execution_allowed": all(required.values()),
        "current_result": "PHYSICAL_EXECUTION_BLOCKED",
        "postcomparison_parameter_adjustment_allowed": False,
        "physical_mass_or_PMNS_emitted": False,
    }


def status_payload() -> dict[str, Any]:
    return {
        "version": VERSION,
        "primary_verdict": PRIMARY_VERDICT,
        "validated": [
            "Exact homogeneous Berger Dirac retained-mode blocks reproduce the closed n=1 spectrum used by v14.59.",
            "The n=2 Berger blocks at different anisotropies are noncommuting, so retained tangential dynamics need not collapse to scalar propagation.",
            "Positive Hermitian tangential operators have an exact operator-valued interval Calderon/Weyl function by functional calculus.",
            "The assembled operator-valued Weyl map is Hermitian, positive, and covariant under independent vertex unitaries.",
            "A Hermitian KKT Schur-complement Wentzell term yields an exact self-adjoint vector-valued boundary extension.",
            "The non-Abelian Wilson loop has gauge-invariant eigenphases.",
            "Different edge-length partitions with equal total length are distinguished by the retained operator-valued Weyl response.",
            "A deterministic gauge/constraint quotient and finite response heat/logdet pipeline can be run without retuning.",
        ],
        "invalidated": [
            "The v14.65 scalar-circle collapse necessarily persists after noncommuting tangential operator blocks are inserted.",
            "All loop information is exhausted by one scalar U(1) phase once the connection is operator-valued.",
            "A Hermitian dynamic seam term is incompatible with an exact self-adjoint boundary-triple realization.",
        ],
        "reclassified": [
            "The remaining self-adjoint-domain problem is now provenance of the physical tangential/KKT blocks rather than existence of an operator-valued theorem-class extension.",
            "The one scalar diamond phase generalizes to Wilson-loop conjugacy data on a retained internal block.",
            "The repository's open core/wall response Gram-Hessian is the natural source of the physical Wentzell operator.",
            "The current projected heat/logdet object is a finite boundary-response diagnostic, not the full continuum relative heat supertrace.",
        ],
        "open": [
            "evaluate the action-normalized common-attachment core/wall response Gram-Hessian",
            "insert actual M8 tangential Calderon block on the stationary global background",
            "insert actual M5 plus and minus cap Calderon blocks",
            "insert the complete intrinsic M4 fermion/gauge/scalar tangential block",
            "derive the non-Abelian connection holonomy from the stationary action",
            "derive complete physical gauge, ghost, zero-mode and Calderon projectors",
            "derive three transverse moving-seam channel amplitudes/phases",
            "compute the continuum mixed-dimensional relative heat supertrace",
            "exhaust global stationary branches and gauge-reduced Hessian",
            "run the blinded no-retuning neutrino kill screen only after all provenance gates pass",
        ],
    }


def completion_gate_payload() -> dict[str, Any]:
    kill = neutrino_kill_screen_payload()
    return {
        "version": VERSION,
        "primary_verdict": PRIMARY_VERDICT,
        "full_BHSM_complete": False,
        "mark_III": "NOT_REACHED",
        "frozen_predictions_changed": False,
        "official_prediction_logic_changed": False,
        "physical_prediction_emitted": False,
        "usb_touched": False,
        "v14_65_reduced_self_adjoint_domain_retained": True,
        "operator_valued_retained_mode_Weyl_gate_closed": True,
        "retained_mode_Wentzell_self_adjoint_gate_closed": True,
        "scalar_circle_response_collapse_lifted": True,
        "physical_action_normalized_response_Gram_Hessian_closed": False,
        "physical_full_continuum_operator_domain_closed": False,
        "physical_continuum_relative_heat_supertrace_closed": False,
        "neutrino_physical_execution_allowed": kill["physical_execution_allowed"],
        "missing_checks": [k for k, v in kill["required_inputs"].items() if not v],
        "exact_next_object": EXACT_NEXT_OBJECT,
    }


def next_object_payload() -> dict[str, Any]:
    return {
        "version": VERSION,
        "exact_next_object": EXACT_NEXT_OBJECT,
        "closed_in_v14_66": [
            "exact retained S3 Berger tangential block witness",
            "operator-valued Calderon/Weyl functional-calculus gate",
            "non-Abelian Wilson-loop gauge-invariance gate",
            "KKT-Schur Wentzell self-adjoint theorem-class domain",
            "operator-response scalar-collapse lifting witness",
            "diagnostic quotient heat/logdet pipeline",
            "hard no-retuning neutrino execution block",
        ],
        "highest_upstream_physical_blocker": "action-normalized common-attachment core/wall response Gram-Hessian plus actual stratum tangential operator provenance",
        "postcomparison_choice_forbidden": True,
    }


def master_payload() -> dict[str, Any]:
    p = {
        "version": VERSION,
        "primary_verdict": PRIMARY_VERDICT,
        "holonomy_verdict": HOLONOMY_VERDICT,
        "wentzell_verdict": WENTZELL_VERDICT,
        "exact_next_object": EXACT_NEXT_OBJECT,
        "berger_geometry": berger_geometry_payload(),
        "operator_valued_weyl": operator_valued_weyl_payload(),
        "nonabelian_holonomy": nonabelian_holonomy_payload(),
        "wentzell": wentzell_payload(),
        "operator_no_collapse": operator_no_collapse_payload(),
        "projector_heat": projector_heat_payload(),
        "neutrino_kill_screen": neutrino_kill_screen_payload(),
    }
    p["sha256_without_self_hash"] = sha256_payload(p)
    return p


def artifact_payloads() -> dict[str, dict[str, Any]]:
    return {
        "BHSM_operator_valued_calderon_wentzell_v14_66.json": master_payload(),
        "BHSM_berger_common_mode_gate_v14_66.json": berger_geometry_payload(),
        "BHSM_operator_valued_weyl_gate_v14_66.json": operator_valued_weyl_payload(),
        "BHSM_nonabelian_holonomy_gate_v14_66.json": nonabelian_holonomy_payload(),
        "BHSM_kkt_wentzell_gate_v14_66.json": wentzell_payload(),
        "BHSM_operator_no_collapse_gate_v14_66.json": operator_no_collapse_payload(),
        "BHSM_projector_response_heat_gate_v14_66.json": projector_heat_payload(),
        "BHSM_neutrino_kill_screen_v14_66.json": neutrino_kill_screen_payload(),
        "BHSM_status_ledger_v14_66.json": status_payload(),
        "BHSM_next_object_gate_v14_66.json": next_object_payload(),
        "BHSM_completion_gate_v14_66.json": completion_gate_payload(),
    }


def materialize(out_dir: Path) -> list[Path]:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for name, payload in sorted(artifact_payloads().items()):
        path = out / name
        path.write_bytes(canonical_json_bytes(payload) + b"\n")
        written.append(path)
    return written
