"""BHSM v14.56 pair-wake hybrid action and two-gap minimum theorem.

This module performs the next fail-closed action audit after v14.55.

Bounded results
---------------
1. A matter term that acts only on the collective coordinate of an intact pair
   cannot alter an independent internal wake cycle. An explicit collective-to-
   wake cross-coupling is mandatory.
2. Conservative advance/delay kicks must be invertible canonical maps. A
   literal many-to-one phase reset is not generated by a closed Hamiltonian
   action and therefore requires an open-system environment, radiation, or
   measurement channel.
3. One scalar periodic phase supplies only one fundamental phase scale. Three
   detector responses with two independent oscillation gaps require a
   three-component wake monodromy with three eigenphases, or equivalently two
   independent relative phases, while the inception-selected pair identity may
   remain fixed.
4. A deterministic synthetic three-state witness verifies unitarity,
   probability conservation, noncommuting coherent matter kicks, and pair-
   identity preservation. It is not a neutrino prediction.
5. A strict input schema is provided for the still-missing action-derived
   parent/child Dirichlet-to-Neumann and relative heat-kernel coefficients.

No physical mass, mass splitting, PMNS matrix, CKM matrix, coupling, lifetime,
cross section, cosmological radius, or particle spectrum is emitted.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
import cmath
import json
import math
from pathlib import Path
from typing import Any, Iterable, Literal, Sequence

VERSION = "v14.56"

PRIMARY_VERDICT = (
    "BHSM_V14_56_A_COMMON_MODE_PUSH_CHANGES_THE_PAIR_WAKE_ONLY_THROUGH_AN_"
    "EXPLICIT_ACTION_CROSS_COUPLING_CONSERVATIVE_ADVANCE_DELAY_KICKS_ARE_"
    "INVERTIBLE_LITERAL_RESET_IS_OPEN_SYSTEM_AND_TWO_INDEPENDENT_NEUTRINO_"
    "PHASE_GAPS_REQUIRE_A_THREE_EIGENPHASE_WAKE_MONODROMY"
)
SEPARABILITY_VERDICT = (
    "BHSM_A_SEPARABLE_COLLECTIVE_PLUS_INTERNAL_PAIR_ACTION_CANNOT_TRANSFER_A_"
    "COMMON_MODE_MATTER_IMPULSE_INTO_THE_WAKE_PHASE_SO_A_CROSS_COUPLING_IS_"
    "MANDATORY"
)
RESET_VERDICT = (
    "BHSM_ADVANCE_AND_DELAY_MAY_BE_COHERENT_INVERTIBLE_KICKS_BUT_A_LITERAL_"
    "MANY_TO_ONE_PHASE_RESET_REQUIRES_AN_OPEN_SYSTEM_CHANNEL"
)
TWO_GAP_VERDICT = (
    "BHSM_ONE_SCALAR_CYCLE_HAS_PHASE_RANK_ONE_WHILE_THREE_WAKE_RESPONSES_"
    "WITH_TWO_INDEPENDENT_SPLITTINGS_REQUIRE_THREE_FLOQUET_EIGENPHASES_OR_"
    "TWO_RELATIVE_PHASE_COORDINATES_WITH_FIXED_PAIR_IDENTITY"
)
EXACT_NEXT_OBJECT = (
    "ACTION_DERIVED_PARENT_CHILD_DTN_AND_RELATIVE_HEAT_KERNEL_COEFFICIENT_"
    "BUNDLE_INSERTED_INTO_THE_THREE_EIGENPHASE_WAKE_MONODROMY_AND_MOVING_"
    "SEAM_BVP_FOLLOWED_BY_A_NO_RETUNING_GLOBAL_NEUTRINO_KILL_SCREEN"
)

Matrix = tuple[tuple[complex, ...], ...]
Vector = tuple[complex, ...]
Vector3 = tuple[float, float, float]
PhaseMapKind = Literal["coherent", "reset"]


def _finite(values: Iterable[float]) -> bool:
    return all(math.isfinite(float(value)) for value in values)


def normalize_phase(value: float) -> float:
    if not math.isfinite(value):
        raise ValueError("finite phase required")
    return value % (2.0 * math.pi)


def identity(n: int = 3) -> Matrix:
    if n <= 0:
        raise ValueError("positive dimension required")
    return tuple(
        tuple(1.0 + 0j if i == j else 0j for j in range(n)) for i in range(n)
    )


def dagger(matrix: Sequence[Sequence[complex]]) -> Matrix:
    if not matrix:
        raise ValueError("nonempty matrix required")
    rows = len(matrix)
    cols = len(matrix[0])
    if any(len(row) != cols for row in matrix):
        raise ValueError("rectangular matrix required")
    return tuple(
        tuple(complex(matrix[i][j]).conjugate() for i in range(rows))
        for j in range(cols)
    )


def matmul(a: Sequence[Sequence[complex]], b: Sequence[Sequence[complex]]) -> Matrix:
    if not a or not b:
        raise ValueError("nonempty matrices required")
    a_rows = len(a)
    a_cols = len(a[0])
    b_rows = len(b)
    b_cols = len(b[0])
    if any(len(row) != a_cols for row in a) or any(len(row) != b_cols for row in b):
        raise ValueError("rectangular matrices required")
    if a_cols != b_rows:
        raise ValueError("incompatible matrix dimensions")
    return tuple(
        tuple(
            sum(complex(a[i][k]) * complex(b[k][j]) for k in range(a_cols))
            for j in range(b_cols)
        )
        for i in range(a_rows)
    )


def matvec(matrix: Sequence[Sequence[complex]], vector: Sequence[complex]) -> Vector:
    if not matrix or len(matrix[0]) != len(vector):
        raise ValueError("incompatible matrix/vector dimensions")
    return tuple(
        sum(complex(value) * complex(vector[j]) for j, value in enumerate(row))
        for row in matrix
    )


def matsub(a: Sequence[Sequence[complex]], b: Sequence[Sequence[complex]]) -> Matrix:
    if len(a) != len(b) or any(len(x) != len(y) for x, y in zip(a, b)):
        raise ValueError("equal matrix dimensions required")
    return tuple(
        tuple(complex(x) - complex(y) for x, y in zip(row_a, row_b))
        for row_a, row_b in zip(a, b)
    )


def frobenius_norm(matrix: Sequence[Sequence[complex]]) -> float:
    return math.sqrt(
        sum(abs(complex(value)) ** 2 for row in matrix for value in row)
    )


def unitarity_residual(matrix: Sequence[Sequence[complex]]) -> float:
    if not matrix or len(matrix) != len(matrix[0]):
        raise ValueError("nonempty square matrix required")
    product = matmul(dagger(matrix), matrix)
    return frobenius_norm(matsub(product, identity(len(matrix))))


def commutator_norm(a: Sequence[Sequence[complex]], b: Sequence[Sequence[complex]]) -> float:
    return frobenius_norm(matsub(matmul(a, b), matmul(b, a)))


def diagonal_unitary(phases: Sequence[float]) -> Matrix:
    if not phases or not _finite(phases):
        raise ValueError("finite phases required")
    n = len(phases)
    return tuple(
        tuple(cmath.exp(-1j * phases[i]) if i == j else 0j for j in range(n))
        for i in range(n)
    )


def rotation_12(theta: float, phase: float = 0.0) -> Matrix:
    if not _finite((theta, phase)):
        raise ValueError("finite rotation parameters required")
    c = math.cos(theta)
    s = math.sin(theta)
    e_minus = cmath.exp(-1j * phase)
    e_plus = e_minus.conjugate()
    return (
        (c + 0j, s * e_minus, 0j),
        (-s * e_plus, c + 0j, 0j),
        (0j, 0j, 1.0 + 0j),
    )


def rotation_13(theta: float, phase: float = 0.0) -> Matrix:
    if not _finite((theta, phase)):
        raise ValueError("finite rotation parameters required")
    c = math.cos(theta)
    s = math.sin(theta)
    e_minus = cmath.exp(-1j * phase)
    e_plus = e_minus.conjugate()
    return (
        (c + 0j, 0j, s * e_minus),
        (0j, 1.0 + 0j, 0j),
        (-s * e_plus, 0j, c + 0j),
    )


def rotation_23(theta: float, phase: float = 0.0) -> Matrix:
    if not _finite((theta, phase)):
        raise ValueError("finite rotation parameters required")
    c = math.cos(theta)
    s = math.sin(theta)
    e_minus = cmath.exp(-1j * phase)
    e_plus = e_minus.conjugate()
    return (
        (1.0 + 0j, 0j, 0j),
        (0j, c + 0j, s * e_minus),
        (0j, -s * e_plus, c + 0j),
    )


def synthetic_detector_basis() -> Matrix:
    """Deterministic nontrivial unitary basis; not a PMNS prediction."""

    return matmul(
        rotation_23(0.51, 0.0),
        matmul(rotation_13(0.23, 0.79), rotation_12(0.34, 0.0)),
    )


def free_wake_propagator(
    elapsed_proper_time: float,
    angular_frequencies: Sequence[float],
    detector_basis: Sequence[Sequence[complex]],
) -> Matrix:
    if not math.isfinite(elapsed_proper_time) or elapsed_proper_time < 0.0:
        raise ValueError("finite nonnegative elapsed proper time required")
    if len(angular_frequencies) != 3 or not _finite(angular_frequencies):
        raise ValueError("three finite angular frequencies required")
    basis = tuple(tuple(complex(value) for value in row) for row in detector_basis)
    if unitarity_residual(basis) > 1e-10:
        raise ValueError("unitary detector basis required")
    phases = [omega * elapsed_proper_time for omega in angular_frequencies]
    return matmul(basis, matmul(diagonal_unitary(phases), dagger(basis)))


def state_probabilities(state: Sequence[complex]) -> tuple[float, float, float]:
    if len(state) != 3:
        raise ValueError("three-component wake state required")
    raw = tuple(abs(complex(value)) ** 2 for value in state)
    total = sum(raw)
    if total <= 0.0:
        raise ValueError("nonzero wake state required")
    return tuple(float(value / total) for value in raw)  # type: ignore[return-value]


def probability_distance(a: Sequence[float], b: Sequence[float]) -> float:
    if len(a) != len(b):
        raise ValueError("equal probability vectors required")
    return math.sqrt(sum((float(x) - float(y)) ** 2 for x, y in zip(a, b)))


@dataclass(frozen=True)
class CoherentPhaseMap:
    """Invertible orientation-preserving phase kick on S^1.

    phi_plus = phi_minus + offset + modulation*sin(phi_minus+orientation)

    |modulation| < 1 guarantees a positive Jacobian everywhere, so the map is
    invertible and is eligible to be embedded in a conservative canonical
    collision map. This is a kinematic contract, not an action-derived law.
    """

    offset: float
    modulation: float
    orientation: float = 0.0

    def validate(self) -> None:
        if not _finite((self.offset, self.modulation, self.orientation)):
            raise ValueError("finite phase-map parameters required")
        if abs(self.modulation) >= 1.0:
            raise ValueError("|modulation| < 1 required for global invertibility")

    def apply(self, phase: float) -> float:
        self.validate()
        phi = normalize_phase(phase)
        return normalize_phase(
            phi + self.offset + self.modulation * math.sin(phi + self.orientation)
        )

    def jacobian(self, phase: float) -> float:
        self.validate()
        phi = normalize_phase(phase)
        return 1.0 + self.modulation * math.cos(phi + self.orientation)

    def globally_invertible(self) -> bool:
        self.validate()
        return 1.0 - abs(self.modulation) > 0.0


@dataclass(frozen=True)
class CoherentMatterImpulse:
    momentum_kick: Vector3
    phase_map: CoherentPhaseMap
    wake_angle_12: float
    wake_angle_23: float
    wake_phase: float

    def validate(self) -> None:
        if not _finite((*self.momentum_kick, self.wake_angle_12, self.wake_angle_23, self.wake_phase)):
            raise ValueError("finite coherent impulse required")
        self.phase_map.validate()

    def wake_unitary(self) -> Matrix:
        self.validate()
        return matmul(
            rotation_23(self.wake_angle_23, -0.5 * self.wake_phase),
            rotation_12(self.wake_angle_12, self.wake_phase),
        )


@dataclass(frozen=True)
class HybridPairWakeState:
    proper_time: float
    scalar_phase: float
    momentum: Vector3
    wake_state: Vector
    pair_identity: tuple[str, str]
    internal_relation_tag: str

    def validate(self) -> None:
        if not _finite((self.proper_time, self.scalar_phase, *self.momentum)):
            raise ValueError("finite hybrid pair-wake state required")
        if len(self.wake_state) != 3:
            raise ValueError("three-component wake state required")
        if abs(sum(abs(value) ** 2 for value in self.wake_state) - 1.0) > 1e-10:
            raise ValueError("normalized wake state required")
        if len(self.pair_identity) != 2 or not all(self.pair_identity):
            raise ValueError("fixed two-member pair identity required")
        if not self.internal_relation_tag:
            raise ValueError("nonempty internal relation tag required")


def free_evolve_hybrid_state(
    state: HybridPairWakeState,
    elapsed_proper_time: float,
    scalar_frequency: float,
    angular_frequencies: Sequence[float],
    detector_basis: Sequence[Sequence[complex]],
) -> HybridPairWakeState:
    state.validate()
    if not _finite((elapsed_proper_time, scalar_frequency)) or elapsed_proper_time < 0.0:
        raise ValueError("finite nonnegative propagation data required")
    propagator = free_wake_propagator(
        elapsed_proper_time, angular_frequencies, detector_basis
    )
    evolved = matvec(propagator, state.wake_state)
    norm = math.sqrt(sum(abs(value) ** 2 for value in evolved))
    evolved = tuple(value / norm for value in evolved)
    return HybridPairWakeState(
        proper_time=state.proper_time + elapsed_proper_time,
        scalar_phase=normalize_phase(
            state.scalar_phase + scalar_frequency * elapsed_proper_time
        ),
        momentum=state.momentum,
        wake_state=evolved,
        pair_identity=state.pair_identity,
        internal_relation_tag=state.internal_relation_tag,
    )


def apply_coherent_matter_impulse(
    state: HybridPairWakeState,
    impulse: CoherentMatterImpulse,
) -> HybridPairWakeState:
    state.validate()
    impulse.validate()
    kick = impulse.wake_unitary()
    kicked = matvec(kick, state.wake_state)
    norm = math.sqrt(sum(abs(value) ** 2 for value in kicked))
    kicked = tuple(value / norm for value in kicked)
    return HybridPairWakeState(
        proper_time=state.proper_time,
        scalar_phase=impulse.phase_map.apply(state.scalar_phase),
        momentum=tuple(
            component + delta
            for component, delta in zip(state.momentum, impulse.momentum_kick)
        ),  # type: ignore[arg-type]
        wake_state=kicked,
        pair_identity=state.pair_identity,
        internal_relation_tag=state.internal_relation_tag,
    )


def separability_no_go_payload() -> dict[str, Any]:
    return {
        "artifact": "BHSM_pair_wake_separability_no_go_v14_56",
        "version": VERSION,
        "assumed_separable_action": (
            "S=S_cm[X;J_matter]+S_cycle[phi]+S_wake[z] with no X-phi or X-z cross term"
        ),
        "distributional_result": {
            "collective_jump": "Delta P_X = integral F_matter d tau may be nonzero",
            "cycle_jump": "Delta p_phi = 0",
            "wake_jump": "z_plus=z_minus up to free evolution",
        },
        "theorem": (
            "a common-mode matter impulse on X cannot advance, delay, reset, or rotate "
            "an independent wake cycle unless the action contains an explicit cross-coupling"
        ),
        "minimum_allowed_couplings": [
            "continuous term A_mu(phi,X) dot X^mu dot phi",
            "Hermitian wake connection z^dagger A_mu(X,environment) z dot X^mu",
            "localized collision generator G_k(X,phi,z;environment) delta(tau-tau_k)",
        ],
        "pair_identity_exchange_required": False,
        "separability_verdict": SEPARABILITY_VERDICT,
    }


def phase_kick_contract_payload() -> dict[str, Any]:
    witness_map = CoherentPhaseMap(offset=0.31, modulation=0.22, orientation=-0.47)
    sample_phases = [0.0, 0.8, 2.1, 4.7]
    samples = [
        {
            "phase_minus": phase,
            "phase_plus": witness_map.apply(phase),
            "jacobian": witness_map.jacobian(phase),
        }
        for phase in sample_phases
    ]
    return {
        "artifact": "BHSM_symplectic_phase_kick_contract_v14_56",
        "version": VERSION,
        "closed_action_jump": {
            "generating_function": "G_k(X,phi,z;I_k,E_k)",
            "momentum_jump": "P_X^+-P_X^-=-partial_X G_k",
            "cycle_momentum_jump": "p_phi^+-p_phi^-=-partial_phi G_k",
            "coherent_wake_jump": "z^+=exp(-i K_k) z^- with K_k Hermitian",
        },
        "phase_coordinate_map": (
            "phi_plus=phi_minus+Delta(phi_minus,impact,environment) modulo 2pi"
        ),
        "invertibility_condition": "1+partial_phi Delta != 0 everywhere",
        "deterministic_witness": {
            "parameters": asdict(witness_map),
            "globally_invertible": witness_map.globally_invertible(),
            "samples": samples,
            "physical_law": False,
        },
        "impact_dependence_required": [
            "impact strength",
            "impact direction relative to pair motion",
            "pair phase at encounter",
            "local environment",
        ],
    }


def reset_open_system_payload() -> dict[str, Any]:
    return {
        "artifact": "BHSM_phase_reset_open_system_obstruction_v14_56",
        "version": VERSION,
        "literal_reset_map": "phi_plus=phi_reset independent of phi_minus",
        "jacobian": 0.0,
        "invertible": False,
        "closed_hamiltonian_action_compatible": False,
        "allowed_realizations": [
            "radiative damping into unobserved modes",
            "decohering environmental interaction",
            "capture or breakup channel with entropy production",
            "measurement-conditioned state preparation",
        ],
        "density_matrix_form": (
            "rho_plus=sum_a M_a rho_minus M_a^dagger; sum_a M_a^dagger M_a=I"
        ),
        "reclassification": (
            "advance/delay may be coherent action-owned kicks; literal reset is an "
            "environment-owned open-system branch"
        ),
        "reset_verdict": RESET_VERDICT,
    }


def two_gap_minimum_payload() -> dict[str, Any]:
    difference_map = ((-1.0, 1.0, 0.0), (-1.0, 0.0, 1.0))
    determinant_minor = difference_map[0][1] * difference_map[1][2] - difference_map[0][2] * difference_map[1][1]
    gap_dimension = 2 if abs(determinant_minor) > 1e-12 else 1
    return {
        "artifact": "BHSM_three_response_two_gap_minimum_v14_56",
        "version": VERSION,
        "single_scalar_cycle": {
            "form": "phi(tau)=omega tau+phi_0; every Fourier component has frequency n omega",
            "independent_phase_scale_rank": 1,
            "sufficient_for_two_generic_independent_splittings": False,
        },
        "minimum_wake_state": {
            "state": "z(tau) in C^3 with z^dagger z=1",
            "equation": "i D_tau z=H_wake z",
            "monodromy": "U(T) z_j=exp(-i theta_j) z_j",
            "global_phase_removed": True,
            "independent_relative_phase_dimension": gap_dimension,
            "difference_map": [list(row) for row in difference_map],
        },
        "fixed_pair_condition": "D_tau Xi_AB=0",
        "detector_map": "P_alpha=|<D_alpha,z>|^2 for alpha=e,mu,tau",
        "interpretation": (
            "the pair does not change identity; the three-component geometric wake "
            "acquires two independent relative phases"
        ),
        "two_gap_verdict": TWO_GAP_VERDICT,
    }


def hybrid_action_payload() -> dict[str, Any]:
    return {
        "artifact": "BHSM_pair_wake_hybrid_action_v14_56",
        "version": VERSION,
        "fixed_pair": "Xi_AB is selected at inception and D_tau Xi_AB=0",
        "closed_coherent_action": (
            "S_closed=integral d tau [P_mu dot X^mu+p_phi dot phi+i z^dagger D_tau z"
            "-H_pair(Xi)-H_cm-H_phi-z^dagger H_wake z-H_cross]"
            "-sum_k G_k delta(tau-tau_k)"
        ),
        "mandatory_cross_term": (
            "H_cross or G_k must depend jointly on collective motion/environment and "
            "the wake variables; otherwise a common-mode push cannot alter flavor response"
        ),
        "coherent_matter_map": {
            "collective": "P_X^+=P_X^-+I_k",
            "scalar_cycle": "phi^+=R_k(phi^-,I_k,E_k) with nonzero Jacobian",
            "wake": "z^+=exp(-i K_k(I_k,E_k))z^-",
            "pair_identity": "unchanged",
        },
        "open_branch": (
            "S_closed must be enlarged by environment/radiation degrees of freedom before "
            "a reduced many-to-one reset map is permitted"
        ),
        "mass_readout": (
            "physical mass remains a parent-relative complete-cycle Hamiltonian/Floquet "
            "quasi-energy, not an instantaneous wake label"
        ),
        "physical_coefficients_derived": False,
    }


def synthetic_hybrid_monodromy_witness() -> dict[str, Any]:
    basis = synthetic_detector_basis()
    frequencies = (0.0, 0.43, 1.37)
    scalar_frequency = 0.71
    initial = HybridPairWakeState(
        proper_time=0.0,
        scalar_phase=0.18,
        momentum=(1.0, 0.0, 0.0),
        wake_state=(1.0 + 0j, 0j, 0j),
        pair_identity=("A", "B"),
        internal_relation_tag="fixed_at_inception",
    )
    before = free_evolve_hybrid_state(
        initial, 1.3, scalar_frequency, frequencies, basis
    )
    impulse = CoherentMatterImpulse(
        momentum_kick=(0.0, 0.23, -0.04),
        phase_map=CoherentPhaseMap(offset=-0.27, modulation=0.18, orientation=0.61),
        wake_angle_12=0.29,
        wake_angle_23=-0.17,
        wake_phase=0.73,
    )
    kicked = apply_coherent_matter_impulse(before, impulse)
    after = free_evolve_hybrid_state(
        kicked, 0.9, scalar_frequency, frequencies, basis
    )
    no_kick = free_evolve_hybrid_state(
        before, 0.9, scalar_frequency, frequencies, basis
    )
    baseline_generator_proxy = diagonal_unitary(frequencies)
    wake_kick = impulse.wake_unitary()
    probabilities = {
        "initial": state_probabilities(initial.wake_state),
        "before_kick": state_probabilities(before.wake_state),
        "immediately_after_kick": state_probabilities(kicked.wake_state),
        "after_kick_propagation": state_probabilities(after.wake_state),
        "counterfactual_no_kick": state_probabilities(no_kick.wake_state),
    }
    return {
        "artifact": "BHSM_synthetic_hybrid_monodromy_witness_v14_56",
        "version": VERSION,
        "status": "SYNTHETIC_UNITARY_CAPABILITY_WITNESS_NOT_A_NEUTRINO_PREDICTION",
        "angular_frequencies": list(frequencies),
        "two_independent_gap_witness": [
            frequencies[1] - frequencies[0],
            frequencies[2] - frequencies[0],
        ],
        "basis_unitarity_residual": unitarity_residual(basis),
        "kick_unitarity_residual": unitarity_residual(wake_kick),
        "kick_noncommutator_norm": commutator_norm(baseline_generator_proxy, wake_kick),
        "phase_map_minimum_jacobian_bound": 1.0 - abs(impulse.phase_map.modulation),
        "probabilities": {key: list(value) for key, value in probabilities.items()},
        "probability_sums": {
            key: sum(value) for key, value in probabilities.items()
        },
        "matter_kick_changes_later_detector_probabilities": (
            probability_distance(
                probabilities["after_kick_propagation"],
                probabilities["counterfactual_no_kick"],
            )
            > 1e-6
        ),
        "pair_identity_preserved": (
            initial.pair_identity
            == before.pair_identity
            == kicked.pair_identity
            == after.pair_identity
        ),
        "internal_relation_preserved": (
            initial.internal_relation_tag
            == before.internal_relation_tag
            == kicked.internal_relation_tag
            == after.internal_relation_tag
        ),
        "physical_PMNS_emitted": False,
        "physical_splittings_emitted": False,
        "action_derived_coefficients_used": False,
    }


def dtn_heat_kernel_input_schema_payload() -> dict[str, Any]:
    return {
        "artifact": "BHSM_dtn_heat_kernel_input_schema_v14_56",
        "version": VERSION,
        "status": "STRICT_INPUT_SCHEMA_ONLY_NO_ACTION_DERIVED_KERNEL_BUNDLE_PRESENT",
        "required_provenance": [
            "repository commit and branch",
            "parent and child background hashes",
            "gauge-fixing operator and domain",
            "zero-mode projector hash",
            "renormalization prescription and scale",
            "derivation notebook or symbolic artifact hash",
        ],
        "required_geometry": [
            "cosmological parent radius or symbolic anchor",
            "child/parent ratio lambda",
            "Berger parameter a",
            "period T",
            "moving-seam embedding and normal orientation",
        ],
        "required_mode_data": [
            "three normalized Peter-Weyl harmonics",
            "parent DtN 3x3 Hermitian matrix",
            "child DtN 3x3 Hermitian matrix",
            "shape-current 3x3 Hermitian wake generator",
            "mode Gram matrix and zero-mode exclusions",
        ],
        "required_relative_spectral_data": [
            "trace-class proof for Delta exp(-t D^2)",
            "relative heat-trace samples or exact representation",
            "small-t subtraction coefficients",
            "large-t convergence bound",
            "relative zeta value and derivative",
            "lambda, a, and seam-amplitude derivatives",
        ],
        "physical_acceptance_conditions": [
            "all matrices Hermitian within declared tolerance",
            "all provenance hashes non-placeholder",
            "trace-class and gauge-domain proofs marked complete",
            "same coefficient bundle used for vacuum and matter propagation",
            "no measured neutrino quantity used to select coefficients",
        ],
        "bundle_present": False,
        "physical_BVP_execution_allowed": False,
    }


def completion_payload() -> dict[str, Any]:
    synthetic = synthetic_hybrid_monodromy_witness()
    minimum = two_gap_minimum_payload()
    return {
        "artifact": "BHSM_completion_gate_v14_56",
        "version": VERSION,
        "primary_verdict": PRIMARY_VERDICT,
        "validated": [
            "separable common-mode and internal actions cannot transmit a matter phase kick",
            "an explicit collective-to-wake action cross-coupling is mandatory",
            "coherent advance/delay phase maps must be invertible",
            "literal reset is an open-system rather than closed-action branch",
            "one scalar cycle has phase rank one",
            "a normalized three-component wake has two independent relative phases",
            "a synthetic unitary matter-kick witness preserves pair identity and probability",
            "the DtN and relative heat-kernel insertion gate is now a strict schema",
        ],
        "invalidated_or_reclassified": [
            "a direct whole-pair push automatically changes flavor without cross-coupling",
            "a many-to-one phase reset can be generated by an isolated Hamiltonian action",
            "one scalar periodic phase alone generically supplies two independent splittings",
            "the synthetic frequencies or detector basis are BHSM predictions",
            "three detected responses require exchange of the inception-selected pair members",
        ],
        "open": [
            "action-derived collective-to-wake cross-coupling",
            "matched parent and child backgrounds",
            "physical parent/child DtN matrices",
            "trace-class relative heat kernel and nonlocal determinant",
            "action-selected three-eigenphase wake generator",
            "physical coherent matter impulse kernel",
            "two neutrino phase splittings, detector map, CP behavior and quasi-energies",
            "global no-retuning neutrino kill screen",
            "duplicate-capture amplitude and radiation spectrum",
            "nested color-neutral hadron orbit and Wilson area law",
            "full gauge-fixed Floquet stability",
        ],
        "diagnostics": {
            "single_scalar_phase_rank": minimum["single_scalar_cycle"]["independent_phase_scale_rank"],
            "three_wake_relative_phase_dimension": minimum["minimum_wake_state"]["independent_relative_phase_dimension"],
            "synthetic_basis_unitarity_residual": synthetic["basis_unitarity_residual"],
            "synthetic_kick_unitarity_residual": synthetic["kick_unitarity_residual"],
            "synthetic_kick_noncommutator_norm": synthetic["kick_noncommutator_norm"],
            "pair_identity_preserved": synthetic["pair_identity_preserved"],
        },
        "Mark_I": "REACHED",
        "Mark_II": "CONDITIONAL",
        "Mark_III": "NOT_REACHED",
        "BHSM_physical_completion": False,
        "validation_passed": True,
        "validation": {
            "frozen_predictions_changed": False,
            "official_prediction_logic_changed": False,
            "physical_mass_emitted": False,
            "physical_mass_splitting_emitted": False,
            "physical_PMNS_emitted": False,
            "physical_CKM_emitted": False,
            "physical_coupling_emitted": False,
            "full_repository_suite_run": False,
            "USB_untouched": True,
        },
        "exact_next_object": EXACT_NEXT_OBJECT,
    }


def _json_text(payload: dict[str, Any]) -> str:
    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def materialize(output: str | Path) -> list[Path]:
    output_path = Path(output)
    output_path.mkdir(parents=True, exist_ok=True)
    payloads = {
        "BHSM_pair_wake_separability_no_go_v14_56.json": separability_no_go_payload(),
        "BHSM_symplectic_phase_kick_contract_v14_56.json": phase_kick_contract_payload(),
        "BHSM_phase_reset_open_system_obstruction_v14_56.json": reset_open_system_payload(),
        "BHSM_three_response_two_gap_minimum_v14_56.json": two_gap_minimum_payload(),
        "BHSM_pair_wake_hybrid_action_v14_56.json": hybrid_action_payload(),
        "BHSM_synthetic_hybrid_monodromy_witness_v14_56.json": synthetic_hybrid_monodromy_witness(),
        "BHSM_dtn_heat_kernel_input_schema_v14_56.json": dtn_heat_kernel_input_schema_payload(),
        "BHSM_completion_gate_v14_56.json": completion_payload(),
    }
    written: list[Path] = []
    for name, payload in sorted(payloads.items()):
        target = output_path / name
        target.write_text(_json_text(payload), encoding="utf-8", newline="\n")
        written.append(target)
    return written


__all__ = [
    "CoherentMatterImpulse",
    "CoherentPhaseMap",
    "EXACT_NEXT_OBJECT",
    "HybridPairWakeState",
    "PRIMARY_VERDICT",
    "RESET_VERDICT",
    "SEPARABILITY_VERDICT",
    "TWO_GAP_VERDICT",
    "VERSION",
    "apply_coherent_matter_impulse",
    "commutator_norm",
    "completion_payload",
    "dtn_heat_kernel_input_schema_payload",
    "free_evolve_hybrid_state",
    "free_wake_propagator",
    "hybrid_action_payload",
    "materialize",
    "phase_kick_contract_payload",
    "reset_open_system_payload",
    "separability_no_go_payload",
    "state_probabilities",
    "synthetic_detector_basis",
    "synthetic_hybrid_monodromy_witness",
    "two_gap_minimum_payload",
    "unitarity_residual",
]
