"""Exact paired linear/quadratic support-connection expansions."""

from __future__ import annotations

from typing import Any


def real_scalar_expansion(phi: int, dphi: int, weight: int, a: int) -> tuple[int, int, int, int]:
    """Return exact norm, parent, linear, and quadratic pieces for D=d-wA."""

    parent = dphi * dphi
    linear = -2 * weight * a * phi * dphi
    quadratic = weight * weight * a * a * phi * phi
    return (dphi - weight * a * phi) ** 2, parent, linear, quadratic


def coupling_ledger() -> list[dict[str, Any]]:
    blocked = "weight/pairing not action-owned"
    return [
        {
            "sector": "real scalar",
            "exact_norm": "|D phi|^2=|nabla phi|^2-2w A_D.phi nabla phi+w^2 A_D^2 phi^2",
            "linear_term": "-2w A_D.phi nabla phi",
            "quadratic_term": "+w^2 A_D^2 phi^2",
            "integration_by_parts": "-w A_D.d(phi^2)=+w phi^2 div(A_D)-w boundary(n.A_D phi^2)",
            "momentum_shift": "Pi_phi=Pi_phi,parent-w sqrt(gamma) A_D,normal phi (signature convention dependent)",
            "stress_and_current": "fixed uniquely once w and the kinetic coefficient are action-owned",
            "status": blocked,
        },
        {
            "sector": "complex Hermitian co-scaling scalar",
            "exact_norm": "(D phi)^dagger D phi=|nabla phi|^2-w A_D.(phi^dagger nabla phi+(nabla phi)^dagger phi)+w^2 A_D^2|phi|^2",
            "linear_term": "Hermitian radial current, not the U(1) phase current",
            "quadratic_term": "+w^2 A_D^2|phi|^2",
            "integration_by_parts": "linear term is -w A_D.d|phi|^2 plus its boundary term",
            "momentum_shift": "paired shift in Pi_phi and Pi_phi_dagger",
            "stress_and_current": "requires the action to declare Hermitian co-scaling rather than contragredient duality",
            "status": blocked,
        },
        {
            "sector": "dual-paired field",
            "exact_norm": "D^(-w)Phi* paired with D^(w)Phi; signs follow the two opposite characters",
            "linear_term": "antisymmetric representation current determined by the declared pairing",
            "quadratic_term": "the product of opposite connection charges; never selectable independently",
            "integration_by_parts": "boundary Green form inherits the pairing character",
            "momentum_shift": "dual canonical momenta shift oppositely",
            "stress_and_current": "current unavailable because the parent action supplies no G_D pairing law",
            "status": blocked,
        },
        {
            "sector": "fermion",
            "exact_norm": "first-order Dirac terms are at most linear in A_D before eliminating auxiliaries; a standalone A_D^2 fermion seagull is not generated by minimal first-order covariantization",
            "linear_term": "-w bar(psi) Gamma^A A_D,A psi, with adjoint character fixed by the support pairing",
            "quadratic_term": "none for a primitive first-order Dirac operator; may arise only after squaring/reduction and must not be inserted independently",
            "integration_by_parts": "Dirac Green boundary form",
            "momentum_shift": "first-order constraint structure, not a scalar momentum shift",
            "stress_and_current": "blocked by adjoint/pairing character and chiral anomaly audit",
            "status": blocked,
        },
        {
            "sector": "gauge",
            "exact_norm": "no A_D coupling follows when the non-Abelian gauge connection has forced multiplicative weight zero",
            "linear_term": None,
            "quadratic_term": None,
            "integration_by_parts": None,
            "momentum_shift": None,
            "stress_and_current": "unchanged in the tested coframe candidate",
            "status": "TRIVIAL_ZERO_IN_TESTED_CANDIDATE",
        },
        {
            "sector": "geometry/wall/boundary/compatibility/core",
            "exact_norm": None,
            "linear_term": None,
            "quadratic_term": None,
            "integration_by_parts": None,
            "momentum_shift": None,
            "stress_and_current": None,
            "status": "NO_PRIMITIVE_CHARACTER_OR_COMPLETE_LOCAL_TERM",
        },
    ]


def couplings_payload() -> dict[str, Any]:
    exact, parent, linear, quadratic = real_scalar_expansion(2, 5, 3, 7)
    validation = {
        "real_scalar_identity_exact": exact == parent + linear + quadratic,
        "linear_never_without_quadratic_for_second_order_scalar": all(row["quadratic_term"] is not None for row in coupling_ledger()[:3]),
        "fermion_first_order_exception_explicit": coupling_ledger()[3]["quadratic_term"].startswith("none for a primitive"),
        "gauge_zero_weight_respected": coupling_ledger()[4]["linear_term"] is None,
        "frozen_limit": real_scalar_expansion(2, 5, 3, 0)[0] == 25,
    }
    return {
        "artifact": "BHSM_support_linear_quadratic_connection_couplings_v11_2",
        "connection_convention": "delta Phi=+w epsilon Phi, delta A_D=d epsilon, D=nabla-w A_D",
        "sectors": coupling_ledger(),
        "complete_linear_couplings": None,
        "complete_quadratic_couplings": None,
        "complete_boundary_contributions": None,
        "complete_canonical_momentum_shifts": None,
        "frozen_limit": "A_D=0 at constant upsilon=1 restores every parent kinetic term",
        "status": "EXACT_COUPLING_IDENTITIES_DERIVED_CONDITIONALLY; COEFFICIENT_LEDGER_NOT_ACTION_FIXED",
        "validation": validation,
        "validation_passed": all(validation.values()),
    }

